"""
Django settings for pokertrace project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import firebase_admin
from django.core.exceptions import ImproperlyConfigured
from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR=Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 由環境變數提供，請勿把正式金鑰寫進 repo。
SECRET_KEY=os.environ.get("DJANGO_SECRET_KEY","")

# SECURITY WARNING: don't run with debug turned on in production!
# 預設關閉；本地開發時設定環境變數 DJANGO_DEBUG=1 才開啟。
DEBUG=os.environ.get("DJANGO_DEBUG","0")=="1"

# 本地 DEBUG 若未設定金鑰則退回開發用金鑰；非 DEBUG 未設定時直接啟動失敗，避免正式環境用到硬編金鑰。
if not SECRET_KEY:
	if DEBUG:
		SECRET_KEY="django-insecure-dev-only-change-me"
	else:
		raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable is required when DEBUG is off")

# 以逗號分隔的允許主機清單，例如 "example.com,api.example.com"。
ALLOWED_HOSTS=[host.strip() for host in os.environ.get("DJANGO_ALLOWED_HOSTS","").split(",") if host.strip()]
if DEBUG and not ALLOWED_HOSTS:
	ALLOWED_HOSTS=["localhost","127.0.0.1"]


# ── 錯誤紀錄 (logging) ───────────────────────────────────────────────
# 將後端錯誤寫入 backend/log/ 下的檔案，方便日後維護排查。
# 涵蓋：Django 4xx/5xx 請求錯誤 (django.request)、DisallowedHost 等安全事件
# (django.security)、以及其他 WARNING 以上的訊息。檔案會自動輪替，避免無限長大。
LOG_DIR=BASE_DIR / "log"
os.makedirs(LOG_DIR,exist_ok=True)

LOGGING={
	"version": 1,
	"disable_existing_loggers": False,
	"formatters": {
		"verbose": {
			"format": "[{asctime}] {levelname} {name} ({process:d}): {message}",
			"style": "{",
		},
	},
	"handlers": {
		"errorfile": {
			"level": "WARNING",
			"class": "logging.handlers.RotatingFileHandler",
			"filename": str(LOG_DIR / "error.log"),
			"maxBytes": 10*1024*1024,
			"backupCount": 10,
			"encoding": "utf-8",
			"formatter": "verbose",
		},
	},
	"loggers": {
		# 4xx/5xx 請求錯誤（含被 ALLOWED_HOSTS 擋下的 400）
		"django.request": {
			"handlers": ["errorfile"],
			"level": "WARNING",
			"propagate": False,
		},
		# DisallowedHost、SuspiciousOperation 等安全事件；訊息會帶出被拒絕的 Host
		"django.security": {
			"handlers": ["errorfile"],
			"level": "WARNING",
			"propagate": False,
		},
		# 其餘 Django 內部 WARNING 以上訊息
		"django": {
			"handlers": ["errorfile"],
			"level": "WARNING",
			"propagate": False,
		},
		# 統一例外處理 middleware 寫入的未捕捉例外（含 traceback）
		"pokertrace": {
			"handlers": ["errorfile"],
			"level": "ERROR",
			"propagate": False,
		},
	},
}


# Application definition

INSTALLED_APPS=[
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    'channels',
]

MIDDLEWARE=[
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	"corsheaders.middleware.CorsMiddleware",
	# 統一例外處理：攔截未捕捉例外，回通用錯誤碼、完整錯誤只進 error.log（檢查表 1.4）
	"pokertrace.middleware.ExceptionMiddleware",
	# 記錄每一次後端 API 請求，供 admin.html 稽核使用
	"pokertrace.middleware.ApiLogMiddleware",
]

ROOT_URLCONF="pokertrace.urls"

TEMPLATES=[
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION="pokertrace.wsgi.application"
ASGI_APPLICATION="pokertrace.asgi.application"

# WebSocket channel layer
# 多行程(多 worker)時必須用 Redis，跨行程才能共用 websocket 廣播(計時器/顯示端同步)。
# 需先安裝: pip install channels_redis，並啟動 Redis(127.0.0.1:6379)。
CHANNEL_LAYERS={
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1",6379)]
        }
    }
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES={
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS=[
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE='en-us'

TIME_ZONE='Asia/Taipei'

USE_I18N=True

USE_TZ=True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL='static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'

# 跨來源請求只允許白名單網域（以逗號分隔，例如 "https://app.example.com,https://example.com"）。
# 正式環境務必設定 DJANGO_CORS_ALLOWED_ORIGINS；未設定且 DEBUG 時才退回本地開發來源。
CORS_ALLOWED_ORIGINS=[origin.strip() for origin in os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS","").split(",") if origin.strip()]
if DEBUG and not CORS_ALLOWED_ORIGINS:
	CORS_ALLOWED_ORIGINS=["http://localhost","http://127.0.0.1","http://localhost:8000","http://127.0.0.1:8000"]
CORS_ALLOW_CREDENTIALS=True

EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST=os.environ.get("EMAIL_HOST","smtp.gmail.com")
EMAIL_PORT=int(os.environ.get("EMAIL_PORT","587"))
# SMTP 帳密改由環境變數提供，請勿寫進 repo（外洩的金鑰應立即撤銷/輪替）。
EMAIL_HOST_USER=os.environ.get("EMAIL_HOST_USER","")
EMAIL_HOST_PASSWORD=os.environ.get("EMAIL_HOST_PASSWORD","")
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL=EMAIL_HOST_USER

# 正式環境(非 DEBUG)時啟用基本安全標頭與 cookie 保護。
if not DEBUG:
	SECURE_SSL_REDIRECT=True
	SESSION_COOKIE_SECURE=True
	CSRF_COOKIE_SECURE=True
	SECURE_HSTS_SECONDS=31536000
	SECURE_HSTS_INCLUDE_SUBDOMAINS=True
	SECURE_HSTS_PRELOAD=True
	SECURE_CONTENT_TYPE_NOSNIFF=True
	SECURE_PROXY_SSL_HEADER=("HTTP_X_FORWARDED_PROTO","https")

# Firebase 憑證路徑亦改由環境變數指定（憑證檔請勿入庫）。
# 初始化失敗（例如缺憑證檔）時不擋整個服務啟動，只印警告並讓相關功能降級。
FIREBASE_CREDENTIAL_PATH=os.environ.get("FIREBASE_CREDENTIAL_PATH","pokertrace-firebase-adminsdk-fbsvc-bdb33658a6.json")
if not firebase_admin._apps:
    try:
        cred = credentials.Certificate(FIREBASE_CREDENTIAL_PATH)
        firebase_admin.initialize_app(cred)
    except Exception as error:
        print("WARNING: firebase initialize failed, related features disabled:",error)
