import json
import threading

from django.core.mail import send_mail
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from function.sql import *
from function.thing import *
from function.function import *
from .initialize import *


CONTACTNOTIFYEMAIL="chris960527ho@gmail.com"
# 公開端點頻率限制: 同一 IP (取不到 IP 時改用 email) 在 CONTACTRATELIMITMINUTE 分鐘內最多 CONTACTRATELIMITCOUNT 筆
CONTACTRATELIMITMINUTE=10
CONTACTRATELIMITCOUNT=3


def asyncsendmail(*args,**kwargs):
	threading.Thread(target=send_mail,args=args,kwargs=kwargs).start()


def gettokenuser(request):
	header=request.headers.get("Authorization")
	token=None
	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return None,errorresponse("ERROR_token_not_found")
	if not token:
		return None,errorresponse("ERROR_token_not_found")
	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return None,errorresponse("ERROR_token_error")
	userrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow[0]["userid"]],SETTING["dbsetting"])
	if not userrow:
		return None,errorresponse("ERROR_user_not_found")
	return userrow[0],None


def cleantext(value,limit):
	value=str(value or "").strip()
	if limit and limit<len(value):
		value=value[:limit]
	return value


def ensurecontactschema():
	query(SETTING["dbname"],"""
		CREATE TABLE IF NOT EXISTS public.contactmessage(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			userid bigint,
			name varchar(100) NOT NULL,
			email varchar(150) NOT NULL,
			subject varchar(150) NOT NULL DEFAULT '',
			message text NOT NULL,
			status varchar(20) NOT NULL DEFAULT 'new',
			replysubject varchar(150) NOT NULL DEFAULT '',
			replymessage text NOT NULL DEFAULT '',
			replytime timestamp with time zone,
			replyuserid bigint,
			ip varchar(80) NOT NULL DEFAULT '',
			useragent text NOT NULL DEFAULT '',
			createtime timestamp with time zone NOT NULL DEFAULT now(),
			updatetime timestamp with time zone NOT NULL DEFAULT now(),
			deletetime timestamp with time zone
		)
	""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replysubject varchar(150) NOT NULL DEFAULT ''""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replymessage text NOT NULL DEFAULT ''""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replytime timestamp with time zone""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replyuserid bigint""",[],SETTING["dbsetting"])


@api_view(["POST"])
def newcontactmessage(request):
	try:
		ensurecontactschema()
		data=json.loads(request.body or "{}")
		name=cleantext(data.get("name"),100)
		email=cleantext(data.get("email"),150)
		subject=cleantext(data.get("subject"),150)
		message=cleantext(data.get("message"),3000)
		userid=None
		header=request.headers.get("Authorization")
		if header:
			try:
				token=header.split("Bearer ")[1]
				tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
				if tokenrow:
					userid=tokenrow[0]["userid"]
			except Exception as error:
				userid=None
		if not name or not email or not message:
			return errorresponse("ERROR_request_data_not_found")
		if "@" not in email:
			return errorresponse("ERROR_request_data_type_error")
		# 優先取 nginx 設的 X-Real-IP，取不到才 fallback REMOTE_ADDR；本部署兩者都是真實 client IP
		# (uvicorn proxy_headers 預設開啟，已從 X-Forwarded-For 還原真實來源；nginx 兩條 location 也都有
		#  proxy_set_header X-Real-IP $remote_addr，會覆寫用戶端偽造的標頭值)
		# (此 ip 同時用於頻率限制計數與寫入 contactmessage.ip 欄)
		ip=request.META.get("HTTP_X_REAL_IP") or request.META.get("REMOTE_ADDR","")
		useragent=request.META.get("HTTP_USER_AGENT","")
		# 免登入公開端點, 用 contactmessage 既有 ip 欄位做簡易頻率限制 (不含軟刪過濾, 刪除訊息不會重置額度);
		# 取不到 IP 時退而以 email 計數
		if ip:
			ratelimitrow=query(SETTING["dbname"],"""SELECT COUNT(*) AS total FROM "contactmessage" WHERE "ip"=%s AND "createtime">=NOW()-make_interval(mins=>%s)""",[ip,CONTACTRATELIMITMINUTE],SETTING["dbsetting"])
		else:
			ratelimitrow=query(SETTING["dbname"],"""SELECT COUNT(*) AS total FROM "contactmessage" WHERE "email"=%s AND "createtime">=NOW()-make_interval(mins=>%s)""",[email,CONTACTRATELIMITMINUTE],SETTING["dbsetting"])
		if ratelimitrow and CONTACTRATELIMITCOUNT<=int(ratelimitrow[0]["total"]):
			return Response({
				"success": False,
				"data": "ERROR_too_many_requests"
			},status.HTTP_429_TOO_MANY_REQUESTS)
		query(SETTING["dbname"],f"""
			INSERT INTO "contactmessage"("userid","name","email","subject","message","ip","useragent","createtime","updatetime")
			VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s)
		""",[userid,name,email,subject,message,ip,useragent,nowtime(),nowtime()],SETTING["dbsetting"])
		notifysubject="PokerTrace 新聯絡訊息"
		if subject:
			notifysubject=notifysubject+"："+subject
		notifybody=f"""PokerTrace 收到新的聯絡訊息：

姓名：{name}
Email：{email}
主旨：{subject or "未填主旨"}
時間：{nowtime()}

內容：
{message}

請到聯絡訊息後台查看與回覆。
"""
		asyncsendmail(notifysubject,notifybody,None,[CONTACTNOTIFYEMAIL],fail_silently=True)
		return Response({
			"success": True,
			"data": ""
		},status.HTTP_200_OK)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] "+str(error),"")
		return Response({
			"success": False,
			"data": "ERROR_unknow_error_pls_tell_the_admin"
		},status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(["GET"])
def getcontactmessages(request):
	try:
		ensurecontactschema()
		userrow,errresp=gettokenuser(request)
		if errresp:
			return errresp
		if 4>int(userrow["permission"]):
			return errorresponse("ERROR_no_permission")
		page=int(request.GET.get("page") or 1)
		limit=int(request.GET.get("limit") or 20)
		statusfilter=cleantext(request.GET.get("status"),20)
		if page<1:
			page=1
		if limit<1:
			limit=20
		if 100<limit:
			limit=100
		offset=(page-1)*limit
		where=["cm.\"deletetime\" IS NULL"]
		params=[]
		if statusfilter:
			where.append("cm.\"status\"=%s")
			params.append(statusfilter)
		wheresql=" AND ".join(where)
		countrow=query(SETTING["dbname"],f"""
			SELECT COUNT(*) AS total
			FROM "contactmessage" cm
			WHERE {wheresql}
		""",params,SETTING["dbsetting"])
		row=query(SETTING["dbname"],f"""
			SELECT
				cm.*,
				u."name" AS username,
				u."playerid" AS userplayerid
			FROM "contactmessage" cm
			LEFT JOIN "user" u ON u."id"=cm."userid"
			WHERE {wheresql}
			ORDER BY cm."createtime" DESC,cm."id" DESC
			LIMIT %s OFFSET %s
		""",params+[limit,offset],SETTING["dbsetting"])
		total=0
		if countrow:
			total=countrow[0]["total"]
		totalpages=(total+limit-1)//limit
		if totalpages<=0:
			totalpages=1
		if totalpages<page:
			page=totalpages
		return Response({
			"success": True,
			"data": {
				"messages": row or [],
				"pagination": {
					"page": page,
					"limit": limit,
					"total": total,
					"totalpages": totalpages,
					"hasprev": 1<page,
					"hasnext": page<totalpages
				}
			}
		},status.HTTP_200_OK)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] "+str(error),"")
		return Response({
			"success": False,
			"data": "ERROR_unknow_error_pls_tell_the_admin"
		},status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(["PUT"])
def editcontactmessage(request,messageid):
	try:
		ensurecontactschema()
		userrow,errresp=gettokenuser(request)
		if errresp:
			return errresp
		if 4>int(userrow["permission"]):
			return errorresponse("ERROR_no_permission")
		data=json.loads(request.body or "{}")
		messagestatus=cleantext(data.get("status"),20)
		if messagestatus not in ["new","read","done"]:
			return errorresponse("ERROR_request_data_type_error")
		row=query(SETTING["dbname"],f"""SELECT*FROM "contactmessage" WHERE "id"=%s AND "deletetime" IS NULL""",[messageid],SETTING["dbsetting"])
		if not row:
			return errorresponse("ERROR_request_data_not_found")
		query(SETTING["dbname"],f"""UPDATE "contactmessage" SET "status"=%s,"updatetime"=%s WHERE "id"=%s""",[messagestatus,nowtime(),messageid],SETTING["dbsetting"])
		return Response({
			"success": True,
			"data": ""
		},status.HTTP_200_OK)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] "+str(error),"")
		return Response({
			"success": False,
			"data": "ERROR_unknow_error_pls_tell_the_admin"
		},status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(["POST"])
def replycontactmessage(request,messageid):
	try:
		ensurecontactschema()
		userrow,errresp=gettokenuser(request)
		if errresp:
			return errresp
		if 4>int(userrow["permission"]):
			return errorresponse("ERROR_no_permission")
		data=json.loads(request.body or "{}")
		replymessage=cleantext(data.get("message"),5000)
		replysubject=cleantext(data.get("subject"),150)
		if not replymessage:
			return errorresponse("ERROR_request_data_not_found")
		row=query(SETTING["dbname"],f"""SELECT*FROM "contactmessage" WHERE "id"=%s AND "deletetime" IS NULL""",[messageid],SETTING["dbsetting"])
		if not row:
			return errorresponse("ERROR_request_data_not_found")
		message=row[0]
		if not replysubject:
			if message["subject"]:
				replysubject="Re: "+str(message["subject"])
			else:
				replysubject="Re: PokerTrace 聯絡我們"
		body=f"""您好 {message["name"]}：

感謝你聯絡 PokerTrace，以下是我們的回覆：

{replymessage}

---
你原本送出的訊息：
主旨：{message["subject"] or "未填主旨"}
內容：
{message["message"]}

PokerTrace
"""
		asyncsendmail(replysubject,body,None,[message["email"]],fail_silently=False)
		query(SETTING["dbname"],f"""
			UPDATE "contactmessage"
			SET "status"=%s,"replysubject"=%s,"replymessage"=%s,"replytime"=%s,"replyuserid"=%s,"updatetime"=%s
			WHERE "id"=%s
		""",["done",replysubject,replymessage,nowtime(),userrow["id"],nowtime(),messageid],SETTING["dbsetting"])
		return Response({
			"success": True,
			"data": ""
		},status.HTTP_200_OK)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] "+str(error),"")
		return Response({
			"success": False,
			"data": "ERROR_unknow_error_pls_tell_the_admin"
		},status.HTTP_500_INTERNAL_SERVER_ERROR)
