import json
import threading

from django.core.mail import send_mail
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from function.sql import *
from function.thing import *
from function.function import *
from .initialize import *
from .authhelper import gettokenuser as commonauthuser


CONTACTNOTIFYEMAIL="chris960527ho@gmail.com"
# 公開端點頻率限制: 同一 IP (取不到 IP 時改用 email) 在 CONTACTRATELIMITMINUTE 分鐘內最多 CONTACTRATELIMITCOUNT 筆
CONTACTRATELIMITMINUTE=10
CONTACTRATELIMITCOUNT=3


def asyncsendmail(*args,**kwargs):
	threading.Thread(target=send_mail,args=args,kwargs=kwargs).start()


def gettokenuser(request):
	"""Bearer token → 使用者列。**委派給共用的 authhelper.gettokenuser**。

	原本這裡是一份手寫的副本，檢查了 token、也檢查了使用者的 deletetime，
	但**沒有檢查封禁狀態** —— 共用版本有，而且註明了理由：
	「封禁時已撤銷 token，這裡再撤一次，避免封禁後才發出的 token 或漏撤的舊 token 仍可用」。

	結果是被封禁（type='ban'）或仍在限時封鎖期（type='block'）的使用者，
	只要手上的 token 還沒被撤，就能照常呼叫本模組的每一個端點。
	2026-07-30 稽核發現，改成委派。

	共用版本的 token 解析也比較嚴謹：`getbearertoken()` 會檢查 scheme 是不是
	bearer（不分大小寫）、處理多餘空白；原本的 `header.split("Bearer ")[1]`
	連 "Basic xyzBearer abc" 這種都切得出東西。
	"""
	return commonauthuser(request)

def cleantext(value,limit):
	value=str(value or "").strip()
	if limit and limit<len(value):
		value=value[:limit]
	return value


def ensurecontactschema():
	query(SETTING["dbname"],"""
		CREATE TABLE IF NOT EXISTS public.contactmessage(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			userid bigint,
			name varchar(100) NOT NULL,
			email varchar(150) NOT NULL,
			subject varchar(150) NOT NULL DEFAULT '',
			message text NOT NULL,
			status varchar(20) NOT NULL DEFAULT 'new',
			replysubject varchar(150) NOT NULL DEFAULT '',
			replymessage text NOT NULL DEFAULT '',
			replytime timestamp with time zone,
			replyuserid bigint,
			ip varchar(80) NOT NULL DEFAULT '',
			useragent text NOT NULL DEFAULT '',
			createtime timestamp with time zone NOT NULL DEFAULT now(),
			updatetime timestamp with time zone NOT NULL DEFAULT now(),
			deletetime timestamp with time zone
		)
	""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replysubject varchar(150) NOT NULL DEFAULT ''""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replymessage text NOT NULL DEFAULT ''""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replytime timestamp with time zone""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replyuserid bigint""",[],SETTING["dbsetting"])


@api_view(["POST"])
def newcontactmessage(request):
	try:
		ensurecontactschema()
		data=json.loads(request.body or "{}")
		name=cleantext(data.get("name"),100)
		email=cleantext(data.get("email"),150)
		subject=cleantext(data.get("subject"),150)
		message=cleantext(data.get("message"),3000)
		# 這是免登入的公開端點，token 只用來「標記是誰送的」，不決定能不能送，
		# 所以驗證失敗不擋，只是留白 userid。
		# 原本這裡自己查 token 表：沒驗 Bearer scheme，也沒讀 user 列，
		# 於是已軟刪或被封禁帳號的舊 token 仍會被寫成留言的 userid。改走共用驗證。
		userid=None
		if request.headers.get("Authorization"):
			tokenuserrow,autherror=commonauthuser(request)
			if not autherror:
				userid=tokenuserrow["id"]
		if not name or not email or not message:
			return errorresponse("ERROR_request_data_not_found")
		if "@" not in email:
			return errorresponse("ERROR_request_data_type_error")
		# 優先取 nginx 設的 X-Real-IP，取不到才 fallback REMOTE_ADDR；本部署兩者都是真實 client IP
		# (uvicorn proxy_headers 預設開啟，已從 X-Forwarded-For 還原真實來源；nginx 兩條 location 也都有
		#  proxy_set_header X-Real-IP $remote_addr，會覆寫用戶端偽造的標頭值)
		# (此 ip 同時用於頻率限制計數與寫入 contactmessage.ip 欄)
		ip=request.META.get("HTTP_X_REAL_IP") or request.META.get("REMOTE_ADDR","")
		useragent=request.META.get("HTTP_USER_AGENT","")
		# 免登入公開端點, 用 contactmessage 既有 ip 欄位做簡易頻率限制 (不含軟刪過濾, 刪除訊息不會重置額度);
		# 取不到 IP 時退而以 email 計數
		if ip:
			ratelimitrow=query(SETTING["dbname"],"""SELECT COUNT(*) AS total FROM "contactmessage" WHERE "ip"=%s AND "createtime">=NOW()-make_interval(mins=>%s)""",[ip,CONTACTRATELIMITMINUTE],SETTING["dbsetting"])
		else:
			ratelimitrow=query(SETTING["dbname"],"""SELECT COUNT(*) AS total FROM "contactmessage" WHERE "email"=%s AND "createtime">=NOW()-make_interval(mins=>%s)""",[email,CONTACTRATELIMITMINUTE],SETTING["dbsetting"])
		if ratelimitrow and CONTACTRATELIMITCOUNT<=int(ratelimitrow[0]["total"]):
			return Response({
				"success": False,
				"data": "ERROR_too_many_requests"
			},status.HTTP_429_TOO_MANY_REQUESTS)
		query(SETTING["dbname"],f"""
			INSERT INTO "contactmessage"("userid","name","email","subject","message","ip","useragent","createtime","updatetime")
			VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s)
		""",[userid,name,email,subject,message,ip,useragent,nowtime(),nowtime()],SETTING["dbsetting"])
		# TASK-070：中英並列，不做語系分流（收件人語系偏好沒有存，分流要先加欄位）。
		# 這一封是**寄給站方**的內部通知，不是寄給填表的人。
		#
		# 這裡刻意**不把整封信複製成中英兩段**：訊息內容上限 5000 字，
		# 複製一次等於信件長度加倍。固定文案中英並列、變動內容只出現一次。
		notifysubject="PokerTrace 新聯絡訊息 / New contact message"
		if subject:
			notifysubject=notifysubject+"："+subject
		notifybody=f"""PokerTrace 收到新的聯絡訊息：
PokerTrace received a new contact message:

姓名 Name：{name}
Email：{email}
主旨 Subject：{subject or "未填主旨 (no subject)"}
時間 Time：{nowtime()}

內容 Message：
{message}

請到聯絡訊息後台查看與回覆。
Please review and reply in the contact message console.
"""
		asyncsendmail(notifysubject,notifybody,None,[CONTACTNOTIFYEMAIL],fail_silently=True)
		return Response({
			"success": True,
			"data": ""
		},status.HTTP_200_OK)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] "+str(error),"")
		return Response({
			"success": False,
			"data": "ERROR_unknow_error_pls_tell_the_admin"
		},status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(["GET"])
def getcontactmessages(request):
	try:
		ensurecontactschema()
		userrow,errresp=gettokenuser(request)
		if errresp:
			return errresp
		if 4>int(userrow["permission"]):
			return errorresponse("ERROR_no_permission")
		page=int(request.GET.get("page") or 1)
		limit=int(request.GET.get("limit") or 20)
		statusfilter=cleantext(request.GET.get("status"),20)
		if page<1:
			page=1
		if limit<1:
			limit=20
		if 100<limit:
			limit=100
		offset=(page-1)*limit
		where=["cm.\"deletetime\" IS NULL"]
		params=[]
		if statusfilter:
			where.append("cm.\"status\"=%s")
			params.append(statusfilter)
		wheresql=" AND ".join(where)
		countrow=query(SETTING["dbname"],f"""
			SELECT COUNT(*) AS total
			FROM "contactmessage" cm
			WHERE {wheresql}
		""",params,SETTING["dbsetting"])
		row=query(SETTING["dbname"],f"""
			SELECT
				cm.*,
				u."name" AS username,
				u."playerid" AS userplayerid
			FROM "contactmessage" cm
			LEFT JOIN "user" u ON u."id"=cm."userid"
			WHERE {wheresql}
			ORDER BY cm."createtime" DESC,cm."id" DESC
			LIMIT %s OFFSET %s
		""",params+[limit,offset],SETTING["dbsetting"])
		total=0
		if countrow:
			total=countrow[0]["total"]
		totalpages=(total+limit-1)//limit
		if totalpages<=0:
			totalpages=1
		if totalpages<page:
			page=totalpages
		return Response({
			"success": True,
			"data": {
				"messages": row or [],
				"pagination": {
					"page": page,
					"limit": limit,
					"total": total,
					"totalpages": totalpages,
					"hasprev": 1<page,
					"hasnext": page<totalpages
				}
			}
		},status.HTTP_200_OK)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] "+str(error),"")
		return Response({
			"success": False,
			"data": "ERROR_unknow_error_pls_tell_the_admin"
		},status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(["PUT"])
def editcontactmessage(request,messageid):
	try:
		ensurecontactschema()
		userrow,errresp=gettokenuser(request)
		if errresp:
			return errresp
		if 4>int(userrow["permission"]):
			return errorresponse("ERROR_no_permission")
		data=json.loads(request.body or "{}")
		messagestatus=cleantext(data.get("status"),20)
		if messagestatus not in ["new","read","done"]:
			return errorresponse("ERROR_request_data_type_error")
		row=query(SETTING["dbname"],f"""SELECT*FROM "contactmessage" WHERE "id"=%s AND "deletetime" IS NULL""",[messageid],SETTING["dbsetting"])
		if not row:
			return errorresponse("ERROR_request_data_not_found")
		query(SETTING["dbname"],f"""UPDATE "contactmessage" SET "status"=%s,"updatetime"=%s WHERE "id"=%s""",[messagestatus,nowtime(),messageid],SETTING["dbsetting"])
		return Response({
			"success": True,
			"data": ""
		},status.HTTP_200_OK)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] "+str(error),"")
		return Response({
			"success": False,
			"data": "ERROR_unknow_error_pls_tell_the_admin"
		},status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(["POST"])
def replycontactmessage(request,messageid):
	try:
		ensurecontactschema()
		userrow,errresp=gettokenuser(request)
		if errresp:
			return errresp
		if 4>int(userrow["permission"]):
			return errorresponse("ERROR_no_permission")
		data=json.loads(request.body or "{}")
		replymessage=cleantext(data.get("message"),5000)
		replysubject=cleantext(data.get("subject"),150)
		if not replymessage:
			return errorresponse("ERROR_request_data_not_found")
		row=query(SETTING["dbname"],f"""SELECT*FROM "contactmessage" WHERE "id"=%s AND "deletetime" IS NULL""",[messageid],SETTING["dbsetting"])
		if not row:
			return errorresponse("ERROR_request_data_not_found")
		message=row[0]
		if not replysubject:
			if message["subject"]:
				replysubject="Re: "+str(message["subject"])
			else:
				replysubject="Re: PokerTrace 聯絡我們 / Contact us"
		# TASK-070：中英並列。同上，變動內容（回覆內文、原始訊息）只出現一次，
		# 只有固定文案與欄位標籤中英並列 —— 回覆內文上限 5000 字，複製會讓信長度加倍。
		body=f"""您好 {message["name"]}：
Hi {message["name"]},

感謝你聯絡 PokerTrace，以下是我們的回覆：
Thank you for contacting PokerTrace. Here is our reply:

{replymessage}

---
你原本送出的訊息 / Your original message:
主旨 Subject：{message["subject"] or "未填主旨 (no subject)"}
內容 Message：
{message["message"]}

PokerTrace
"""
		asyncsendmail(replysubject,body,None,[message["email"]],fail_silently=False)
		query(SETTING["dbname"],f"""
			UPDATE "contactmessage"
			SET "status"=%s,"replysubject"=%s,"replymessage"=%s,"replytime"=%s,"replyuserid"=%s,"updatetime"=%s
			WHERE "id"=%s
		""",["done",replysubject,replymessage,nowtime(),userrow["id"],nowtime(),messageid],SETTING["dbsetting"])
		return Response({
			"success": True,
			"data": ""
		},status.HTTP_200_OK)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] "+str(error),"")
		return Response({
			"success": False,
			"data": "ERROR_unknow_error_pls_tell_the_admin"
		},status.HTTP_500_INTERNAL_SERVER_ERROR)
