import json
import random
import itertools
import threading
import time
import eval7

from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from function.validation import *
from function.sql import *
from function.thing import *
from function.function import *
from .initialize import *


def boolval(value):
	if value==True or value==1 or value=="1" or value=="true" or value=="True":
		return True
	return False


def ensurehandcolumns():
	query(SETTING["dbname"],"""ALTER TABLE public."table" ADD COLUMN IF NOT EXISTS no integer""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""
		DO $$
		BEGIN
			IF EXISTS(
				SELECT 1 FROM information_schema.columns
				WHERE table_schema='public' AND table_name='table' AND column_name='name'
			) THEN
				EXECUTE 'UPDATE public."table" SET no=CASE WHEN "name" ~ ''^[0-9]+$'' THEN "name"::integer ELSE id::integer END WHERE no IS NULL';
			ELSE
				UPDATE public."table" SET no=id::integer WHERE no IS NULL;
			END IF;
		END $$;
	""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS levelid bigint""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS handtime timestamp with time zone""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS actionsjson text""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS note text""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS recordtype character varying(40) NOT NULL DEFAULT 'hand'""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS exceptiontype character varying(80) NOT NULL DEFAULT ''""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS familydatajson text""",[],SETTING["dbsetting"])


def ensuretimebanktables():
	query(SETTING["dbname"],"""
		CREATE TABLE IF NOT EXISTS public.sessiontimebank(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			sessionid bigint NOT NULL,
			tableid bigint NOT NULL UNIQUE,
			state jsonb NOT NULL DEFAULT '{}'::jsonb,
			createtime timestamp with time zone NOT NULL DEFAULT now(),
			updatetime timestamp with time zone NOT NULL DEFAULT now(),
			deletetime timestamp with time zone
		)
	""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS adjustmentsjson text""",[],SETTING["dbsetting"])


def intval(value,defaultvalue=0):
	try:
		return int(value)
	except Exception as error:
		return defaultvalue


def jsonval(value,defaultvalue):
	if value is None:
		return defaultvalue
	if isinstance(value,dict) or isinstance(value,list):
		return value
	try:
		return json.loads(value)
	except Exception as error:
		return defaultvalue


def handtime(value):
	if not value:
		return None
	return str(value).replace("+00:00","").replace("T"," ")


def getrequestuser(request):
	header=request.headers.get("Authorization")
	token=None
	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return (None,errorresponse("ERROR_token_not_found"))
	if not token:
		return (None,errorresponse("ERROR_token_not_found"))
	tokenrow=query(SETTING["dbname"],"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return (None,errorresponse("ERROR_token_error"))
	userrow=query(SETTING["dbname"],"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow[0]["userid"]],SETTING["dbsetting"])
	if not userrow:
		return (None,errorresponse("ERROR_user_not_found"))
	return (userrow[0],None)


def gettableandsession(tableid):
	tablerow=query(SETTING["dbname"],"""SELECT*FROM "table" WHERE "id"=%s AND "deletetime" IS NULL""",[tableid],SETTING["dbsetting"])
	if not tablerow:
		return (None,None)
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[tablerow[0]["sessionid"]],SETTING["dbsetting"])
	if not sessionrow:
		return (tablerow[0],None)
	return (tablerow[0],sessionrow[0])


def sessionaccess(sessionrow,userrow):
	access={
		"isown": False,
		"isstaff": False,
		"isadmin": False,
		"isplayer": False,
		"accessrole": "",
		"canrecord": False,
		"canunifiedrecord": False,
		"cantimer": False
	}
	if not sessionrow or not userrow:
		return access
	if intval(userrow.get("permission"))>=4:
		access["isadmin"]=True
		access["accessrole"]="admin"
	if sessionrow["userid"]==userrow["id"]:
		access["isown"]=True
		access["accessrole"]="owner"
	staffrow=query(SETTING["dbname"],"""SELECT*FROM "sessionstaff" WHERE "sessionid"=%s AND "staffuserid"=%s AND "status"='active' AND "deletetime" IS NULL""",[sessionrow["id"],userrow["id"]],SETTING["dbsetting"])
	if not staffrow:
		staffrow=query(SETTING["dbname"],"""SELECT*FROM "userstaff" WHERE "userid"=%s AND "staffuserid"=%s AND "status"='active' AND "deletetime" IS NULL""",[sessionrow["userid"],userrow["id"]],SETTING["dbsetting"])
	if staffrow:
		access["isstaff"]=True
		access["accessrole"]=staffrow[0]["role"]
	playerrow=query(SETTING["dbname"],"""SELECT*FROM "sessionplayer" WHERE "sessionid"=%s AND "userid"=%s AND "status"='confirmed' AND "deletetime" IS NULL""",[sessionrow["id"],userrow["id"]],SETTING["dbsetting"])
	if playerrow:
		access["isplayer"]=True
	if access["isown"] or access["isadmin"]:
		access["canrecord"]=True
		access["canunifiedrecord"]=True
	if boolval(sessionrow.get("unifiedhandrecord")):
		if access["accessrole"]=="dealer" or access["accessrole"]=="floor" or access["accessrole"]=="assistant":
			access["canrecord"]=True
			access["canunifiedrecord"]=True
	else:
		if access["isplayer"] or access["isown"] or access["isadmin"]:
			access["canrecord"]=True
	if access["isown"] or access["isadmin"] or access["accessrole"]=="floor" or access["accessrole"]=="assistant":
		access["cantimer"]=True
	return access


def sessionregistered(sessionid,userid):
	row=query(SETTING["dbname"],"""SELECT*FROM "sessionplayer" WHERE "sessionid"=%s AND "userid"=%s AND "deletetime" IS NULL""",[sessionid,userid],SETTING["dbsetting"])
	if row:
		return True
	return False


def canreadsessionhands(sessionrow,userrow,access):
	if access["canrecord"] or access["isplayer"] or access["isstaff"] or access["isown"] or access["isadmin"]:
		return True
	if sessionregistered(sessionrow["id"],userrow["id"]):
		return True
	if boolval(sessionrow.get("owned")) and boolval(sessionrow.get("linkuser")) and not boolval(sessionrow.get("private")):
		return True
	return False


def ensurebroadcastcolumns():
	# 現場轉播設定欄位(冪等): 開放開關 / 延遲分鐘 / 顯示底牌 / H4H 手動推進
	query(SETTING["dbname"],"""ALTER TABLE public."session" ADD COLUMN IF NOT EXISTS broadcastopen boolean NOT NULL DEFAULT false""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public."session" ADD COLUMN IF NOT EXISTS broadcastdelay integer NOT NULL DEFAULT 0""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public."session" ADD COLUMN IF NOT EXISTS broadcastshowcard boolean NOT NULL DEFAULT true""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public."session" ADD COLUMN IF NOT EXISTS broadcasth4h boolean NOT NULL DEFAULT false""",[],SETTING["dbsetting"])
	# H4H 已放行手數(由最舊往最新逐手放行), 開啟 H4H 當下會初始化為當時總手數
	query(SETTING["dbname"],"""ALTER TABLE public."session" ADD COLUMN IF NOT EXISTS broadcastreleasedcount integer NOT NULL DEFAULT 0""",[],SETTING["dbsetting"])


def cancontrolbroadcast(sessionrow,userrow):
	# 裁判/主辦才能操作 H4H 逐手推進
	access=sessionaccess(sessionrow,userrow)
	if access["isown"] or access["isadmin"] or access["cantimer"] or access["canrecord"]:
		return True
	return False


def sessionhandcount(sessionid):
	rows=query(SETTING["dbname"],"""SELECT count(*) AS c FROM "hand" h JOIN "table" t ON t."id"=h."tableid" WHERE t."sessionid"=%s AND h."deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
	if rows:
		return intval(rows[0]["c"])
	return 0


def sessionispublicbroadcast(sessionrow):
	# 場外轉播的資格: 開放轉播 + 統一手牌紀錄 + 公開場次(主辦制 + 開放連結 + 非私人)
	# 只有符合的場次才允許匿名/連結觀眾唯讀觀看, 私人場或未開放一律不開放
	if not sessionrow:
		return False
	if not boolval(sessionrow.get("broadcastopen")):
		return False
	if not boolval(sessionrow.get("unifiedhandrecord")):
		return False
	if not boolval(sessionrow.get("owned")):
		return False
	if not boolval(sessionrow.get("linkuser")):
		return False
	if boolval(sessionrow.get("private")):
		return False
	return True


def broadcastsessionchips(sessionid):
	# 轉播頁下注計分牌配色用: 回傳該場次的計分牌面額(含顏色), 無設定則給預設
	rows=query(SETTING["dbname"],"""SELECT "shape","value","color","sortorder" FROM "sessionchip" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC,"value" ASC,"id" ASC""",[sessionid],SETTING["dbsetting"])
	if rows:
		return [dict(rows[i]) for i in range(len(rows))]
	return [
		{"shape": "circle","value": 100,"color": "#ffffff","sortorder": 1},
		{"shape": "circle","value": 500,"color": "#ef4444","sortorder": 2},
		{"shape": "circle","value": 1000,"color": "#f59e0b","sortorder": 3},
		{"shape": "circle","value": 5000,"color": "#22c55e","sortorder": 4},
		{"shape": "circle","value": 10000,"color": "#3b82f6","sortorder": 5}
	]


def maskholecards(item):
	# 隱藏底牌: 清掉本手英雄底牌與各座位底牌, 前端會顯示為未知牌
	item["handcard"]={}
	seats=item.get("seatingdata") or []
	for i in range(len(seats)):
		seats[i]["handcard"]=None
	return item


def handbroadcast(sessionid,eventname,handid=None,state=None):
	try:
		layer=get_channel_layer()
		if layer:
			async_to_sync(layer.group_send)("hand_"+str(sessionid),{
				"type": "hand.update",
				"event": eventname,
				"handid": handid,
				"state": state or {}
			})
	except Exception as error:
		printcolorhaveline("fail","[ERROR] handbroadcast "+str(error),"")


def serializeseating(row):
	data=[]
	for i in range(len(row or [])):
		item=dict(row[i])
		item["handcard"]=jsonval(item.get("handcard"),None)
		data.append(item)
	return data


def serializebitting(row):
	data=[]
	for i in range(len(row or [])):
		data.append(dict(row[i]))
	return data


def defaulttimebankconfig(sessionrow):
	defaultseconds=15
	soundon=True
	try:
		from .timer import ensuretimertables,readconfig
		ensuretimertables()
		config=readconfig(sessionrow,0,0,True) or {}
		defaultseconds=intval(config.get("defaultTimebankSeconds"),15)
		soundon=boolval(config.get("timebankSoundOn"))
	except Exception as error:
		defaultseconds=15
		soundon=True
	return {
		"defaultTimebankSeconds": defaultseconds,
		"timebankSoundOn": soundon
	}


def normalizetimebankstate(stateval,defaultseconds=15):
	state={}
	if isinstance(stateval,str):
		try:
			state=json.loads(stateval)
		except Exception as error:
			state={}
	elif isinstance(stateval,dict):
		state=dict(stateval)
	state["enabled"]=boolval(state.get("enabled"))
	state["seatno"]=intval(state.get("seatno"),0)
	state["durationseconds"]=max(1,intval(state.get("durationseconds"),defaultseconds))
	state["remainingseconds"]=intval(state.get("remainingseconds"),state["durationseconds"])
	if state["remainingseconds"]<0:
		state["remainingseconds"]=0
	state["endtime"]=state.get("endtime") or ""
	state["running"]=boolval(state.get("running"))
	state["expired"]=boolval(state.get("expired"))
	state["startedby"]=intval(state.get("startedby"),0)
	state["starttime"]=state.get("starttime") or ""
	state["updatedtime"]=state.get("updatedtime") or nowtime()
	return state


def loadtimebankstate(tablerow,sessionrow):
	ensuretimebanktables()
	defaultconfig=defaulttimebankconfig(sessionrow)
	defaultseconds=intval(defaultconfig.get("defaultTimebankSeconds"),15)
	row=query(SETTING["dbname"],"""SELECT*FROM "sessiontimebank" WHERE "tableid"=%s AND "deletetime" IS NULL""",[tablerow["id"]],SETTING["dbsetting"])
	if row:
		state=normalizetimebankstate(row[0]["state"],defaultseconds)
	else:
		state=normalizetimebankstate({},defaultseconds)
	return {
		"state": state,
		"defaults": defaultconfig
	}


def savetimebankstate(tablerow,sessionrow,stateval):
	ensuretimebanktables()
	defaultconfig=defaulttimebankconfig(sessionrow)
	state=normalizetimebankstate(stateval,intval(defaultconfig.get("defaultTimebankSeconds"),15))
	state["updatedtime"]=nowtime()
	row=query(SETTING["dbname"],"""SELECT*FROM "sessiontimebank" WHERE "tableid"=%s""",[tablerow["id"]],SETTING["dbsetting"])
	if row:
		queryupdate(SETTING["dbname"],"sessiontimebank",{
			"sessionid": sessionrow["id"],
			"state": json.dumps(state),
			"updatetime": nowtime(),
			"deletetime": None
		},{"tableid": tablerow["id"]},SETTING["dbsetting"])
	else:
		queryinsert(SETTING["dbname"],"sessiontimebank",{
			"sessionid": sessionrow["id"],
			"tableid": tablerow["id"],
			"state": json.dumps(state)
		},SETTING["dbsetting"])
	return {
		"state": state,
		"defaults": defaultconfig
	}


def grouprowsbyhandid(row):
	data={}
	for i in range(len(row or [])):
		handid=row[i]["handid"]
		if handid not in data:
			data[handid]=[]
		data[handid].append(row[i])
	return data


def loadhanddetailmaps(rows):
	handids=[]
	for i in range(len(rows or [])):
		handids.append(rows[i]["id"])
	if not handids:
		return {},{}
	placeholders=",".join(["%s"]*len(handids))
	seatingrow=query(SETTING["dbname"],f"""SELECT*FROM "handseating" WHERE "handid" IN ({placeholders}) AND "deletetime" IS NULL ORDER BY "handid" ASC,"seatno" ASC""",handids,SETTING["dbsetting"])
	bittingrow=query(SETTING["dbname"],f"""SELECT*FROM "handbittingdata" WHERE "handid" IN ({placeholders}) AND "deletetime" IS NULL ORDER BY "handid" ASC,"id" ASC""",handids,SETTING["dbsetting"])
	return grouprowsbyhandid(seatingrow),grouprowsbyhandid(bittingrow)


def serializehand(hand,withdetail=True,seatingrow=None,bittingrow=None):
	item=dict(hand)
	item["handcard"]=jsonval(item.get("handcard"),{})
	item["boardcard"]=jsonval(item.get("boardcard"),{})
	item["actionsjson"]=jsonval(item.get("actionsjson"),{})
	item["adjustments"]=jsonval(item.get("adjustmentsjson"),{})
	item["familydata"]=jsonval(item.get("familydatajson"),{})
	item["recordtype"]=item.get("recordtype") or "hand"
	item["exceptiontype"]=item.get("exceptiontype") or ""
	item["createtime"]=handtime(item.get("createtime"))
	item["updatetime"]=handtime(item.get("updatetime"))
	item["handtime"]=handtime(item.get("handtime"))
	if withdetail:
		if seatingrow is None:
			seatingrow=query(SETTING["dbname"],"""SELECT*FROM "handseating" WHERE "handid"=%s AND "deletetime" IS NULL ORDER BY "seatno" ASC""",[hand["id"]],SETTING["dbsetting"])
		if bittingrow is None:
			bittingrow=query(SETTING["dbname"],"""SELECT*FROM "handbittingdata" WHERE "handid"=%s AND "deletetime" IS NULL ORDER BY "id" ASC""",[hand["id"]],SETTING["dbsetting"])
		item["seatingdata"]=serializeseating(seatingrow)
		item["bittingdata"]=serializebitting(bittingrow)
		invest={}
		for i in range(len(item["bittingdata"])):
			seatno=intval(item["bittingdata"][i].get("seatno"))
			if seatno not in invest:
				invest[seatno]=0
			invest[seatno]=invest[seatno]+intval(item["bittingdata"][i].get("chip"))
		hero=None
		for i in range(len(item["seatingdata"])):
			if item["seatingdata"][i]["seatno"]==item.get("selfseating"):
				hero=item["seatingdata"][i]
		item["playername"]=hero["name"] if hero else ""
		item["result"]=0
		if hero:
			if item["recordtype"]!="hand":
				# 校正 / 例外紀錄沒有下注，淨增減就是 endchip-chip（chipchange 在此不是投入額）
				item["result"]=intval(hero.get("endchip"))-intval(hero.get("chip"))
			else:
				oldinvest=intval(hero.get("chipchange"))
				currentinvest=intval(invest.get(hero["seatno"],oldinvest))
				winamount=0
				if boolval(hero.get("winnered")):
					winamount=intval(hero.get("endchip"))-intval(hero.get("chip"))+oldinvest
				item["result"]=winamount-currentinvest
	return item


def buildseatmap(sessionrow,tablerow,latesthand):
	maxseat=intval(sessionrow.get("maxseat"),9)
	seatmap=[None]
	for i in range(maxseat):
		seatmap.append(False)
	if boolval(sessionrow.get("linkuser")):
		row=query(SETTING["dbname"],"""
			SELECT sp."id" AS sessionplayerid,sp."userid",sp."seatno",sp."startchip",u."name"
			FROM "sessionplayer" sp
			JOIN "user" u ON u."id"=sp."userid"
			WHERE sp."sessionid"=%s AND sp."tableid"=%s AND sp."status"='confirmed' AND sp."seatno" IS NOT NULL AND sp."deletetime" IS NULL
			  AND NOT EXISTS(
				  SELECT 1 FROM "sessiontimerplayer" tp
				  WHERE tp."sessionid"=sp."sessionid" AND tp."sessionplayerid"=sp."id" AND tp."status"='eliminated' AND tp."deletetime" IS NULL
			  )
			ORDER BY sp."seatno" ASC
		""",[sessionrow["id"],tablerow["id"]],SETTING["dbsetting"])
		for item in row or []:
			seatno=intval(item["seatno"])
			if 0<seatno and seatno<len(seatmap):
				seatmap[seatno]={
					"chip": item.get("startchip") or sessionrow.get("chip") or 0,
					"unknownchip": intval(item.get("startchip"),0)<0,
					"name": item.get("name") or "",
					"userid": item.get("userid"),
					"sessionplayerid": item.get("sessionplayerid"),
					"banned": False
				}
	else:
		row=query(SETTING["dbname"],"""SELECT*FROM "seating" WHERE "tableid"=%s AND "deletetime" IS NULL ORDER BY "seatno" ASC,"time" ASC,"id" ASC""",[tablerow["id"]],SETTING["dbsetting"])
		for item in row or []:
			seatno=intval(item["seatno"])
			if 0<seatno and seatno<len(seatmap):
				if item["type"]=="leave":
					seatmap[seatno]=False
				else:
					seatmap[seatno]={
						"chip": item.get("chip") or sessionrow.get("chip") or 0,
						"unknownchip": intval(item.get("chip"),0)<0,
						"name": item.get("name") or "",
						"userid": item.get("userid"),
						"sessionplayerid": item.get("sessionplayerid"),
						"banned": False
					}
	if latesthand:
		seatingrow=query(SETTING["dbname"],"""SELECT*FROM "handseating" WHERE "handid"=%s AND "deletetime" IS NULL ORDER BY "seatno" ASC""",[latesthand["id"]],SETTING["dbsetting"])
		latestchips={}
		for item in seatingrow or []:
			chip=item.get("endchip") or item.get("chip") or 0
			if item.get("sessionplayerid"):
				latestchips["sp:"+str(item["sessionplayerid"])]=chip
			elif item.get("userid"):
				latestchips["u:"+str(item["userid"])]=chip
			elif item.get("name"):
				latestchips["n:"+str(item["name"])]=chip
		for seatno in range(1,len(seatmap)):
			item=seatmap[seatno]
			if not item:
				continue
			key=None
			if item.get("sessionplayerid"):
				key="sp:"+str(item["sessionplayerid"])
			elif item.get("userid"):
				key="u:"+str(item["userid"])
			elif item.get("name"):
				key="n:"+str(item["name"])
			if key and key in latestchips:
				item["chip"]=latestchips[key]
				item["unknownchip"]=intval(latestchips[key],0)<0
	return seatmap


def nextdealerseat(latesthand,seatmap,tablerow):
	if not latesthand:
		return intval(tablerow.get("firstdealerplace"),1)
	last=intval(latesthand.get("dealerseat"),1)
	maxseat=len(seatmap)-1
	for i in range(maxseat):
		last=last+1
		if last>maxseat:
			last=1
		if seatmap[last]:
			return last
	return 1


def timerlevel(sessionid):
	state={}
	try:
		from .timer import buildtimerstate
		state=buildtimerstate(sessionid) or {}
	except Exception as error:
		state={}
	index=intval(state.get("currentIndex"),0)
	levels=query(SETTING["dbname"],"""SELECT*FROM "sessiontimerlevel" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC""",[sessionid],SETTING["dbsetting"])
	level=None
	if levels and index<len(levels):
		level=levels[index]
	elif levels:
		level=levels[0]
	return {
		"state": state,
		"level": level
	}


def advancehandcount(sessionrow):
	try:
		from .timer import buildtimerstate,savesplitstate,broadcasttimerupdate,boolval as timerbool,intval as timerint
		state=buildtimerstate(sessionrow["id"])
		if not state:
			return {}
		index=timerint(state.get("currentIndex"),0)
		schedule=state.get("schedule") or []
		if index>=len(schedule):
			return state
		item=schedule[index]
		count=timerint(item.get("handCount"),0)+1
		item["handCount"]=count
		state["schedule"][index]=item
		if item.get("timemode")=="handcount":
			target=timerint(item.get("handTargetCount"),0)
			if 0<target and count>=target and index<len(schedule)-1:
				state["currentIndex"]=index+1
				state["secondsLeft"]=timerint(schedule[index+1].get("dur"),20)*60
				state["running"]=False
		savesplitstate(sessionrow,state)
		state=buildtimerstate(sessionrow["id"])
		broadcasttimerupdate(sessionrow["id"],state)
		return state
	except Exception as error:
		printcolorhaveline("fail","[ERROR] advancehandcount "+str(error),"")
		return {}


@api_view(["GET"])
def gethandcontext(request,tableid):
	ensurehandcolumns()
	ensuretimebanktables()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	tablerow,sessionrow=gettableandsession(tableid)
	if not tablerow:
		return errorresponse("ERROR_table_not_found")
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	access=sessionaccess(sessionrow,userrow)
	if not canreadsessionhands(sessionrow,userrow,access):
		return errorresponse("ERROR_no_permission")
	tables=query(SETTING["dbname"],"""SELECT "id","no","token" FROM "table" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "no" ASC,"id" ASC""",[sessionrow["id"]],SETTING["dbsetting"])
	latestrow=query(SETTING["dbname"],"""SELECT*FROM "hand" WHERE "tableid"=%s AND "deletetime" IS NULL AND "recordtype"!='quickhand' ORDER BY "createtime" DESC,"id" DESC LIMIT 1""",[tableid],SETTING["dbsetting"])
	latesthand=latestrow[0] if latestrow else None
	seatmap=buildseatmap(sessionrow,tablerow,latesthand)
	timerdata=timerlevel(sessionrow["id"])
	timebankdefaults=defaulttimebankconfig(sessionrow)
	chiprow=query(SETTING["dbname"],"""SELECT "shape","value","color","sortorder" FROM "sessionchip" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC,"value" ASC,"id" ASC""",[sessionrow["id"]],SETTING["dbsetting"])
	if not chiprow:
		chiprow=[
			{"shape": "circle","value": 100,"color": "#ffffff","sortorder": 1},
			{"shape": "circle","value": 500,"color": "#ef4444","sortorder": 2},
			{"shape": "circle","value": 1000,"color": "#f59e0b","sortorder": 3},
			{"shape": "circle","value": 5000,"color": "#22c55e","sortorder": 4},
			{"shape": "circle","value": 10000,"color": "#3b82f6","sortorder": 5}
		]
	level=timerdata["level"]
	currentlevel=None
	if level:
		currentlevel=dict(level)
	currentseat=None
	for i in range(1,len(seatmap)):
		if seatmap[i] and seatmap[i].get("userid")==userrow["id"]:
			currentseat=i
	return Response({
		"success": True,
		"data": {
			"session": dict(sessionrow),
			"table": dict(tablerow),
			"tables": tables or [],
			"maxseat": intval(sessionrow.get("maxseat"),9),
			"antemode": sessionrow.get("antemode") or "bigblindante",
			"unifiedhandrecord": boolval(sessionrow.get("unifiedhandrecord")),
			"access": access,
			"currentuser": dict(userrow),
			"currentseat": currentseat,
			"timerstate": timerdata["state"],
			"timerlevel": currentlevel,
			"timebankdefaults": timebankdefaults,
			"chips": chiprow or [],
			"latesthand": serializehand(latesthand) if latesthand else None,
			"seatmap": seatmap,
			"nextdealer": nextdealerseat(latesthand,seatmap,tablerow)
		}
	},status.HTTP_200_OK)


@api_view(["GET"])
def gettimebank(request,tableid):
	ensurehandcolumns()
	ensuretimebanktables()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	tablerow,sessionrow=gettableandsession(tableid)
	if not tablerow:
		return errorresponse("ERROR_table_not_found")
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	access=sessionaccess(sessionrow,userrow)
	if not canreadsessionhands(sessionrow,userrow,access):
		return errorresponse("ERROR_no_permission")
	data=loadtimebankstate(tablerow,sessionrow)
	return Response({"success": True,"data": data},status.HTTP_200_OK)


@api_view(["PUT"])
def savetimebank(request,tableid):
	ensurehandcolumns()
	ensuretimebanktables()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	tablerow,sessionrow=gettableandsession(tableid)
	if not tablerow:
		return errorresponse("ERROR_table_not_found")
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	access=sessionaccess(sessionrow,userrow)
	if not access["canrecord"]:
		return errorresponse("ERROR_no_permission")
	try:
		data=json.loads(request.body)
	except Exception as error:
		print(str(error))
		return errorresponse("ERROR_request_data_not_found")
	if isinstance(data,dict)==False:
		return errorresponse("ERROR_request_data_not_found")
	stateval=data.get("state") if isinstance(data.get("state"),dict) else data
	saved=savetimebankstate(tablerow,sessionrow,stateval)
	return Response({"success": True,"data": saved},status.HTTP_200_OK)


def latesthandidmap(tableids):
	# 每桌最新一筆紀錄（不分 recordtype），用來判斷哪一筆能刪／能改計分牌；不受列表的篩選條件影響
	result={}
	seen=set()
	for tid in tableids or []:
		if tid is None or tid in seen:
			continue
		seen.add(tid)
		latestrow=query(SETTING["dbname"],"""SELECT "id" FROM "hand" WHERE "tableid"=%s AND "deletetime" IS NULL ORDER BY "createtime" DESC,"id" DESC LIMIT 1""",[tid],SETTING["dbsetting"])
		if latestrow:
			result[tid]=latestrow[0]["id"]
	return result


@api_view(["GET"])
def gethandlist(request,tableid):
	ensurehandcolumns()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	tablerow,sessionrow=gettableandsession(tableid)
	if not tablerow:
		return errorresponse("ERROR_table_not_found")
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	access=sessionaccess(sessionrow,userrow)
	if not canreadsessionhands(sessionrow,userrow,access):
		return errorresponse("ERROR_no_permission")
	params=[sessionrow["id"]]
	where=["h.\"deletetime\" IS NULL","t.\"sessionid\"=%s"]
	targettable=request.GET.get("tableid") or tableid
	if targettable:
		where.append("h.\"tableid\"=%s")
		params.append(targettable)
	seatno=request.GET.get("seatno")
	if seatno:
		where.append("EXISTS(SELECT 1 FROM \"handseating\" hs WHERE hs.\"handid\"=h.\"id\" AND hs.\"seatno\"=%s AND hs.\"deletetime\" IS NULL)")
		params.append(seatno)
	userid=request.GET.get("userid")
	if userid:
		where.append("EXISTS(SELECT 1 FROM \"handseating\" hs WHERE hs.\"handid\"=h.\"id\" AND hs.\"userid\"=%s AND hs.\"deletetime\" IS NULL)")
		params.append(userid)
	playerid=request.GET.get("playerid")
	if playerid:
		where.append("EXISTS(SELECT 1 FROM \"handseating\" hs JOIN \"user\" u ON u.\"id\"=hs.\"userid\" WHERE hs.\"handid\"=h.\"id\" AND u.\"playerid\"=%s AND hs.\"deletetime\" IS NULL)")
		params.append(playerid)
	datefrom=request.GET.get("datefrom")
	if datefrom:
		where.append("h.\"createtime\">=%s")
		params.append(datefrom)
	dateto=request.GET.get("dateto")
	if dateto:
		where.append("h.\"createtime\"<(%s::date + INTERVAL '1 day')")
		params.append(dateto)
	rows=query(SETTING["dbname"],"""
		SELECT h.*,t."no" AS tablename,t."token" AS tabletoken,u."name" AS creatorname
		FROM "hand" h
		JOIN "table" t ON t."id"=h."tableid"
		LEFT JOIN "user" u ON u."id"=h."userid"
		WHERE """+" AND ".join(where)+"""
		ORDER BY h."createtime" DESC,h."id" DESC
	""",params,SETTING["dbsetting"])
	data=[]
	seatingmap,bittingmap=loadhanddetailmaps(rows)
	latestmap=latesthandidmap([rows[i]["tableid"] for i in range(len(rows or []))])
	for i in range(len(rows or [])):
		handid=rows[i]["id"]
		item=serializehand(rows[i],True,seatingmap.get(handid,[]),bittingmap.get(handid,[]))
		canmodify=rows[i]["userid"]==userrow["id"] or access["canunifiedrecord"]
		item["islatest"]=str(latestmap.get(rows[i]["tableid"]))==str(handid)
		# 非最新一筆只能改不影響計分牌的欄位（備註等），故 canedit 仍看權限；但刪除只允許最新一筆，以免後面手牌起始碼量錯亂。
		# 快速手牌（quickhand）為獨立紀錄、不與其他手牌連動，故任何一筆都可刪除。
		isquickhand=rows[i].get("recordtype")=="quickhand"
		item["canedit"]=canmodify
		item["candelete"]=canmodify and (item["islatest"] or isquickhand)
		data.append(item)
	return Response({"success": True,"data": data},status.HTTP_200_OK)


@api_view(["GET"])
def getsessionhandlist(request,sessionid):
	ensurehandcolumns()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	sessionrow=sessionrow[0]
	access=sessionaccess(sessionrow,userrow)
	if not canreadsessionhands(sessionrow,userrow,access):
		return errorresponse("ERROR_no_permission")
	params=[sessionid]
	where=["h.\"deletetime\" IS NULL","t.\"sessionid\"=%s"]
	seatno=request.GET.get("seatno")
	if seatno:
		where.append("EXISTS(SELECT 1 FROM \"handseating\" hs WHERE hs.\"handid\"=h.\"id\" AND hs.\"seatno\"=%s AND hs.\"deletetime\" IS NULL)")
		params.append(seatno)
	rows=query(SETTING["dbname"],"""
		SELECT h.*,t."no" AS tablename,t."token" AS tabletoken,u."name" AS creatorname
		FROM "hand" h
		JOIN "table" t ON t."id"=h."tableid"
		LEFT JOIN "user" u ON u."id"=h."userid"
		WHERE """+" AND ".join(where)+"""
		ORDER BY h."createtime" DESC,h."id" DESC
	""",params,SETTING["dbsetting"])
	data=[]
	seatingmap,bittingmap=loadhanddetailmaps(rows)
	latestmap=latesthandidmap([rows[i]["tableid"] for i in range(len(rows or []))])
	for i in range(len(rows or [])):
		handid=rows[i]["id"]
		item=serializehand(rows[i],True,seatingmap.get(handid,[]),bittingmap.get(handid,[]))
		canmodify=rows[i]["userid"]==userrow["id"] or access["canunifiedrecord"]
		item["islatest"]=str(latestmap.get(rows[i]["tableid"]))==str(handid)
		isquickhand=rows[i].get("recordtype")=="quickhand"
		item["canedit"]=canmodify
		item["candelete"]=canmodify and (item["islatest"] or isquickhand)
		data.append(item)
	return Response({"success": True,"data": data},status.HTTP_200_OK)


@api_view(["GET"])
def getbroadcasthandlist(request,sessionid):
	# 場外現場轉播用: 唯讀, 免登入, 只對「公開的統一手牌紀錄場次」開放
	# 權限與寫入端點無關, 一律不回傳可編輯/刪除旗標
	ensurehandcolumns()
	ensurebroadcastcolumns()
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	sessionrow=sessionrow[0]
	if not sessionispublicbroadcast(sessionrow):
		return errorresponse("ERROR_no_permission")
	showcard=boolval(sessionrow.get("broadcastshowcard"))
	delay=intval(sessionrow.get("broadcastdelay"))
	h4h=boolval(sessionrow.get("broadcasth4h"))
	releasedcount=intval(sessionrow.get("broadcastreleasedcount"))
	if h4h:
		# H4H 手動推進: 只回傳裁判已放行的最舊 N 手, 顯示時再轉成最新在前
		rows=query(SETTING["dbname"],"""
			SELECT h.*,t."no" AS tablename,t."token" AS tabletoken,u."name" AS creatorname
			FROM "hand" h
			JOIN "table" t ON t."id"=h."tableid"
			LEFT JOIN "user" u ON u."id"=h."userid"
			WHERE h."deletetime" IS NULL AND t."sessionid"=%s
			ORDER BY h."createtime" ASC,h."id" ASC
			LIMIT %s
		""",[sessionid,releasedcount],SETTING["dbsetting"])
		rows=list(reversed(rows or []))
	else:
		params=[sessionid]
		where=["h.\"deletetime\" IS NULL","t.\"sessionid\"=%s"]
		if delay>0:
			# 固定延遲: 只回傳建立時間已超過延遲分鐘數的手牌, 場內即時、場外延後
			where.append("h.\"createtime\" <= now() - (%s * interval '1 minute')")
			params.append(delay)
		rows=query(SETTING["dbname"],"""
			SELECT h.*,t."no" AS tablename,t."token" AS tabletoken,u."name" AS creatorname
			FROM "hand" h
			JOIN "table" t ON t."id"=h."tableid"
			LEFT JOIN "user" u ON u."id"=h."userid"
			WHERE """+" AND ".join(where)+"""
			ORDER BY h."createtime" DESC,h."id" DESC
		""",params,SETTING["dbsetting"])
	data=[]
	seatingmap,bittingmap=loadhanddetailmaps(rows)
	for i in range(len(rows or [])):
		handid=rows[i]["id"]
		item=serializehand(rows[i],True,seatingmap.get(handid,[]),bittingmap.get(handid,[]))
		if not showcard:
			item=maskholecards(item)
		data.append(item)
	sessionmeta={
		"id": sessionrow["id"],
		"name": sessionrow.get("name") or "",
		"unifiedhandrecord": boolval(sessionrow.get("unifiedhandrecord")),
		"maxseat": intval(sessionrow.get("maxseat"),9),
		"broadcastdelay": delay,
		"broadcastshowcard": showcard,
		"broadcasth4h": boolval(sessionrow.get("broadcasth4h")),
		"chips": broadcastsessionchips(sessionid)
	}
	return Response({"success": True,"data": data,"session": sessionmeta},status.HTTP_200_OK)


def _broadcastcontrolsession(request,sessionid):
	# 共用: 驗證使用者 + 取場次 + 裁判權限, 回傳 (sessionrow, errorresponse)
	ensurehandcolumns()
	ensurebroadcastcolumns()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return (None,errresp)
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
	if not sessionrow:
		return (None,errorresponse("ERROR_session_not_found"))
	sessionrow=sessionrow[0]
	if not cancontrolbroadcast(sessionrow,userrow):
		return (None,errorresponse("ERROR_no_permission"))
	return (sessionrow,None)


@api_view(["GET"])
def getbroadcastcontrol(request,sessionid):
	# 裁判端 H4H 控制台: 回傳已放行/總手數 + 下一手待放行預覽 + 各手放行狀態
	sessionrow,errresp=_broadcastcontrolsession(request,sessionid)
	if errresp:
		return errresp
	total=sessionhandcount(sessionid)
	released=intval(sessionrow.get("broadcastreleasedcount"))
	if released>total:
		released=total
	rows=query(SETTING["dbname"],"""
		SELECT h."id",h."createtime",h."smallblind",h."bigblind",h."ante",h."bigblindante",h."selfseating",t."no" AS tablename,t."token" AS tabletoken
		FROM "hand" h
		JOIN "table" t ON t."id"=h."tableid"
		WHERE h."deletetime" IS NULL AND t."sessionid"=%s
		ORDER BY h."createtime" ASC,h."id" ASC
	""",[sessionid],SETTING["dbsetting"])
	hands=[]
	for i in range(len(rows or [])):
		item=dict(rows[i])
		item["createtime"]=handtime(item.get("createtime"))
		item["released"]=i<released
		item["order"]=i+1
		hands.append(item)
	nexthand=hands[released] if released<len(hands) else None
	control={
		"total": total,
		"released": released,
		"pending": max(0,total-released),
		"h4h": boolval(sessionrow.get("broadcasth4h")),
		"nexthand": nexthand,
		"hands": hands,
		"name": sessionrow.get("name") or ""
	}
	return Response({"success": True,"data": control},status.HTTP_200_OK)


@api_view(["PUT"])
def broadcastrelease(request,sessionid):
	# 裁判操作: action = advance(推進一手) / all(全部放行) / back(退回一手)
	sessionrow,errresp=_broadcastcontrolsession(request,sessionid)
	if errresp:
		return errresp
	try:
		body=json.loads(request.body or "{}")
	except Exception as error:
		body={}
	action=str(body.get("action") or "advance")
	total=sessionhandcount(sessionid)
	released=intval(sessionrow.get("broadcastreleasedcount"))
	if released>total:
		released=total
	if action=="all":
		released=total
	elif action=="back":
		released=max(0,released-1)
	else:
		released=min(total,released+1)
	queryupdate(SETTING["dbname"],"session",{"broadcastreleasedcount": released,"updatetime": nowtime()},{"id": sessionid},SETTING["dbsetting"])
	# 通知觀眾端重抓(轉播頁收到手牌事件即重新載入)
	handbroadcast(sessionid,"broadcast.released",None,{"released": released,"total": total})
	return Response({"success": True,"data": {"released": released,"total": total,"pending": max(0,total-released)}},status.HTTP_200_OK)


@api_view(["GET"])
def getsessionchips(request,sessionid):
	# 手牌回放上色用: 回傳該場次計分牌面額(含顏色), 需可讀取該場手牌者
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	sessionrow=sessionrow[0]
	access=sessionaccess(sessionrow,userrow)
	if not canreadsessionhands(sessionrow,userrow,access):
		return errorresponse("ERROR_no_permission")
	return Response({"success": True,"data": broadcastsessionchips(sessionid)},status.HTTP_200_OK)


@api_view(["GET"])
def gethand(request,handid):
	ensurehandcolumns()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	row=query(SETTING["dbname"],"""
		SELECT h.*,t."sessionid",t."no" AS tablename,t."token" AS tabletoken,u."name" AS creatorname
		FROM "hand" h
		JOIN "table" t ON t."id"=h."tableid"
		LEFT JOIN "user" u ON u."id"=h."userid"
		WHERE h."id"=%s AND h."deletetime" IS NULL
	""",[handid],SETTING["dbsetting"])
	if not row:
		return errorresponse("ERROR_hand_not_found")
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[row[0]["sessionid"]],SETTING["dbsetting"])
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	access=sessionaccess(sessionrow[0],userrow)
	if not canreadsessionhands(sessionrow[0],userrow,access):
		return errorresponse("ERROR_no_permission")
	item=serializehand(row[0])
	latestrow=query(SETTING["dbname"],"""SELECT "id" FROM "hand" WHERE "tableid"=%s AND "deletetime" IS NULL ORDER BY "createtime" DESC,"id" DESC LIMIT 1""",[row[0]["tableid"]],SETTING["dbsetting"])
	item["islatest"]=bool(latestrow) and str(latestrow[0]["id"])==str(handid)
	return Response({"success": True,"data": item},status.HTTP_200_OK)


def cardlistfrompair(value):
	cards=[]
	if not value:
		return cards
	if value.get("card1"):
		cards.append(value.get("card1"))
	if value.get("card2"):
		cards.append(value.get("card2"))
	return cards


def boardcardsfromdata(value): 
	cards=[] 
	if not value: 
		return cards 
	floplist=value.get("floplist") 
	if floplist is None: 
		floplist=value.get("flop") or [] 
	for i in range(len(floplist)): 
		if floplist[i]: 
			cards.append(floplist[i]) 
	if value.get("turn"): 
		cards.append(value.get("turn")) 
	if value.get("river"): 
		cards.append(value.get("river")) 
	return cards 


@api_view(["POST"])
def solvehandwinner(request):
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	try:
		data=json.loads(request.body)
	except Exception as error:
		return errorresponse("ERROR_request_data_not_found")
	try:
		board=[]
		boardraw=boardcardsfromdata(data.get("boardcard") or {})
		for i in range(len(boardraw)):
			board.append(eval7.Card(boardraw[i]))
		if len(board)<3:
			return Response({"success": True,"data": {"winners": [],"results": [],"message": "BOARD_NOT_ENOUGH"}},status.HTTP_200_OK)
		seats=[]
		selfseat=intval(data.get("selfseating"),0)
		herocards=cardlistfrompair(data.get("handcard") or {})
		if selfseat and len(herocards)==2:
			seats.append({
				"seat": selfseat,
				"cards": herocards
			})
		showdowndata=data.get("showdowndata") or {}
		for key in showdowndata:
			row=showdowndata[key]
			if boolval(row.get("shown")):
				cards=cardlistfrompair(row)
				if len(cards)==2:
					seatno=intval(key,0)
					existed=False
					for i in range(len(seats)):
						if seats[i]["seat"]==seatno:
							seats[i]["cards"]=cards
							existed=True
					if not existed:
						seats.append({
							"seat": seatno,
							"cards": cards
						})
		results=[]
		bestscore=None
		for i in range(len(seats)):
			handcards=[eval7.Card(seats[i]["cards"][0]),eval7.Card(seats[i]["cards"][1])]
			score=eval7.evaluate(handcards+board)
			results.append({
				"seat": seats[i]["seat"],
				"score": score,
				"cards": seats[i]["cards"]
			})
			if bestscore is None or score>bestscore:
				bestscore=score
		winners=[]
		for i in range(len(results)):
			if results[i]["score"]==bestscore:
				winners.append(results[i]["seat"])
		return Response({"success": True,"data": {"winners": winners,"results": results}},status.HTTP_200_OK)
	except Exception as error:
		return errorresponse("ERROR_request_data_type_error")


def equityomahaed(gametype):
	if gametype=="OM" or gametype=="O8" or gametype=="O5":
		return True
	return False


def equityhiloed(gametype):
	if gametype=="O8":
		return True
	return False


def equityshortdecked(gametype):
	if gametype=="SD":
		return True
	return False


def equityholecount(gametype):
	if gametype=="O5":
		return 5
	if equityomahaed(gametype):
		return 4
	return 2


def equitycardtext(carditem):
	return str(carditem)


def equityrankchar(carditem):
	return equitycardtext(carditem)[0].upper()


def equityallowedranklist(gametype):
	if equityshortdecked(gametype):
		return ["A","K","Q","J","T","9","8","7","6"]
	return ["A","K","Q","J","T","9","8","7","6","5","4","3","2"]


def equityrankvalue(rankchar):
	rankmap={
		"A": 14,
		"K": 13,
		"Q": 12,
		"J": 11,
		"T": 10,
		"9": 9,
		"8": 8,
		"7": 7,
		"6": 6,
		"5": 5,
		"4": 4,
		"3": 3,
		"2": 2
	}
	return rankmap.get(rankchar.upper(),0)


def shortdeckstraighthigh(rankvaluelist):
	uniquelist=[]
	for i in range(len(rankvaluelist)):
		if rankvaluelist[i] not in uniquelist:
			uniquelist.append(rankvaluelist[i])
	uniquelist=sorted(uniquelist,reverse=True)
	if uniquelist==[14,9,8,7,6]:
		return 9
	if len(uniquelist)!=5:
		return None
	for i in range(4):
		if uniquelist[i]-1!=uniquelist[i+1]:
			return None
	return uniquelist[0]


def shortdeckscore5(cardlist5): 
	rankcount={}
	suitcount={}
	rankvaluelist=[]
	for i in range(len(cardlist5)):
		rankchar=equityrankchar(cardlist5[i])
		suitchar=equitycardtext(cardlist5[i])[-1].lower()
		rankvalue=equityrankvalue(rankchar)
		rankvaluelist.append(rankvalue)
		if rankvalue not in rankcount:
			rankcount[rankvalue]=0
		rankcount[rankvalue]=rankcount[rankvalue]+1
		if suitchar not in suitcount:
			suitcount[suitchar]=0
		suitcount[suitchar]=suitcount[suitchar]+1
	flushsed=False
	for suitchar in suitcount:
		if suitcount[suitchar]==5:
			flushsed=True
	straighthigh=shortdeckstraighthigh(rankvaluelist)
	if flushsed and straighthigh is not None:
		return (8,straighthigh)
	fourrank=0
	threerank=0
	pairlist=[]
	singlelist=[]
	for rankvalue in sorted(rankcount.keys(),reverse=True):
		if rankcount[rankvalue]==4:
			fourrank=rankvalue
		elif rankcount[rankvalue]==3:
			threerank=rankvalue
		elif rankcount[rankvalue]==2:
			pairlist.append(rankvalue)
		else:
			singlelist.append(rankvalue)
	if fourrank>0:
		return (7,fourrank,singlelist[0])
	if flushsed:
		return (6,)+tuple(sorted(rankvaluelist,reverse=True))
	if threerank>0 and len(pairlist)>0:
		return (5,threerank,pairlist[0])
	if threerank>0:
		kickerlist=sorted(singlelist,reverse=True)
		return (3,threerank)+tuple(kickerlist)
	if straighthigh is not None:
		return (4,straighthigh)
	if len(pairlist)>=2:
		pairlist=sorted(pairlist,reverse=True)
		return (2,pairlist[0],pairlist[1],singlelist[0])
	if len(pairlist)==1: 
		kickerlist=sorted(singlelist,reverse=True) 
		return (1,pairlist[0])+tuple(kickerlist) 
	return (0,)+tuple(sorted(rankvaluelist,reverse=True)) 


def equityvisiblescore(cardlist):
	rankcount={}
	for i in range(len(cardlist)):
		rankvalue=equityrankvalue(equityrankchar(cardlist[i]))
		if rankvalue not in rankcount:
			rankcount[rankvalue]=0
		rankcount[rankvalue]=rankcount[rankvalue]+1
	pairlist=[]
	threerank=0
	fourrank=0
	singlelist=[]
	for rankvalue in sorted(rankcount.keys(),reverse=True):
		if rankcount[rankvalue]==4:
			fourrank=rankvalue
		elif rankcount[rankvalue]==3:
			threerank=rankvalue
		elif rankcount[rankvalue]==2:
			pairlist.append(rankvalue)
		else:
			singlelist.append(rankvalue)
	if fourrank>0:
		return (7,fourrank)+tuple(singlelist)
	if threerank>0 and len(pairlist)>0:
		return (5,threerank,pairlist[0])
	if threerank>0:
		return (4,threerank)+tuple(singlelist)
	if len(pairlist)>=2:
		pairlist=sorted(pairlist,reverse=True)
		return (2,pairlist[0],pairlist[1])+tuple(singlelist)
	if len(pairlist)==1:
		return (1,pairlist[0])+tuple(singlelist)
	return (0,)+tuple(sorted(singlelist,reverse=True))


def equitypartialsolebest(handlist,board):
	scores=[]
	for i in range(len(handlist)):
		scores.append(equityvisiblescore(handlist[i]+board))
	best=max(scores)
	if scores.count(best)==1:
		return scores.index(best)
	return -1


def equityhighbestdata(handcardlist,board5,gametype):
	bestscore=None
	bestcardlist=[]
	if len(board5)<3:
		return {
			"score": None,
			"bestcardlist": bestcardlist
		}
	if equityshortdecked(gametype):
		allcardlist=handcardlist+board5
		for combo in itertools.combinations(allcardlist,5):
			bestcombo=list(combo)
			score=shortdeckscore5(bestcombo)
			if bestscore is None or score>bestscore:
				bestscore=score
				bestcardlist=[]
				for carditem in bestcombo:
					bestcardlist.append(equitycardtext(carditem))
		return {
			"score": bestscore,
			"bestcardlist": bestcardlist
		}
	if equityomahaed(gametype):
		for hc in itertools.combinations(handcardlist,2):
			for bc in itertools.combinations(board5,3):
				bestcombo=list(hc)+list(bc)
				score=eval7.evaluate(bestcombo)
				if bestscore is None or score>bestscore:
					bestscore=score
					bestcardlist=[]
					for carditem in bestcombo:
						bestcardlist.append(equitycardtext(carditem))
		return {
			"score": bestscore,
			"bestcardlist": bestcardlist
		}
	allcardlist=handcardlist+board5
	for combo in itertools.combinations(allcardlist,5):
		bestcombo=list(combo)
		score=eval7.evaluate(bestcombo)
		if bestscore is None or score>bestscore:
			bestscore=score
			bestcardlist=[]
			for carditem in bestcombo:
				bestcardlist.append(equitycardtext(carditem))
	return {
		"score": bestscore,
		"bestcardlist": bestcardlist
	}


def equitylowscore(handcardlist,board5,gametype):
	if equityhiloed(gametype)==False:
		return None
	bestlow=None
	for hc in itertools.combinations(handcardlist,2):
		for bc in itertools.combinations(board5,3):
			combo=list(hc)+list(bc)
			lowvaluelist=[]
			valided=True
			for i in range(len(combo)):
				rankchar=equityrankchar(combo[i])
				rankvalue=equityrankvalue(rankchar)
				if rankvalue==14:
					rankvalue=1
				if rankvalue>8:
					valided=False
					break
				if rankvalue in lowvaluelist:
					valided=False
					break
				lowvaluelist.append(rankvalue)
			if valided==False:
				continue
			lowtuple=tuple(sorted(lowvaluelist,reverse=True))
			if bestlow is None or lowtuple<bestlow:
				bestlow=lowtuple
	return bestlow


def equitysolebest(handlist,board,gametype):
	scores=[]
	for i in range(len(handlist)):
		bestdata=equityhighbestdata(handlist[i],board,gametype)
		scores.append(bestdata["score"])
	best=max(scores)
	if scores.count(best)==1:
		return scores.index(best)
	return -1


# ================= 勝率計算器每 IP 速率限制 =================
# equity 是公開勝率計算器工具頁（tool/equity.html）用的端點，不加登入限制以免破壞免登入公開功能，
# 改用模組層 in-memory 每 IP 速率限制防止匿名濫用：每 IP 每 EQUITYRATELIMITWINDOW 秒最多
# EQUITYRATELIMITMAX 次，超限回 429。帶有效 token 的登入使用者略過此限流。
# 取 IP 優先用 nginx 設的 X-Real-IP，取不到才 fallback REMOTE_ADDR；本部署兩者都是真實 client IP
# (uvicorn proxy_headers 預設開啟，已從 X-Forwarded-For 還原真實來源；nginx 也有 proxy_set_header
#  X-Real-IP $remote_addr 覆寫用戶端偽造值)，統一取法讓四處寫法一致。
EQUITYRATELIMITWINDOW=60
EQUITYRATELIMITMAX=12
EQUITYRATELIMITLOCK=threading.Lock()
equityratelimitrecord={}


def equityratelimited(request):
	"""回傳該請求來源 IP 是否已超過勝率計算速率限制；未超過時記下這一次。"""
	ip=request.META.get("HTTP_X_REAL_IP") or request.META.get("REMOTE_ADDR","")
	now=time.time()
	limited=False
	with EQUITYRATELIMITLOCK:
		# 順手清掉已全部過期的 IP 紀錄，避免 dict 無限成長
		for key in list(equityratelimitrecord.keys()):
			recentlist=[t for t in equityratelimitrecord[key] if now-t<EQUITYRATELIMITWINDOW]
			if recentlist:
				equityratelimitrecord[key]=recentlist
			else:
				del equityratelimitrecord[key]
		recentlist=equityratelimitrecord.get(ip,[])
		if len(recentlist)>=EQUITYRATELIMITMAX:
			limited=True
		else:
			recentlist.append(now)
			equityratelimitrecord[ip]=recentlist
	return limited


@api_view(["POST"])
def equity(request):
	# 公開端點：有帶 token 就驗（驗過視為登入使用者、略過限流），無 token 允許匿名但走每 IP 限流
	userrow=None
	if request.headers.get("Authorization"):
		userrow,errresp=getrequestuser(request)
		if errresp:
			return errresp
	if userrow is None and equityratelimited(request):
		return Response({
			"success": False,
			"data": "ERROR_too_many_requests"
		},status.HTTP_429_TOO_MANY_REQUESTS)
	try:
		data=json.loads(request.body)
	except Exception as error:
		return errorresponse("ERROR_request_data_not_found")
	try:  
		gametype=str(data.get("gametype") or "HE").upper()
		holecount=equityholecount(gametype)
		omahaed=equityomahaed(gametype)
		hiloed=equityhiloed(gametype)
		shortdecked=equityshortdecked(gametype)
		allowedranklist=equityallowedranklist(gametype)
		handrawlist=data.get("handlist")  
		if handrawlist is None:  
			handrawlist=data.get("hands") or []  
		if len(handrawlist)<2 or len(handrawlist)>15:
			return errorresponse("ERROR_request_data_type_error")
		used=[]  
		handlist=[]  
		for handitem in handrawlist:  
			cardtextlist=[cardtext for cardtext in (handitem or []) if cardtext]  
			if len(cardtextlist)!=holecount:  
				return errorresponse("ERROR_request_data_type_error")  
			handcardlist=[]  
			for cardtext in cardtextlist:  
				if equityrankchar(cardtext) not in allowedranklist:
					return errorresponse("ERROR_request_data_type_error")
				if cardtext in used:  
					return errorresponse("ERROR_request_data_type_error")  
				used.append(cardtext)  
				handcardlist.append(eval7.Card(cardtext))  
			handlist.append(handcardlist)  
		boardraw=boardcardsfromdata(data.get("board") or {}) 
		if len(boardraw)>5: 
			return errorresponse("ERROR_request_data_type_error") 
		board=[]  
		for cardtext in boardraw:  
			if equityrankchar(cardtext) not in allowedranklist:
				return errorresponse("ERROR_request_data_type_error")
			if cardtext in used:  
				return errorresponse("ERROR_request_data_type_error")  
			used.append(cardtext)
			board.append(eval7.Card(cardtext))
		deadraw=data.get("dead")
		if deadraw is None:
			deadraw=data.get("deadlist") or []
		deadcards=[]
		for cardtext in deadraw:
			if not cardtext:
				continue
			if equityrankchar(cardtext) not in allowedranklist:
				return errorresponse("ERROR_request_data_type_error")
			if cardtext in used:
				return errorresponse("ERROR_request_data_type_error")
			used.append(cardtext)
			deadcards.append(eval7.Card(cardtext))
		usedcards=[]
		for handcardlist in handlist:
			usedcards=usedcards+handcardlist
		usedcards=usedcards+board+deadcards
		remaining=[]  
		for carditem in eval7.Deck().cards:  
			if shortdecked and equityrankchar(carditem) not in allowedranklist:
				continue
			if carditem not in usedcards:  
				remaining.append(carditem)  
		n=len(handlist)  
		need=5-len(board)  
		wins=[0]*n  
		ties=[0]*n  
		equityshares=[0]*n
		scoops=[0]*n
		total=0  
		def settle(full5):  
			highscorelist=[]
			for i in range(n):
				bestdata=equityhighbestdata(handlist[i],full5,gametype)
				highscorelist.append(bestdata["score"])
			besthigh=max(highscorelist)
			highwinnerlist=[]
			for i in range(n):
				if highscorelist[i]==besthigh:
					highwinnerlist.append(i)
			if hiloed:
				lowwinnerlist=[]
				bestlow=None
				for i in range(n):
					lowscore=equitylowscore(handlist[i],full5,gametype)
					if lowscore is None:
						continue
					if bestlow is None or lowscore<bestlow:
						bestlow=lowscore
						lowwinnerlist=[i]
					elif lowscore==bestlow:
						lowwinnerlist.append(i)
				sharelist=[0]*n
				highshare=1
				if len(lowwinnerlist)>0:
					highshare=0.5
				for i in range(len(highwinnerlist)):
					sharelist[highwinnerlist[i]]=sharelist[highwinnerlist[i]]+(highshare/len(highwinnerlist))
				if len(lowwinnerlist)>0:
					for i in range(len(lowwinnerlist)):
						sharelist[lowwinnerlist[i]]=sharelist[lowwinnerlist[i]]+(0.5/len(lowwinnerlist))
				for i in range(n):
					equityshares[i]=equityshares[i]+sharelist[i]
					if sharelist[i]==1:
						scoops[i]=scoops[i]+1
				return
			if len(highwinnerlist)==1: 
				wins[highwinnerlist[0]]=wins[highwinnerlist[0]]+1 
			else: 
				for i in highwinnerlist: 
					ties[i]=ties[i]+1 
		if need<=0: 
			settle(board) 
			total=1 
		elif need==1 or (need==2 and omahaed==False and hiloed==False and shortdecked==False): 
			for combo in itertools.combinations(remaining,need): 
				settle(board+list(combo)) 
				total=total+1 
		else: 
			iters=8000
			if omahaed:
				iters=3000
			if hiloed:
				iters=3000
			if shortdecked:
				iters=6000
			rem=remaining[:] 
			for _ in range(iters): 
				random.shuffle(rem) 
				settle(board+rem[:need]) 
				total=total+1 
		if total<=0: 
			total=1 
		bestdatalist=[] 
		currentscorelist=[] 
		bestscore=None 
		if len(board)>=3: 
			for i in range(n): 
				bestdata=equityhighbestdata(handlist[i],board,gametype) 
				bestdatalist.append(bestdata) 
				currentscorelist.append(bestdata["score"]) 
				if bestdata["score"] is not None: 
					if bestscore is None or bestdata["score"]>bestscore: 
						bestscore=bestdata["score"] 
		else:
			for i in range(n):
				bestdatalist.append({
					"score": None,
					"bestcardlist": []
				})
				currentscorelist.append(None)
		results=[]  
		for i in range(n):    
			winp=wins[i]/total*100 
			tiep=ties[i]/total*100 
			if hiloed: 
				winp=equityshares[i]/total*100 
				tiep=scoops[i]/total*100 
			handstatus="ahead"    
			outs=[]  
			chopouts=[] 
			if len(board)<3:    
				if omahaed or hiloed: 
					handstatus="need_flop" 
				else: 
					sole=equitypartialsolebest(handlist,board) 
					if sole==i:
						handstatus="ahead"
					else:
						for carditem in remaining: 
							b1=board+[carditem] 
							scores=[] 
							for j in range(n): 
								scores.append(equityvisiblescore(handlist[j]+b1)) 
							best=max(scores) 
							if scores[i]==best and scores.count(best)==1: 
								outs.append(str(carditem)) 
							elif scores[i]==best and 1<scores.count(best):
								chopouts.append(str(carditem))
						if len(outs)>0: 
							handstatus="out" 
						elif len(chopouts)>0:
							handstatus="chop_out"
						else: 
							handstatus="need_flop" 
			elif hiloed:  
				if winp>=100 and tiep<=0:
					handstatus="win"
				elif winp<=0 and tiep>=100:
					handstatus="tie_only"
				else:
					handstatus=""  
			else:    
				sole=equitysolebest(handlist,board,gametype)    
				if sole==i:    
					if winp>=100 and tiep<=0:
						handstatus="win"
					elif winp<=0 and tiep>=100:
						handstatus="tie_only"
					else:
						handstatus="ahead"    
				elif len(board)>=5: 
					if winp<=0 and tiep>=100:
						handstatus="tie_only"
					else:
						handstatus="drawing_dead" 
				else:    
					for carditem in remaining:    
						b1=board+[carditem]    
						scores=[]    
						for j in range(n):   
							scores.append(equityhighbestdata(handlist[j],b1,gametype)["score"])   
						best=max(scores)   
						if scores[i]==best and scores.count(best)==1:   
							outs.append(str(carditem))  
						elif scores[i]==best and 1<scores.count(best):
							chopouts.append(str(carditem))
					if len(outs)>0:   
						handstatus="out"   
					elif len(chopouts)>0:
						handstatus="chop_out"
					elif len(board)==3:   
						handstatus="drawing_dead"  
						for combo in itertools.combinations(remaining,2):  
							b2=board+list(combo)  
							scores=[]  
							for j in range(n):  
								scores.append(equityhighbestdata(handlist[j],b2,gametype)["score"])  
							best=max(scores)  
							if scores[i]==best and scores.count(best)==1:  
								handstatus="runner_runner"  
								break  
					else:  
						handstatus="drawing_dead"  
			results.append({   
				"index": i,   
				"gametype": gametype,
				"win": round(winp,2),   
				"tie": round(tiep,2),   
				"bested": bestscore is not None and currentscorelist[i]==bestscore,  
				"bestcardlist": bestdatalist[i]["bestcardlist"],  
				"outlist": outs,  
				"outs": outs,   
				"chopoutlist": chopouts,
				"status": handstatus  
			})   
		return Response({"success": True,"data": {"resultlist": results,"results": results}},status.HTTP_200_OK) 
	except Exception as error: 
		return errorresponse("ERROR_request_data_type_error") 


@api_view(["POST"])
def newhand(request,tableid):
	ensurehandcolumns()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	tablerow,sessionrow=gettableandsession(tableid)
	if not tablerow:
		return errorresponse("ERROR_table_not_found")
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	access=sessionaccess(sessionrow,userrow)
	if not access["canrecord"]:
		return errorresponse("ERROR_no_permission")
	try:
		data=json.loads(request.body)
	except Exception as error:
		return errorresponse("ERROR_request_data_not_found")
	return persisthand(data,tablerow,sessionrow,userrow,access,None)


def persisthand(data,tablerow,sessionrow,userrow,access,edithandid):
	# edithandid 為 None 時新增手牌；有值時整手完整複寫（編輯最新一手用）
	tableid=tablerow["id"]
	requestdata=validate(data,{
		"dealerseat": "required|integer",
		"selfseating": "required|integer",
		"recordtype": "string",
		"exceptiontype": "string",
		"handcard": "dict",
		"boardcard.flop": "array",
		"boardcard.flop.*": "string",
		"boardcard.turn": "string|nullable",
		"boardcard.river": "string|nullable",
		"bittingdata": "dict",
		"seatinglist": "required|array",
		"showdowndata": "dict",
		"winner": "array",
		"winnerprice": "array",
		"adjustments": "dict",
		"ps": "string",
		"note": "string",
		"totalpot": "integer",
		"positionpot": "array",
		"gametype": "string",
		"blindlevel": "string",
		"levelid": "integer",
		"smallblind": "integer",
		"bigblind": "integer",
		"bigblindante": "integer",
		"ante": "integer",
		"emptybutton": "boolean",
		"deadsmallblind": "boolean",
		"actionsjson": "array",
		"familydata": "dict"
	},{
		"required": "ERROR_request_data_not_found",
		"string": "ERROR_request_data_type_error",
		"integer": "ERROR_request_data_type_error",
		"array": "ERROR_request_data_type_error",
		"dict": "ERROR_request_data_type_error",
		"boolean": "ERROR_request_data_type_error"
	})
	if requestdata["error"] is not None:
		return errorresponse(requestdata["error"])
	data=requestdata["data"]
	recordtype=data.get("recordtype") or "hand"
	if recordtype not in ("hand","quickhand","stackadjustment","brokenhand"):
		return errorresponse("ERROR_request_data_type_error")
	# 快速手牌（quickhand）是獨立的正常手牌，計分牌 / 底池比照 hand 計算，不需要例外類型與備註
	if recordtype in ("stackadjustment","brokenhand"):
		if not data.get("exceptiontype") or not (data.get("ps") or data.get("note")):
			return errorresponse("ERROR_request_data_not_found")
	maxseat=intval(sessionrow.get("maxseat"),9)
	selfseating=intval(data.get("selfseating"))
	if boolval(sessionrow.get("unifiedhandrecord")):
		if selfseating<0 or selfseating>maxseat:
			return errorresponse("ERROR_request_data_type_error")
	else:
		if selfseating<1 or selfseating>maxseat:
			return errorresponse("ERROR_request_data_type_error")
	if not boolval(sessionrow.get("unifiedhandrecord")) and not (access["isown"] or access["isadmin"]):
		seatinglist=data.get("seatinglist") or []
		if selfseating>=len(seatinglist) or not seatinglist[selfseating] or seatinglist[selfseating].get("userid")!=userrow["id"]:
			return errorresponse("ERROR_no_permission")
	seatinglist=data.get("seatinglist")
	if boolval(sessionrow.get("linkuser")):
		linkedseating=[None]
		for i in range(maxseat):
			linkedseating.append(False)
		linkedrow=query(SETTING["dbname"],"""
			SELECT sp."id" AS sessionplayerid,sp."userid",sp."seatno",sp."startchip",u."name"
			FROM "sessionplayer" sp
			JOIN "user" u ON u."id"=sp."userid"
			WHERE sp."sessionid"=%s AND sp."tableid"=%s AND sp."status"='confirmed' AND sp."seatno" IS NOT NULL AND sp."deletetime" IS NULL
		""",[sessionrow["id"],tableid],SETTING["dbsetting"])
		for linked in linkedrow or []:
			seatno=intval(linked["seatno"])
			if 0<seatno and seatno<len(linkedseating):
				oldseat={}
				if seatno<len(seatinglist) and isinstance(seatinglist[seatno],dict):
					oldseat=seatinglist[seatno]
				linkedseating[seatno]={
					"chip": oldseat.get("chip") or linked.get("startchip") or sessionrow.get("chip") or 0,
					"unknownchip": boolval(oldseat.get("unknownchip")) or intval(oldseat.get("chip"),0)<0 or intval(linked.get("startchip"),0)<0,
					"name": linked["name"],
					"userid": linked["userid"],
					"sessionplayerid": linked["sessionplayerid"],
					"banned": oldseat.get("banned") or False,
					"specialbutton": oldseat.get("specialbutton") or ""
				}
		seatinglist=linkedseating
	bittingdata=data.get("bittingdata") or {}
	totalpot=0
	positionpot=[None]
	for i in range(maxseat):
		positionpot.append(0)
	for btype in bittingdata:
		for actiondata in bittingdata[btype]:
			seatno=intval(actiondata.get("seat"))
			chip=intval(actiondata.get("chip"))
			totalpot=totalpot+chip
			if 0<seatno and seatno<len(positionpot):
				positionpot[seatno]=positionpot[seatno]+chip
	# 寫入採兩段式：hand 主列先單獨 INSERT 取得 handid，其餘所有寫入（座位、下注、淘汰連動）
	# 收進 sqllist 用 querytransaction 單一交易執行；交易失敗時補償刪除剛插入的 hand 主列。
	# 編輯路徑（edithandid 有值）不需要新 id，主檔 UPDATE 與 DELETE+重建全部收進同一交易。
	sqllist=[]
	if edithandid is None:
		# token 流水號：取既有 token 數字部分最大值 +1（含軟刪列），不用列數避免重號
		tokenprefix="HD"+str(tablerow["token"])
		tokenrow=query(SETTING["dbname"],"""SELECT COALESCE(MAX(CAST(SUBSTR("token",%s) AS integer)),0)+1 AS nextno FROM "hand" WHERE "tableid"=%s AND SUBSTR("token",%s)~'^[0-9]+$'""",[len(tokenprefix)+1,tableid,len(tokenprefix)+1],SETTING["dbsetting"])
		nextno=1
		if tokenrow:
			nextno=intval(tokenrow[0]["nextno"],1)
		handtoken=tokenprefix+str(nextno).zfill(4)
		handid=query(SETTING["dbname"],"""INSERT INTO "hand"("token","userid","tableid","dealerseat","selfseating","handcard","boardcard","totalpot","gametype","blindlevel","levelid","smallblind","bigblind","bigblindante","ante","emptybutton","deadsmallblind","actionsjson","adjustmentsjson","recordtype","exceptiontype","ps","note","familydatajson","handtime","createtime")VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,NOW(),%s)""",[
			handtoken,userrow["id"],tableid,data.get("dealerseat"),selfseating,json.dumps(data.get("handcard")),json.dumps(data.get("boardcard")),totalpot,
			data.get("gametype") or sessionrow.get("gametype") or "holdem",data.get("blindlevel") or "",data.get("levelid"),data.get("smallblind") or 0,data.get("bigblind") or 0,
			data.get("bigblindante") or 0,data.get("ante") or 0,boolval(data.get("emptybutton")),boolval(data.get("deadsmallblind")),json.dumps(data.get("actionsjson") or []),
			json.dumps(data.get("adjustments") or {}),recordtype,data.get("exceptiontype") or "",data.get("ps") or data.get("note") or "",data.get("note") or data.get("ps") or "",json.dumps(data.get("familydata") or {}),nowtime()
		],SETTING["dbsetting"])
		if not handid:
			return errorresponse("ERROR_database_error")
	else:
		# 編輯最新一手：更新 hand 主檔，並清掉舊的座位/下注紀錄以便整手重建（皆在同一交易內）
		handid=edithandid
		sqllist.append(["""UPDATE "hand" SET "dealerseat"=%s,"selfseating"=%s,"handcard"=%s,"boardcard"=%s,"totalpot"=%s,"gametype"=%s,"blindlevel"=%s,"levelid"=%s,"smallblind"=%s,"bigblind"=%s,"bigblindante"=%s,"ante"=%s,"emptybutton"=%s,"deadsmallblind"=%s,"actionsjson"=%s,"adjustmentsjson"=%s,"familydatajson"=%s,"recordtype"=%s,"exceptiontype"=%s,"ps"=%s,"note"=%s,"updatetime"=%s WHERE "id"=%s""",[
			data.get("dealerseat"),selfseating,json.dumps(data.get("handcard")),json.dumps(data.get("boardcard")),totalpot,
			data.get("gametype") or sessionrow.get("gametype") or "holdem",data.get("blindlevel") or "",data.get("levelid"),data.get("smallblind") or 0,data.get("bigblind") or 0,
			data.get("bigblindante") or 0,data.get("ante") or 0,boolval(data.get("emptybutton")),boolval(data.get("deadsmallblind")),json.dumps(data.get("actionsjson") or []),
			json.dumps(data.get("adjustments") or {}),json.dumps(data.get("familydata") or {}),recordtype,data.get("exceptiontype") or "",data.get("ps") or data.get("note") or "",data.get("note") or data.get("ps") or "",nowtime(),handid
		]])
		sqllist.append(["""DELETE FROM "handseating" WHERE "handid"=%s""",[handid]])
		sqllist.append(["""DELETE FROM "handbittingdata" WHERE "handid"=%s""",[handid]])
	showdowndata=data.get("showdowndata") or {}
	winner=data.get("winner") or [None]
	winnerprice=data.get("winnerprice") or [None]
	adjustments=data.get("adjustments") or {}
	bustedplayers=[]
	insertedseats=set()
	for seatno in range(1,len(seatinglist)):
		if seatinglist[seatno]!=False and seatinglist[seatno] is not None:
			seat=seatinglist[seatno]
			chip=seat.get("chip") or 0
			unknownchip=boolval(seat.get("unknownchip")) or intval(chip,0)<0 or "UNKNOWN_CHIP" in str(seat.get("specialbutton") or "")
			if unknownchip:
				chip=-1
			seatcard=None
			key=str(seatno)
			if key in showdowndata and showdowndata[key].get("shown")==True:
				# 保留全部底牌（奧馬哈 4-5 張、短牌 2 張），不只 card1/card2，否則重新編輯時會掉牌
				seatcard={cardkey:showdowndata[key].get(cardkey) for cardkey in showdowndata[key] if str(cardkey).startswith("card") and showdowndata[key].get(cardkey)}
			winnered=True if seatno<len(winner) and winner[seatno]==True else False
			ppot=positionpot[seatno] if seatno<len(positionpot) and positionpot[seatno] is not None and positionpot[seatno] is not False else 0
			wpot=winnerprice[seatno] if seatno<len(winnerprice) and winnerprice[seatno] is not None and winnerprice[seatno] is not False else 0
			adjustment=0
			if isinstance(adjustments,dict):
				adjustment=intval(adjustments.get(str(seatno)) or adjustments.get(seatno),0)
			if recordtype not in ("hand","quickhand"):
				ppot=adjustment
				endchip=chip+adjustment
			elif winnered:
				endchip=chip+wpot-ppot
			else:
				endchip=chip-ppot
			specialbutton=seat.get("specialbutton") or ""
			if unknownchip and "UNKNOWN_CHIP" not in str(specialbutton):
				specialbutton=(str(specialbutton)+"|UNKNOWN_CHIP").strip("|")
			sqllist.append(["""INSERT INTO "handseating"("handid","seatno","name","chip","handcard","banned","chipchange","endchip","winnered","userid","sessionplayerid","specialbutton","createtime")VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",[
				handid,seatno,seat.get("name") or "",chip,json.dumps(seatcard),boolval(seat.get("banned")),ppot,endchip,winnered,seat.get("userid"),seat.get("sessionplayerid"),specialbutton,nowtime()
			]])
			insertedseats.add(seatno)
			if recordtype=="hand" and boolval(sessionrow.get("unifiedhandrecord")) and boolval(sessionrow.get("linkuser")) and not unknownchip and intval(endchip,0)<=0 and seat.get("sessionplayerid") and seat.get("userid"):
				bustedplayers.append({"sessionplayerid": seat.get("sessionplayerid"),"userid": seat.get("userid"),"chip": intval(chip,0)})
	if recordtype=="hand" and boolval(sessionrow.get("unifiedhandrecord")) and boolval(sessionrow.get("linkuser")) and bustedplayers:
		# 統一紀錄手牌：玩家計分牌歸 0 自動淘汰，操作者送出後不需再請裁判處理。
		# 同一手同桌多人爆掉時，名次依「該手開始時的計分牌」決定：計分牌少的名次較差（視為先出局）。
		# 名次靠 eliminatedtime 排序（早＝名次差），故依計分牌由小到大給遞增毫秒位移，讓小計分牌最早＝名次最差。
		bustedplayers.sort(key=lambda bp: intval(bp.get("chip"),0))
		for idx in range(len(bustedplayers)):
			bp=bustedplayers[idx]
			sqllist.append(["""
				INSERT INTO "sessiontimerplayer"("sessionid","sessionplayerid","userid","status","eliminatedtime","createtime","updatetime")
				VALUES(%s,%s,%s,%s,NOW()+(%s*INTERVAL '1 millisecond'),NOW(),NOW())
				ON CONFLICT ("sessionid","sessionplayerid")
				DO UPDATE SET "status"='eliminated',"eliminatedtime"=NOW()+(%s*INTERVAL '1 millisecond'),"deletetime"=NULL,"updatetime"=NOW()
			""",[sessionrow["id"],bp["sessionplayerid"],bp["userid"],"eliminated",idx,idx]])
			sqllist.append(["""UPDATE "sessionplayer" SET "tableid"=NULL,"seatno"=NULL,"updatetime"=NOW() WHERE "id"=%s""",[bp["sessionplayerid"]]])
	# 有下注紀錄卻沒寫進座位的座位（例如送出前先被淘汰），補一筆座位避免結果表看不到
	submittedseating=data.get("seatinglist") or []
	bittingseats=[]
	for btype in bittingdata:
		for actiondata in bittingdata[btype]:
			bseat=intval(actiondata.get("seat"))
			if 0<bseat and bseat not in bittingseats:
				bittingseats.append(bseat)
	for bseat in bittingseats:
		if bseat in insertedseats:
			continue
		oldseat=submittedseating[bseat] if bseat<len(submittedseating) and isinstance(submittedseating[bseat],dict) else {}
		chip=oldseat.get("chip") or 0
		unknownchip=boolval(oldseat.get("unknownchip")) or intval(chip,0)<0 or "UNKNOWN_CHIP" in str(oldseat.get("specialbutton") or "")
		if unknownchip or not chip:
			chip=-1
			unknownchip=True
		seatcard=None
		key=str(bseat)
		if key in showdowndata and showdowndata[key].get("shown")==True:
			seatcard={
				"card1": showdowndata[key].get("card1"),
				"card2": showdowndata[key].get("card2")
			}
		winnered=True if bseat<len(winner) and winner[bseat]==True else False
		ppot=positionpot[bseat] if bseat<len(positionpot) and positionpot[bseat] is not None and positionpot[bseat] is not False else 0
		wpot=winnerprice[bseat] if bseat<len(winnerprice) and winnerprice[bseat] is not None and winnerprice[bseat] is not False else 0
		adjustment=0
		if isinstance(adjustments,dict):
			adjustment=intval(adjustments.get(str(bseat)) or adjustments.get(bseat),0)
		if recordtype not in ("hand","quickhand"):
			ppot=adjustment
			endchip=chip+adjustment
		elif winnered:
			endchip=chip+wpot-ppot
		else:
			endchip=chip-ppot
		specialbutton=oldseat.get("specialbutton") or ""
		if unknownchip and "UNKNOWN_CHIP" not in str(specialbutton):
			specialbutton=(str(specialbutton)+"|UNKNOWN_CHIP").strip("|")
		sqllist.append(["""INSERT INTO "handseating"("handid","seatno","name","chip","handcard","banned","chipchange","endchip","winnered","userid","sessionplayerid","specialbutton","createtime")VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",[
			handid,bseat,oldseat.get("name") or "",chip,json.dumps(seatcard),boolval(oldseat.get("banned")),ppot,endchip,winnered,oldseat.get("userid"),oldseat.get("sessionplayerid"),specialbutton,nowtime()
		]])
		insertedseats.add(bseat)
	for btype in bittingdata:
		for actiondata in bittingdata[btype]:
			action=actiondata.get("action")
			if boolval(actiondata.get("allined")):
				action="allin"
			sqllist.append(["""INSERT INTO "handbittingdata"("handid","type","seatno","action","chip","timebank","blinded","bbed","createtime")VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s)""",[
				handid,btype,actiondata.get("seat"),action,actiondata.get("chip") or 0,actiondata.get("timebank") or 0,boolval(actiondata.get("isBlind")),boolval(actiondata.get("isSB")),nowtime()
			]])
	if sqllist:
		transactionresult=querytransaction(SETTING["dbname"],sqllist,SETTING["dbsetting"])
		if transactionresult is None:
			if edithandid is None:
				# 補償：交易失敗時刪掉剛插入的 hand 主列，避免留下沒有座位/下注資料的孤兒手牌
				query(SETTING["dbname"],"""DELETE FROM "hand" WHERE "id"=%s""",[handid],SETTING["dbsetting"])
			return errorresponse("ERROR_database_error")
	if recordtype=="hand" and boolval(sessionrow.get("unifiedhandrecord")) and boolval(sessionrow.get("linkuser")) and bustedplayers:
		try:
			from .sessionplayer import _broadcastsessiontimer
			_broadcastsessiontimer(sessionrow)
		except Exception as error:
			pass
	if edithandid is None:
		state=advancehandcount(sessionrow)
		handbroadcast(sessionrow["id"],"hand.created",handid,state)
	else:
		handbroadcast(sessionrow["id"],"hand.updated",handid,{})
	return Response({"success": True,"data": {"id": handid}},status.HTTP_200_OK)


@api_view(["PUT"])
def editmyhandcard(request,handid):
	ensurehandcolumns()
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	row=query(SETTING["dbname"],"""
		SELECT h.*,t."sessionid"
		FROM "hand" h
		JOIN "table" t ON t."id"=h."tableid"
		WHERE h."id"=%s AND h."deletetime" IS NULL
	""",[handid],SETTING["dbsetting"])
	if not row:
		return errorresponse("ERROR_hand_not_found")
	hand=row[0]
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[hand["sessionid"]],SETTING["dbsetting"])
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	if not boolval(sessionrow[0].get("unifiedhandrecord")):
		return errorresponse("ERROR_no_permission")
	seatingrow=query(SETTING["dbname"],"""SELECT*FROM "handseating" WHERE "handid"=%s AND "userid"=%s AND "deletetime" IS NULL LIMIT 1""",[handid,userrow["id"]],SETTING["dbsetting"])
	if not seatingrow:
		return errorresponse("ERROR_no_permission")
	try:
		data=json.loads(request.body)
	except Exception as error:
		return errorresponse("ERROR_request_data_not_found")
	requestdata=validate(data,{
		"handcard": "dict",
		"handcard.card1": "string|nullable",
		"handcard.card2": "string|nullable",
		"note": "string"
	},{
		"string": "ERROR_request_data_type_error",
		"dict": "ERROR_request_data_type_error"
	})
	if requestdata["error"] is not None:
		return errorresponse(requestdata["error"])
	data=requestdata["data"]
	handcard=data.get("handcard") or {}
	card1=handcard.get("card1") or ""
	card2=handcard.get("card2") or ""
	note=data.get("note") or ""
	cardrow=query(SETTING["dbname"],"""SELECT*FROM "handplayercard" WHERE "handid"=%s AND "playerid"=%s AND "deletetime" IS NULL ORDER BY "id" DESC LIMIT 1""",[handid,userrow["id"]],SETTING["dbsetting"])
	if cardrow:
		queryupdate(SETTING["dbname"],"handplayercard",{
			"card1": card1,
			"card2": card2,
			"note": note,
			"revealed": False,
			"updatetime": nowtime()
		},{"id": cardrow[0]["id"]},SETTING["dbsetting"])
	else:
		query(SETTING["dbname"],"""INSERT INTO "handplayercard"("handid","playerid","card1","card2","revealed","note","createtime")VALUES(%s,%s,%s,%s,%s,%s,%s)""",[
			handid,userrow["id"],card1,card2,False,note,nowtime()
		],SETTING["dbsetting"])
	handbroadcast(sessionrow[0]["id"],"hand.mycard.updated",handid,{})
	return Response({"success": True,"data": ""},status.HTTP_200_OK)


@api_view(["PUT"])
def edithand(request,handid):
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	row=query(SETTING["dbname"],"""SELECT h.*,t."sessionid" FROM "hand" h JOIN "table" t ON t."id"=h."tableid" WHERE h."id"=%s AND h."deletetime" IS NULL""",[handid],SETTING["dbsetting"])
	if not row:
		return errorresponse("ERROR_hand_not_found")
	hand=row[0]
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[hand["sessionid"]],SETTING["dbsetting"])
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	access=sessionaccess(sessionrow[0],userrow)
	if not (hand["userid"]==userrow["id"] or access["canunifiedrecord"]):
		return errorresponse("ERROR_no_permission")
	try:
		data=json.loads(request.body)
	except Exception as error:
		return errorresponse("ERROR_request_data_not_found")
	# 只有最新一手能整手重寫；舊手牌一旦改計分牌會污染後面手牌的起始碼量，因此只允許改不影響計分牌的欄位。
	# 例外：快速手牌（quickhand）為獨立紀錄、不與其他手牌連動，任何時候都可整手重寫（含計分牌）。
	latestrow=query(SETTING["dbname"],"""SELECT "id" FROM "hand" WHERE "tableid"=%s AND "deletetime" IS NULL ORDER BY "createtime" DESC,"id" DESC LIMIT 1""",[hand["tableid"]],SETTING["dbsetting"])
	islatest=bool(latestrow) and str(latestrow[0]["id"])==str(handid)
	isquickhand=hand.get("recordtype")=="quickhand"
	if (islatest or isquickhand) and "seatinglist" in data:
		tablerow,sessionfull=gettableandsession(hand["tableid"])
		if not tablerow or not sessionfull:
			return errorresponse("ERROR_table_not_found")
		fullaccess=sessionaccess(sessionfull,userrow)
		return persisthand(data,tablerow,sessionfull,userrow,fullaccess,handid)
	update={}
	for key in ["ps","note","blindlevel","levelid","smallblind","bigblind","bigblindante","ante"]:
		if key in data:
			update[key]=data[key]
	if "handcard" in data:
		update["handcard"]=json.dumps(data["handcard"])
	if "boardcard" in data:
		update["boardcard"]=json.dumps(data["boardcard"])
	if "actionsjson" in data:
		update["actionsjson"]=json.dumps(data["actionsjson"])
	if update:
		update["updatetime"]=nowtime()
		queryupdate(SETTING["dbname"],"hand",update,{"id": handid},SETTING["dbsetting"])
	handbroadcast(sessionrow[0]["id"],"hand.updated",handid,{})
	return Response({"success": True,"data": ""},status.HTTP_200_OK)


@api_view(["DELETE"])
def deletehand(request,handid):
	userrow,errresp=getrequestuser(request)
	if errresp:
		return errresp
	row=query(SETTING["dbname"],"""SELECT h.*,t."sessionid" FROM "hand" h JOIN "table" t ON t."id"=h."tableid" WHERE h."id"=%s AND h."deletetime" IS NULL""",[handid],SETTING["dbsetting"])
	if not row:
		return errorresponse("ERROR_hand_not_found")
	hand=row[0]
	sessionrow=query(SETTING["dbname"],"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[hand["sessionid"]],SETTING["dbsetting"])
	if not sessionrow:
		return errorresponse("ERROR_session_not_found")
	access=sessionaccess(sessionrow[0],userrow)
	if not (hand["userid"]==userrow["id"] or access["canunifiedrecord"]):
		return errorresponse("ERROR_no_permission")
	# 只允許刪除同桌最新一筆紀錄；刪掉中間的會讓後面手牌的起始碼量對不上而錯亂。
	# 例外：快速手牌（quickhand）為獨立紀錄、不與其他手牌連動，任何一筆都可刪除。
	if hand.get("recordtype")!="quickhand":
		latestrow=query(SETTING["dbname"],"""SELECT "id" FROM "hand" WHERE "tableid"=%s AND "deletetime" IS NULL ORDER BY "createtime" DESC,"id" DESC LIMIT 1""",[hand["tableid"]],SETTING["dbsetting"])
		if not (latestrow and str(latestrow[0]["id"])==str(handid)):
			return errorresponse("ERROR_only_latest_hand_deletable")
	# 還原 persisthand 自動寫入的淘汰連動：依寫入條件反推「這一手造成淘汰」的座位
	# （recordtype=hand、統一紀錄＋連動玩家、計分牌已知且 endchip<=0、有 sessionplayerid/userid），
	# 把 sessiontimerplayer 還原為 active、sessionplayer 還原回原桌原座位。
	# 保護條件：只在該玩家仍是 eliminated、且座位仍空著（未被重買/換座覆蓋）時才還原，避免蓋掉之後的手動異動。
	restorelist=[]
	if hand.get("recordtype")=="hand" and boolval(sessionrow[0].get("unifiedhandrecord")) and boolval(sessionrow[0].get("linkuser")):
		bustedrow=query(SETTING["dbname"],"""SELECT*FROM "handseating" WHERE "handid"=%s AND "deletetime" IS NULL AND "sessionplayerid" IS NOT NULL AND "userid" IS NOT NULL AND "chip">=0 AND "endchip"<=0 AND COALESCE("specialbutton",'') NOT LIKE '%%UNKNOWN_CHIP%%'""",[handid],SETTING["dbsetting"])
		for busted in bustedrow or []:
			restorelist.append([
				"""UPDATE "sessiontimerplayer" SET "status"='active',"eliminatedtime"=NULL,"place"=NULL,"updatetime"=NOW() WHERE "sessionid"=%s AND "sessionplayerid"=%s AND "status"='eliminated' AND "deletetime" IS NULL""",
				[hand["sessionid"],busted["sessionplayerid"]]
			])
			# 自動回座屬於自動入座路徑: 該桌若已被關閉 (closedtime 有值, 例如已併桌拆掉) 就不回座, 讓玩家維持未入座由工作人員手動安排
			restorelist.append([
				"""UPDATE "sessionplayer" SET "tableid"=%s,"seatno"=%s,"updatetime"=NOW() WHERE "id"=%s AND "tableid" IS NULL AND "seatno" IS NULL AND "deletetime" IS NULL AND NOT EXISTS(SELECT 1 FROM "sessionplayer" sp2 WHERE sp2."sessionid"=%s AND sp2."tableid"=%s AND sp2."seatno"=%s AND sp2."status"='confirmed' AND sp2."deletetime" IS NULL) AND EXISTS(SELECT 1 FROM "table" t2 WHERE t2."id"=%s AND t2."deletetime" IS NULL AND t2."closedtime" IS NULL)""",
				[hand["tableid"],busted["seatno"],busted["sessionplayerid"],hand["sessionid"],hand["tableid"],busted["seatno"],hand["tableid"]]
			])
	sqllist=[
		["""UPDATE "hand" SET "deletetime"=NOW() WHERE "id"=%s""",[handid]],
		["""UPDATE "handseating" SET "deletetime"=NOW() WHERE "handid"=%s""",[handid]],
		["""UPDATE "handbittingdata" SET "deletetime"=NOW() WHERE "handid"=%s""",[handid]]
	]+restorelist
	transactionresult=querytransaction(SETTING["dbname"],sqllist,SETTING["dbsetting"])
	if transactionresult is None:
		return errorresponse("ERROR_database_error")
	if restorelist:
		try:
			from .sessionplayer import _broadcastsessiontimer
			_broadcastsessiontimer(sessionrow[0])
		except Exception as error:
			pass
	handbroadcast(sessionrow[0]["id"],"hand.deleted",handid,{})
	return Response({"success": True,"data": ""},status.HTTP_200_OK)
