# notification.py
# ===========================================================================
# 通知中心（檢查表 3.1）：站內通知 + 關鍵事件 Email 提醒
#   * notifyevent() 供其他模組在事件點呼叫，已自帶 try/except，絕不會影響主流程
#   * 站內通知讀取 / 已讀 / 刪除 端點
# ===========================================================================

import threading

from django.core.mail import send_mail
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from function.sql import *
from function.thing import *
from function.function import *
from .initialize import *
from .authhelper import gettokenuser


def asyncsendmail(*args, **kwargs):
	threading.Thread(target=send_mail, args=args, kwargs=kwargs).start()


notificationtableensured=False
notificationtableensuredlock=threading.Lock()


def ensurenotificationtable():
	# CREATE TABLE IF NOT EXISTS 雖冪等, 但六個端點每次請求都跑會反覆對 DB 取鎖;
	# 比照 session.py ensuresessionsettingcolumns 的 run-once 模式, 加模組層旗標 + threading.Lock double-checked, 每個行程只跑一次
	global notificationtableensured
	if notificationtableensured:
		return
	with notificationtableensuredlock:
		if notificationtableensured:
			return
		query(SETTING["dbname"], """CREATE TABLE IF NOT EXISTS "notification"(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			userid bigint NOT NULL,
			sessionid bigint,
			type varchar(50) NOT NULL DEFAULT '',
			title varchar(200) NOT NULL DEFAULT '',
			message text NOT NULL DEFAULT '',
			readed boolean NOT NULL DEFAULT false,
			createtime timestamp with time zone NOT NULL DEFAULT now(),
			updatetime timestamp with time zone NOT NULL DEFAULT now(),
			deletetime timestamp with time zone
		)""", [], SETTING["dbsetting"])
		notificationtableensured=True


def notifyevent(userid, sessionid, ntype, title, message, email=False):
	# 在事件點建立一筆站內通知；可選擇同時寄 Email。
	# 整個函式包在 try/except 內，通知失敗不可拖垮報名/確認/晉級等主要流程。
	try:
		if not userid:
			return
		ensurenotificationtable()
		queryinsert(SETTING["dbname"], "notification", {
			"userid": userid,
			"sessionid": sessionid,
			"type": ntype,
			"title": title,
			"message": message,
			"readed": False,
			"createtime": nowtime()
		}, SETTING["dbsetting"])
		if email:
			userrow = query(SETTING["dbname"], """SELECT "email","name" FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""", [userid], SETTING["dbsetting"])
			if userrow and userrow[0].get("email"):
				asyncsendmail("PokerTrace 通知：" + str(title), str(message), None, [userrow[0]["email"]], fail_silently=True)
	except Exception as error:
		pass


@api_view(["GET"])
def getnotificationlist(request):
	# 站內通知列表：支援 ?page=、?limit=（分頁）與 ?keyword=（比對標題/內容）。
	# 回傳格式與系統 API 紀錄一致：{"list":[...],"pagination":{...}}，前端共用分頁切換器。
	user, errresp = gettokenuser(request)
	if errresp:
		return errresp
	ensurenotificationtable()

	try:
		page = max(1, int(request.GET.get("page") or 1))
	except Exception as error:
		page = 1
	try:
		limit = max(1, min(200, int(request.GET.get("limit") or 20)))
	except Exception as error:
		limit = 20

	conditions = ["\"userid\"=%s", "\"deletetime\" IS NULL"]
	params = [user["id"]]
	if request.GET.get("keyword"):
		keyword = "%" + request.GET.get("keyword") + "%"
		conditions.append("(\"title\" ILIKE %s OR \"message\" ILIKE %s)")
		params.append(keyword)
		params.append(keyword)
	where = " WHERE " + " AND ".join(conditions)

	countrow = query(SETTING["dbname"], f"""SELECT COUNT(*) AS "total" FROM "notification"{where}""", params, SETTING["dbsetting"])
	total = int(countrow[0]["total"]) if countrow else 0

	totalpages = (total + limit - 1) // limit
	if totalpages <= 0:
		totalpages = 1
	if totalpages < page:
		page = totalpages

	rows = query(SETTING["dbname"], f"""SELECT * FROM "notification"{where} ORDER BY "createtime" DESC LIMIT %s OFFSET %s""", params + [limit, (page - 1) * limit], SETTING["dbsetting"]) or []
	return Response({
		"success": True,
		"data": {
			"list": rows,
			"pagination": {
				"page": page,
				"limit": limit,
				"total": total,
				"totalpages": totalpages,
				"hasprev": 1 < page,
				"hasnext": page < totalpages
			}
		}
	}, status.HTTP_200_OK)


@api_view(["GET"])
def getnotificationunreadcount(request):
	user, errresp = gettokenuser(request)
	if errresp:
		return errresp
	ensurenotificationtable()
	unreadrow = query(SETTING["dbname"], """SELECT count(*) AS c FROM "notification" WHERE "userid"=%s AND "readed"=false AND "deletetime" IS NULL""", [user["id"]], SETTING["dbsetting"])
	unread = 0
	if unreadrow:
		unread = unreadrow[0].get("c") or 0
	return Response({
		"success": True,
		"data": {"unread": unread}
	}, status.HTTP_200_OK)


@api_view(["PUT"])
def readnotification(request, notificationid):
	user, errresp = gettokenuser(request)
	if errresp:
		return errresp
	ensurenotificationtable()
	query(SETTING["dbname"], """UPDATE "notification" SET "readed"=true,"updatetime"=NOW() WHERE "id"=%s AND "userid"=%s AND "deletetime" IS NULL""", [notificationid, user["id"]], SETTING["dbsetting"])
	return Response({"success": True, "data": ""}, status.HTTP_200_OK)


@api_view(["PUT"])
def readallnotification(request):
	user, errresp = gettokenuser(request)
	if errresp:
		return errresp
	ensurenotificationtable()
	query(SETTING["dbname"], """UPDATE "notification" SET "readed"=true,"updatetime"=NOW() WHERE "userid"=%s AND "readed"=false AND "deletetime" IS NULL""", [user["id"]], SETTING["dbsetting"])
	return Response({"success": True, "data": ""}, status.HTTP_200_OK)


@api_view(["DELETE"])
def deletenotification(request, notificationid):
	user, errresp = gettokenuser(request)
	if errresp:
		return errresp
	ensurenotificationtable()
	query(SETTING["dbname"], """UPDATE "notification" SET "deletetime"=NOW() WHERE "id"=%s AND "userid"=%s AND "deletetime" IS NULL""", [notificationid, user["id"]], SETTING["dbsetting"])
	return Response({"success": True, "data": ""}, status.HTTP_200_OK)
