# timer.py

import datetime
import json
from decimal import Decimal
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from function.validation import *
from function.sql import *
from function.thing import *
from function.function import *
from .initialize import *
from .authhelper import gettokenuser as commonauthuser

DEFAULTSCHEDULE=[
	{"type": "level","sb": 100,"bb": 200,"ante": 200,"dur": 20},
	{"type": "level","sb": 200,"bb": 400,"ante": 400,"dur": 20},
	{"type": "level","sb": 300,"bb": 600,"ante": 600,"dur": 20},
	{"type": "level","sb": 400,"bb": 800,"ante": 800,"dur": 20},
	{"type": "level","sb": 500,"bb": 1000,"ante": 1000,"dur": 20},
	{"type": "break","dur": 10,"regCloseAfter": True},
	{"type": "level","sb": 800,"bb": 1600,"ante": 1600,"dur": 20},
	{"type": "level","sb": 1200,"bb": 2400,"ante": 2400,"dur": 20},
	{"type": "level","sb": 1500,"bb": 3000,"ante": 3000,"dur": 20},
	{"type": "level","sb": 2000,"bb": 4000,"ante": 4000,"dur": 20},
	{"type": "level","sb": 3000,"bb": 6000,"ante": 6000,"dur": 20}
]

DEFAULTPAYOUTS=[
	{"rank": "1","pct": 1,"color": "#cbd5e1"},
]

DEFAULTMARQUEE=""

def normalizetimerstate(stateval):
	if stateval is None:
		return {}
	if isinstance(stateval,str):
		try:
			return json.loads(stateval)
		except Exception as error:
			return {}
	return stateval

def boolval(value):
	if value==True or value==1 or value=="1" or value=="true" or value=="True":
		return True
	return False

def intval(value,defaultvalue=0):
	try:
		return int(value)
	except Exception as error:
		return defaultvalue

def floatval(value,defaultvalue=0):
	try:
		return float(value)
	except Exception as error:
		return defaultvalue

def parsetimervalue(value):
	if not value:
		return None
	if isinstance(value,datetime.datetime):
		return value.replace(tzinfo=None)
	text=str(value).replace("T"," ").replace("Z","")
	if "+" in text:
		text=text.split("+")[0]
	if "." in text:
		text=text.split(".")[0]
	try:
		return datetime.datetime.strptime(text,"%Y-%m-%d %H:%M:%S")
	except Exception as error:
		return None

def timerseconds(item):
	return intval(item.get("dur"),20)*60

def normalizeindex(index,schedule):
	if not schedule:
		return 0
	index=intval(index,0)
	if index<0:
		return 0
	if len(schedule)<=index:
		return len(schedule)-1
	return index

def advanceruntime(runtime,schedule):
	runtime=normalizetimerstate(runtime)
	if not schedule:
		return runtime
	now=nowtime()
	index=normalizeindex(runtime.get("currentIndex"),schedule)
	secondsleft=intval(runtime.get("anchorSecondsLeft"),intval(runtime.get("secondsLeft"),timerseconds(schedule[index])))
	if secondsleft<0:
		secondsleft=0
	running=boolval(runtime.get("running"))
	if running:
		anchortime=parsetimervalue(runtime.get("anchorTime")) or parsetimervalue(runtime.get("lastSyncTime"))
		if anchortime:
			elapsed=int((datetime.datetime.now()-anchortime).total_seconds())
			if 0<elapsed:
				secondsleft=secondsleft-elapsed
		while secondsleft<=0 and index<len(schedule)-1:
			if boolval(schedule[index].get("regCloseAfter")) and not boolval(runtime.get("regCloseHandled")):
				runtime["regClosed"]=True
				runtime["regCloseHandled"]=True
			index=index+1
			secondsleft=secondsleft+timerseconds(schedule[index])
		if secondsleft<=0:
			secondsleft=0
			running=False
	runtime["currentIndex"]=index
	runtime["secondsLeft"]=secondsleft
	runtime["running"]=running
	runtime["anchorSecondsLeft"]=secondsleft
	runtime["anchorTime"]=now
	runtime["lastSyncTime"]=now
	return runtime

def saveregclosedbyindex(runtime,schedule):
	return runtime

def ensuretimertables():
	query(SETTING["dbname"],"""ALTER TABLE public."table" ADD COLUMN IF NOT EXISTS no integer""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""
		DO $$
		BEGIN
			IF EXISTS(
				SELECT 1 FROM information_schema.columns
				WHERE table_schema='public' AND table_name='table' AND column_name='name'
			) THEN
				EXECUTE 'UPDATE public."table" SET no=CASE WHEN name ~ ''^[0-9]+$'' THEN name::integer ELSE id::integer END WHERE no IS NULL';
			ELSE
				UPDATE public."table" SET no=id::integer WHERE no IS NULL;
			END IF;
		END $$;
	""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""
		CREATE TABLE IF NOT EXISTS public.sessiontimerconfig(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			sessionid bigint NOT NULL UNIQUE,
			tournname varchar(200) NOT NULL DEFAULT '',
			subtitle varchar(200) NOT NULL DEFAULT '',
			startingchips bigint NOT NULL DEFAULT 0,
			buyin bigint NOT NULL DEFAULT 0,
			fee bigint NOT NULL DEFAULT 0,
			defaultbreakdur integer NOT NULL DEFAULT 10,
			soundon boolean NOT NULL DEFAULT true,
			vibeon boolean NOT NULL DEFAULT true,
			prizepoolmode varchar(20) NOT NULL DEFAULT 'auto',
			prizepoolmanual bigint NOT NULL DEFAULT 0,
			itmmode varchar(20) NOT NULL DEFAULT 'pct',
			itmpct numeric NOT NULL DEFAULT 15,
			itmcount integer NOT NULL DEFAULT 7,
			marqueetext text NOT NULL DEFAULT '',
			autostartbytime boolean NOT NULL DEFAULT false,
			createtime timestamp with time zone NOT NULL DEFAULT now(),
			updatetime timestamp with time zone NOT NULL DEFAULT now(),
			deletetime timestamp with time zone
		)
	""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.sessiontimerconfig ADD COLUMN IF NOT EXISTS autostartbytime boolean NOT NULL DEFAULT false""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""
		CREATE TABLE IF NOT EXISTS public.sessiontimerlevel(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			sessionid bigint NOT NULL,
			sortorder integer NOT NULL,
			type varchar(20) NOT NULL DEFAULT 'level',
			smallblind bigint NOT NULL DEFAULT 0,
			bigblind bigint NOT NULL DEFAULT 0,
			ante bigint NOT NULL DEFAULT 0,
			durationminutes integer NOT NULL DEFAULT 20,
			timemode varchar(20) NOT NULL DEFAULT 'time',
			handtargetcount integer NOT NULL DEFAULT 0,
			handcount integer NOT NULL DEFAULT 0,
			regcloseafter boolean NOT NULL DEFAULT false,
			chipraisevalues text NOT NULL DEFAULT '[]',
			createtime timestamp with time zone NOT NULL DEFAULT now(),
			updatetime timestamp with time zone NOT NULL DEFAULT now(),
			deletetime timestamp with time zone
		)
	""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.sessiontimerlevel ADD COLUMN IF NOT EXISTS chipraisevalues text NOT NULL DEFAULT '[]'""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.sessiontimerlevel ADD COLUMN IF NOT EXISTS timemode varchar(20) NOT NULL DEFAULT 'time'""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.sessiontimerlevel ADD COLUMN IF NOT EXISTS handtargetcount integer NOT NULL DEFAULT 0""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.sessiontimerlevel ADD COLUMN IF NOT EXISTS handcount integer NOT NULL DEFAULT 0""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""
		CREATE TABLE IF NOT EXISTS public.sessiontimerpayout(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			sessionid bigint NOT NULL,
			sortorder integer NOT NULL,
			rank varchar(50) NOT NULL DEFAULT '',
			pct numeric NOT NULL DEFAULT 0,
			reward text NOT NULL DEFAULT '',
			color varchar(20) NOT NULL DEFAULT '#888',
			createtime timestamp with time zone NOT NULL DEFAULT now(),
			updatetime timestamp with time zone NOT NULL DEFAULT now(),
			deletetime timestamp with time zone
		)
	""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""ALTER TABLE public.sessiontimerpayout ADD COLUMN IF NOT EXISTS reward text NOT NULL DEFAULT ''""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""
		CREATE TABLE IF NOT EXISTS public.sessiontimerplayer(
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			sessionid bigint NOT NULL,
			sessionplayerid bigint NOT NULL,
			userid bigint NOT NULL,
			status varchar(20) NOT NULL DEFAULT 'active',
			eliminatedtime timestamp with time zone,
			place integer,
			createtime timestamp with time zone NOT NULL DEFAULT now(),
			updatetime timestamp with time zone NOT NULL DEFAULT now(),
			deletetime timestamp with time zone,
			UNIQUE(sessionid,sessionplayerid)
		)
	""",[],SETTING["dbsetting"])

def gettimerpermissionuser(request):
	return commonauthuser(request)

def hastimercontrolpermission(sessionrow,userrow):
	if not userrow:
		return False
	if sessionrow["userid"]==userrow["id"]:
		return True
	if 4<=int(userrow["permission"]):
		return True
	staffrow=query(SETTING["dbname"],f"""SELECT*FROM "sessionstaff" WHERE "sessionid"=%s AND "staffuserid"=%s AND "role" IN ('floor','assistant') AND "status"='active' AND "deletetime" IS NULL""",[sessionrow["id"],userrow["id"]],SETTING["dbsetting"])
	if staffrow:
		return True
	staffrow=query(SETTING["dbname"],f"""SELECT*FROM "userstaff" WHERE "userid"=%s AND "staffuserid"=%s AND "role" IN ('floor','assistant') AND "status"='active' AND "deletetime" IS NULL""",[sessionrow["userid"],userrow["id"]],SETTING["dbsetting"])
	if staffrow:
		return True
	return False

def hastimerstructurepermission(sessionrow,userrow):
	if not userrow:
		return False
	if sessionrow["userid"]==userrow["id"]:
		return True
	if 4<=int(userrow["permission"]):
		return True
	staffrow=query(SETTING["dbname"],f"""SELECT*FROM "sessionstaff" WHERE "sessionid"=%s AND "staffuserid"=%s AND "role"='assistant' AND "status"='active' AND "deletetime" IS NULL""",[sessionrow["id"],userrow["id"]],SETTING["dbsetting"])
	if staffrow:
		return True
	staffrow=query(SETTING["dbname"],f"""SELECT*FROM "userstaff" WHERE "userid"=%s AND "staffuserid"=%s AND "role"='assistant' AND "status"='active' AND "deletetime" IS NULL""",[sessionrow["userid"],userrow["id"]],SETTING["dbsetting"])
	if staffrow:
		return True
	return False

def broadcasttimerupdate(sessionid,state):
	try:
		layer=get_channel_layer()
		if layer:
			async_to_sync(layer.group_send)("timer_"+str(sessionid),{
				"type": "timer.update",
				"state": state
			})
	except Exception as error:
		printcolorhaveline("fail","[ERROR] broadcasttimerupdate "+str(error),"")

def getconfirmedregistrations(sessionid):
	row=query(SETTING["dbname"],
		f"""SELECT sp.*, u."name" AS playername, u."playerid" AS playerplayerid
		   FROM "sessionplayer" sp
		   JOIN "user" u ON u."id"=sp."userid"
		   WHERE sp."sessionid"=%s AND sp."status" IN ('confirmed','advanced') AND sp."deletetime" IS NULL
		   ORDER BY sp."confirmtime" ASC, sp."registertime" ASC, sp."id" ASC""",
		[sessionid],
		SETTING["dbsetting"]
	)
	return row or []

def synctimerplayers(sessionrow):
	if not boolval(sessionrow.get("linkuser")):
		return
	registrations=getconfirmedregistrations(sessionrow["id"])
	existingrow=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerplayer" WHERE "sessionid"=%s""",[sessionrow["id"]],SETTING["dbsetting"])
	existing={}
	for i in range(len(existingrow or [])):
		existing[existingrow[i]["sessionplayerid"]]=existingrow[i]
	updateids=[]
	insertrows=[]
	for item in registrations:
		row=existing.get(item["id"])
		if row:
			updateids.append(row["id"])
		else:
			insertrows.append({
				"sessionid": sessionrow["id"],
				"sessionplayerid": item["id"],
				"userid": item["userid"],
				"status": "active"
			})
	if updateids:
		placeholders=",".join(["%s"]*len(updateids))
		query(SETTING["dbname"],f"""UPDATE "sessiontimerplayer" SET "deletetime"=NULL,"updatetime"=NOW() WHERE "id" IN ({placeholders})""",updateids,SETTING["dbsetting"])
	if insertrows:
		queryinsert(SETTING["dbname"],"sessiontimerplayer",insertrows,SETTING["dbsetting"])
	query(SETTING["dbname"],
		f"""UPDATE "sessionplayer" sp
		   SET "tableid"=NULL,"seatno"=NULL,"updatetime"=NOW()
		   FROM "sessiontimerplayer" tp
		   WHERE tp."sessionplayerid"=sp."id"
		     AND tp."sessionid"=%s
		     AND tp."status"='eliminated'
		     AND tp."deletetime" IS NULL
		     AND sp."deletetime" IS NULL
		     AND (sp."tableid" IS NOT NULL OR sp."seatno" IS NOT NULL)""",
		[sessionrow["id"]],
		SETTING["dbsetting"]
	)

def gettimerplayerrows(sessionid):
	row=query(SETTING["dbname"],
		f"""SELECT tp.*, sp."status" AS registrationstatus, sp."tableid", sp."seatno",
		          sp."serialno", sp."registertime", sp."confirmtime",
		          sp."rebuycount", sp."reentrycount", sp."advancechip",
		          u."name" AS playername, u."playerid" AS playerplayerid,
		          u."avatarurl" AS playeravatarurl,
		          t."no" AS tablename, t."token" AS tabletoken
		   FROM "sessiontimerplayer" tp
		   JOIN "sessionplayer" sp ON sp."id"=tp."sessionplayerid"
		   JOIN "user" u ON u."id"=tp."userid"
		   LEFT JOIN "table" t ON t."id"=sp."tableid" AND t."deletetime" IS NULL
		   WHERE tp."sessionid"=%s AND tp."deletetime" IS NULL AND sp."status" IN ('confirmed','advanced') AND sp."deletetime" IS NULL
		   ORDER BY tp."status" ASC, t."no" ASC, sp."seatno" ASC, sp."serialno" ASC, tp."id" ASC""",
		[sessionid],
		SETTING["dbsetting"]
	)
	return row or []

def serializetimerplayers(row):
	data=[]
	for i in range(len(row)):
		item={}
		for key in row[i]:
			value=row[i][key]
			if "time" in key and value is not None:
				item[key]=str(value)
			elif isinstance(value,Decimal):
				if value==value.to_integral_value():
					item[key]=int(value)
				else:
					item[key]=float(value)
			else:
				item[key]=value
		data.append(item)
	return data

def linkedcounts(sessionid):
	row=gettimerplayerrows(sessionid)
	total=0
	active=0
	for i in range(len(row)):
		total=total+1+intval(row[i].get("rebuycount"),0)+intval(row[i].get("reentrycount"),0)
		if row[i]["status"]=="active" and row[i].get("registrationstatus")!="advanced":
			active=active+1
	return (active,total,row)

def finalizetimerpendingplaces(sessionid,totalentries):
	row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerplayer" WHERE "sessionid"=%s AND "status"='eliminated' AND "deletetime" IS NULL ORDER BY "eliminatedtime" ASC, "id" ASC""",[sessionid],SETTING["dbsetting"])
	for i in range(len(row or [])):
		if row[i]["place"] is None:
			place=totalentries-i
			query(SETTING["dbname"],f"""UPDATE "sessiontimerplayer" SET "place"=%s,"updatetime"=NOW() WHERE "id"=%s""",[place,row[i]["id"]],SETTING["dbsetting"])

def timerregclosed(sessionid):
	row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimer" WHERE "sessionid"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
	if not row:
		return False
	stateval=normalizetimerstate(row[0]["state"])
	return boolval(stateval.get("regClosed"))

def multidaycarryover(sessionid):
	try:
		from .sessionplayer import _multidaycarryover
		return _multidaycarryover(sessionid)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] multidaycarryover "+str(error),"")
	return 0

def multidayremaining(sessionid):
	try:
		from .session import _multidayremainingcount
		return _multidayremainingcount(sessionid)
	except Exception as error:
		printcolorhaveline("fail","[ERROR] multidayremaining "+str(error),"")
	return 0

def hasmultidayrelation(sessionid):
	row=query(SETTING["dbname"],f"""
		SELECT COUNT(*) AS count
		FROM "sessionrelation"
		WHERE "relationtype"='multiday' AND "deletetime" IS NULL
		  AND ("sourceid"=%s OR "targetid"=%s)
	""",[sessionid,sessionid],SETTING["dbsetting"])
	if row and row[0].get("count") is not None:
		return 0<intval(row[0].get("count"),0)
	return False

def defaultconfig(sessionrow,players,totalentries):
	return {
		"tournName": sessionrow["name"] or "Poker Tournament",
		"subtitle": "",
		"startingChips": intval(sessionrow.get("chip"),40000),
		"buyin": intval(sessionrow.get("buyin"),0),
		"fee": intval(sessionrow.get("buyinfee"),0),
		"defaultBreakDur": 10,
		"soundOn": True,
		"vibeOn": True,
		"prizePoolMode": "auto",
		"prizePoolManual": intval(sessionrow.get("buyin"),0)*totalentries,
		"prizePoolCarryover": intval(multidaycarryover(sessionrow["id"]),0),
		"guaranteedPrize": intval(sessionrow.get("guaranteedprize"),0),
		"itmMode": "pct",
		"itmPct": 15,
		"itmCount": 7,
		"marqueeText": DEFAULTMARQUEE,
		"autoStartByTime": False
	}

def legacytimerstate(sessionid):
	row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimer" WHERE "sessionid"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
	if row:
		return normalizetimerstate(row[0]["state"])
	return {}

def defaultstate(sessionrow):
	players=52
	totalentries=52
	if boolval(sessionrow.get("linkuser")):
		synctimerplayers(sessionrow)
		counts=linkedcounts(sessionrow["id"])
		players=counts[0]
		totalentries=counts[1]
	return {
		"currentIndex": 0,
		"secondsLeft": DEFAULTSCHEDULE[0]["dur"]*60,
		"anchorSecondsLeft": DEFAULTSCHEDULE[0]["dur"]*60,
		"anchorTime": nowtime(),
		"running": False,
		"players": players,
		"totalEntries": totalentries,
		"regClosed": False,
		"handForHand": False,
		"bubbleMode": False,
		"playerMode": "linked" if boolval(sessionrow.get("linkuser")) else "manual",
		"lastSyncTime": nowtime()
	}

def readconfig(sessionrow,players,totalentries):
	row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerconfig" WHERE "sessionid"=%s AND "deletetime" IS NULL""",[sessionrow["id"]],SETTING["dbsetting"])
	if not row:
		config=defaultconfig(sessionrow,players,totalentries)
		legacy=legacytimerstate(sessionrow["id"])
		for key in config:
			if key in legacy:
				config[key]=legacy[key]
		queryinsert(SETTING["dbname"],"sessiontimerconfig",{
			"sessionid": sessionrow["id"],
			"tournname": config["tournName"],
			"subtitle": config["subtitle"],
			"startingchips": config["startingChips"],
			"buyin": config["buyin"],
			"fee": config["fee"],
			"defaultbreakdur": config["defaultBreakDur"],
			"soundon": config["soundOn"],
			"vibeon": config["vibeOn"],
			"prizepoolmode": config["prizePoolMode"],
			"prizepoolmanual": config["prizePoolManual"],
			"itmmode": config["itmMode"],
			"itmpct": config["itmPct"],
			"itmcount": config["itmCount"],
			"marqueetext": config["marqueeText"],
			"autostartbytime": boolval(config.get("autoStartByTime"))
		},SETTING["dbsetting"])
		return config
	row=row[0]
	return {
		"tournName": row["tournname"],
		"subtitle": row["subtitle"],
		"startingChips": intval(row["startingchips"],40000),
		"buyin": intval(sessionrow.get("buyin"),0),
		"fee": intval(sessionrow.get("buyinfee"),0),
		"defaultBreakDur": intval(row["defaultbreakdur"],10),
		"soundOn": boolval(row["soundon"]),
		"vibeOn": boolval(row["vibeon"]),
		"prizePoolMode": row["prizepoolmode"],
		"prizePoolManual": intval(row["prizepoolmanual"],0),
		"prizePoolCarryover": intval(multidaycarryover(sessionrow["id"]),0),
		"guaranteedPrize": intval(sessionrow.get("guaranteedprize"),0),
		"itmMode": row["itmmode"],
		"itmPct": floatval(row["itmpct"],15),
		"itmCount": intval(row["itmcount"],7),
		"marqueeText": row["marqueetext"],
		"autoStartByTime": boolval(row.get("autostartbytime"))
	}

def readlevels(sessionid):
	row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerlevel" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC""",[sessionid],SETTING["dbsetting"])
	if not row:
		legacy=legacytimerstate(sessionid)
		if "schedule" in legacy and isinstance(legacy["schedule"],list) and 0<len(legacy["schedule"]):
			for i in range(len(legacy["schedule"])):
				item=legacy["schedule"][i]
				queryinsert(SETTING["dbname"],"sessiontimerlevel",{
					"sessionid": sessionid,
					"sortorder": i,
					"type": item.get("type") or "level",
					"smallblind": intval(item.get("sb"),0),
					"bigblind": intval(item.get("bb"),0),
					"ante": intval(item.get("ante"),0),
					"durationminutes": intval(item.get("dur"),20),
					"regcloseafter": boolval(item.get("regCloseAfter"))
				},SETTING["dbsetting"])
			row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerlevel" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC""",[sessionid],SETTING["dbsetting"])
		if row:
			pass
		else:
			tablerow=[]
			if tablerow:
				for i in range(len(tablerow)):
					queryinsert(SETTING["dbname"],"sessiontimerlevel",{
						"sessionid": sessionid,
						"sortorder": i,
						"type": "level",
						"smallblind": intval(tablerow[i].get("smallblind"),0),
						"bigblind": intval(tablerow[i].get("bigblind"),0),
						"ante": intval(tablerow[i].get("bigblindante"),0),
						"durationminutes": 20,
						"regcloseafter": False
					},SETTING["dbsetting"])
			else:
				for i in range(len(DEFAULTSCHEDULE)):
					item=DEFAULTSCHEDULE[i]
					queryinsert(SETTING["dbname"],"sessiontimerlevel",{
						"sessionid": sessionid,
						"sortorder": i,
						"type": item["type"],
						"smallblind": item["sb"] if "sb" in item else 0,
						"bigblind": item["bb"] if "bb" in item else 0,
						"ante": item["ante"] if "ante" in item else 0,
						"durationminutes": item["dur"],
						"regcloseafter": item["regCloseAfter"] if "regCloseAfter" in item else False
					},SETTING["dbsetting"])
			row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerlevel" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC""",[sessionid],SETTING["dbsetting"])
	schedule=[]
	for i in range(len(row or [])):
		item={
			"type": row[i]["type"],
			"dur": intval(row[i]["durationminutes"],20)
		}
		if row[i]["type"]=="level":
			item["sb"]=intval(row[i]["smallblind"],0)
			item["bb"]=intval(row[i]["bigblind"],0)
			item["ante"]=intval(row[i]["ante"],0)
			item["timemode"]=row[i].get("timemode") or "time"
			item["handTargetCount"]=intval(row[i].get("handtargetcount"),0)
			item["handCount"]=intval(row[i].get("handcount"),0)
		if boolval(row[i]["regcloseafter"]):
			item["regCloseAfter"]=True
		try:
			item["chipRaiseValues"]=json.loads(row[i].get("chipraisevalues") or "[]")
		except Exception as error:
			item["chipRaiseValues"]=[]
		schedule.append(item)
	return schedule

def readpayouts(sessionid):
	row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerpayout" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC""",[sessionid],SETTING["dbsetting"])
	if not row:
		legacy=legacytimerstate(sessionid)
		payoutsource=DEFAULTPAYOUTS
		if "payouts" in legacy and isinstance(legacy["payouts"],list) and 0<len(legacy["payouts"]):
			payoutsource=legacy["payouts"]
		for i in range(len(payoutsource)):
			queryinsert(SETTING["dbname"],"sessiontimerpayout",{
				"sessionid": sessionid,
				"sortorder": i,
				"rank": payoutsource[i]["rank"],
				"pct": payoutsource[i]["pct"],
				"reward": payoutsource[i].get("reward") or "",
				"color": payoutsource[i]["color"]
			},SETTING["dbsetting"])
		row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerpayout" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC""",[sessionid],SETTING["dbsetting"])
	payouts=[]
	for i in range(len(row or [])):
		payouts.append({
			"rank": row[i]["rank"],
			"pct": floatval(row[i]["pct"],0),
			"reward": row[i]["reward"] if "reward" in row[i] else "",
			"color": row[i]["color"]
		})
	return payouts

def readsessionchips(sessionid):
	row=query(SETTING["dbname"],f"""SELECT "shape","value","color","sortorder" FROM "sessionchip" WHERE "sessionid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC,"value" ASC""",[sessionid],SETTING["dbsetting"])
	if row:
		return row
	return [
		{"shape": "circle","value": 100,"color": "#ffffff","sortorder": 1},
		{"shape": "circle","value": 500,"color": "#ef4444","sortorder": 2},
		{"shape": "circle","value": 1000,"color": "#f59e0b","sortorder": 3},
		{"shape": "circle","value": 5000,"color": "#22c55e","sortorder": 4},
		{"shape": "circle","value": 10000,"color": "#3b82f6","sortorder": 5}
	]

def applyautostartbytime(sessionrow,runtime,schedule,autostarted):
	if not autostarted or not schedule:
		return runtime
	if boolval(runtime.get("running")) or boolval(runtime.get("autoStartTriggered")):
		return runtime
	starttime=parsetimervalue(sessionrow.get("starttime"))
	if not starttime:
		return runtime
	now=datetime.datetime.now()
	if now<starttime:
		return runtime
	index=normalizeindex(runtime.get("currentIndex"),schedule)
	runtime["currentIndex"]=index
	runtime["anchorSecondsLeft"]=intval(runtime.get("secondsLeft"),timerseconds(schedule[index]))
	runtime["anchorTime"]=str(sessionrow.get("starttime"))
	runtime["running"]=True
	runtime["autoStartTriggered"]=True
	return runtime

def readruntime(sessionrow,players,totalentries,schedule,autostarted):
	row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimer" WHERE "sessionid"=%s AND "deletetime" IS NULL""",[sessionrow["id"]],SETTING["dbsetting"])
	if not row:
		runtime=defaultstate(sessionrow)
		runtime=applyautostartbytime(sessionrow,runtime,schedule,autostarted)
		runtime=advanceruntime(runtime,schedule)
		queryinsert(SETTING["dbname"],"sessiontimer",{
			"sessionid": sessionrow["id"],
			"state": json.dumps(runtime)
		},SETTING["dbsetting"])
		return runtime
	runtime=normalizetimerstate(row[0]["state"])
	runtime=applyautostartbytime(sessionrow,runtime,schedule,autostarted)
	runtime=advanceruntime(runtime,schedule)
	if boolval(sessionrow.get("linkuser")):
		runtime["players"]=players
		runtime["totalEntries"]=totalentries
		runtime["playerMode"]="linked"
	else:
		runtime["playerMode"]="manual"
		if "players" not in runtime:
			runtime["players"]=players
		if "totalEntries" not in runtime:
			runtime["totalEntries"]=totalentries
	if "lastSyncTime" not in runtime:
		runtime["lastSyncTime"]=str(row[0]["updatetime"])
	query(SETTING["dbname"],f"""UPDATE "sessiontimer" SET "state"=%s::jsonb, "updatetime"=NOW(), "deletetime"=NULL WHERE "sessionid"=%s""",[json.dumps(runtime),sessionrow["id"]],SETTING["dbsetting"])
	return runtime

def buildtimerstate(sessionid):
	ensuretimertables()
	sessionrow=query(SETTING["dbname"],f"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
	if not sessionrow:
		return None
	sessionrow=sessionrow[0]
	if boolval(sessionrow.get("linkuser")):
		synctimerplayers(sessionrow)
		counts=linkedcounts(sessionid)
		players=counts[0]
		totalentries=counts[1]
		playerlist=serializetimerplayers(counts[2])
	else:
		players=0
		totalentries=0
		playerlist=[]
	config=readconfig(sessionrow,players,totalentries)
	schedule=readlevels(sessionid)
	payouts=readpayouts(sessionid)
	runtime=readruntime(sessionrow,players,totalentries,schedule,boolval(config.get("autoStartByTime")))
	if boolval(sessionrow.get("linkuser")) and boolval(runtime.get("regClosed")):
		finalizetimerpendingplaces(sessionid,totalentries)
		counts=linkedcounts(sessionid)
		players=counts[0]
		totalentries=counts[1]
		playerlist=serializetimerplayers(counts[2])
	state={}
	state.update(config)
	state.update(runtime)
	state["schedule"]=schedule
	state["payouts"]=payouts
	state["chips"]=readsessionchips(sessionid)
	state["linkedPlayers"]=playerlist
	state["playerMode"]="linked" if boolval(sessionrow.get("linkuser")) else "manual"
	state["showMultidayRemaining"]=hasmultidayrelation(sessionid)
	state["multidayRemaining"]=multidayremaining(sessionid)
	if boolval(sessionrow.get("linkuser")):
		state["players"]=players
		state["totalEntries"]=totalentries
	return state

def savesplitstate(sessionrow,stateval):
	ensuretimertables()
	if boolval(sessionrow.get("linkuser")):
		synctimerplayers(sessionrow)
		counts=linkedcounts(sessionrow["id"])
		stateval["players"]=counts[0]
		stateval["totalEntries"]=counts[1]
		stateval["playerMode"]="linked"
	else:
		stateval["playerMode"]="manual"
	configrow=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerconfig" WHERE "sessionid"=%s""",[sessionrow["id"]],SETTING["dbsetting"])
	configdata={
		"tournname": stateval.get("tournName") or sessionrow["name"],
		"subtitle": stateval.get("subtitle") or "",
		"startingchips": intval(stateval.get("startingChips"),40000),
		"buyin": intval(sessionrow.get("buyin"),0),
		"fee": intval(sessionrow.get("buyinfee"),0),
		"defaultbreakdur": intval(stateval.get("defaultBreakDur"),10),
		"soundon": boolval(stateval.get("soundOn")),
		"vibeon": boolval(stateval.get("vibeOn")),
		"prizepoolmode": stateval.get("prizePoolMode") or "auto",
		"prizepoolmanual": intval(stateval.get("prizePoolManual"),0),
		"itmmode": stateval.get("itmMode") or "pct",
		"itmpct": floatval(stateval.get("itmPct"),15),
		"itmcount": intval(stateval.get("itmCount"),7),
		"marqueetext": stateval.get("marqueeText") or "",
		"autostartbytime": boolval(stateval.get("autoStartByTime")),
		"updatetime": nowtime(),
		"deletetime": None
	}
	if configrow:
		queryupdate(SETTING["dbname"],"sessiontimerconfig",configdata,{"sessionid": sessionrow["id"]},SETTING["dbsetting"])
	else:
		configdata["sessionid"]=sessionrow["id"]
		queryinsert(SETTING["dbname"],"sessiontimerconfig",configdata,SETTING["dbsetting"])
	query(SETTING["dbname"],f"""UPDATE "sessiontimerlevel" SET "deletetime"=NOW() WHERE "sessionid"=%s""",[sessionrow["id"]],SETTING["dbsetting"])
	schedule=stateval.get("schedule") or []
	for i in range(len(schedule)):
		item=schedule[i]
		queryinsert(SETTING["dbname"],"sessiontimerlevel",{
			"sessionid": sessionrow["id"],
			"sortorder": i,
			"type": item.get("type") or "level",
			"smallblind": intval(item.get("sb"),0),
			"bigblind": intval(item.get("bb"),0),
			"ante": intval(item.get("ante"),0),
			"durationminutes": intval(item.get("dur"),20),
			"timemode": item.get("timemode") or "time",
			"handtargetcount": intval(item.get("handTargetCount"),0),
			"handcount": intval(item.get("handCount"),0),
			"regcloseafter": boolval(item.get("regCloseAfter")),
			"chipraisevalues": json.dumps((item.get("chipRaiseValues") or [])[:3])
		},SETTING["dbsetting"])
	query(SETTING["dbname"],f"""UPDATE "sessiontimerpayout" SET "deletetime"=NOW() WHERE "sessionid"=%s""",[sessionrow["id"]],SETTING["dbsetting"])
	payouts=stateval.get("payouts") or []
	for i in range(len(payouts)):
		item=payouts[i]
		queryinsert(SETTING["dbname"],"sessiontimerpayout",{
			"sessionid": sessionrow["id"],
			"sortorder": i,
			"rank": item.get("rank") or "",
			"pct": floatval(item.get("pct"),0),
			"reward": item.get("reward") or "",
			"color": item.get("color") or "#888"
		},SETTING["dbsetting"])
	runtime={
		"currentIndex": intval(stateval.get("currentIndex"),0),
		"secondsLeft": intval(stateval.get("secondsLeft"),0),
		"anchorSecondsLeft": intval(stateval.get("secondsLeft"),0),
		"anchorTime": nowtime(),
		"running": boolval(stateval.get("running")),
		"players": intval(stateval.get("players"),0),
		"totalEntries": intval(stateval.get("totalEntries"),0),
		"regClosed": boolval(stateval.get("regClosed")),
		"regCloseHandled": boolval(stateval.get("regCloseHandled")) or boolval(stateval.get("regClosed")),
		"handForHand": boolval(stateval.get("handForHand")),
		"bubbleMode": boolval(stateval.get("bubbleMode")),
		"playerMode": stateval.get("playerMode") or "manual",
		"autoStartTriggered": boolval(stateval.get("autoStartTriggered")),
		"lastSyncTime": nowtime()
	}
	runtime=saveregclosedbyindex(runtime,stateval.get("schedule") or [])
	if boolval(sessionrow.get("linkuser")) and boolval(runtime.get("regClosed")):
		finalizetimerpendingplaces(sessionrow["id"],intval(stateval.get("totalEntries"),0))
	timerrow=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimer" WHERE "sessionid"=%s""",[sessionrow["id"]],SETTING["dbsetting"])
	if timerrow:
		query(SETTING["dbname"],f"""UPDATE "sessiontimer" SET "state"=%s::jsonb, "updatetime"=NOW(), "deletetime"=NULL WHERE "sessionid"=%s""",[json.dumps(runtime),sessionrow["id"]],SETTING["dbsetting"])
	else:
		queryinsert(SETTING["dbname"],"sessiontimer",{
			"sessionid": sessionrow["id"],
			"state": json.dumps(runtime)
		},SETTING["dbsetting"])

try:
	@api_view(["GET"])
	def gettimer(request,sessionid):
		state=buildtimerstate(sessionid)
		if state is None:
			return errorresponse("ERROR_session_not_found")
		return Response({
			"success": True,
			"data": {
				"sessionid": sessionid,
				"state": state,
				"updatetime": state.get("lastSyncTime")
			}
		},status.HTTP_200_OK)

	@api_view(["PUT"])
	def savetimer(request,sessionid):
		userrow,errresp=gettimerpermissionuser(request)
		if errresp:
			return errresp
		sessionrow=query(SETTING["dbname"],f"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
		if not sessionrow:
			return errorresponse("ERROR_session_not_found")
		sessionrow=sessionrow[0]
		if not hastimercontrolpermission(sessionrow,userrow):
			return errorresponse("ERROR_no_permission")
		try:
			data=json.loads(request.body)
		except Exception as error:
			return errorresponse("ERROR_request_data_not_found")
		stateval=data.get("state")
		if stateval is None:
			return errorresponse("ERROR_request_data_not_found")
		action=data.get("action") or ""
		if action=="struct-edit" and not hastimerstructurepermission(sessionrow,userrow):
			return errorresponse("ERROR_no_permission")
		stateval=normalizetimerstate(stateval)
		
		# 判斷是否為局部更新: 如果只包含非時間相關欄位，則先讀完整 state 再合併
		fullstate=buildtimerstate(sessionid)
		if fullstate is None:
			return errorresponse("ERROR_session_not_found")
		recvfields=set(stateval.keys())
		fullfields=set(fullstate.keys())
		
		if action=="toggle":
			fullstate["running"]=boolval(stateval.get("running"))
			stateval=fullstate
		elif action=="item-change":
			stateval=fullstate
		elif action=="reset":
			oldstartingchips=intval(fullstate.get("startingChips"),intval(sessionrow.get("chip"),40000))
			oldbuyin=intval(fullstate.get("buyin"),intval(sessionrow.get("buyin"),0))
			oldfee=intval(fullstate.get("fee"),intval(sessionrow.get("buyinfee"),0))
			fullstate.update(stateval)
			fullstate["startingChips"]=oldstartingchips
			fullstate["buyin"]=oldbuyin
			fullstate["fee"]=oldfee
			stateval=fullstate
		elif recvfields!=fullfields:
			# 這是非時間相關的局部更新，需要先讀完整狀態再合併
			fullstate.update(stateval)
			stateval=fullstate
		
		savesplitstate(sessionrow,stateval)
		state=buildtimerstate(sessionid)
		broadcasttimerupdate(sessionid,state)
		return Response({
			"success": True,
			"data": state,
			"action": action
		},status.HTTP_200_OK)

	@api_view(["GET"])
	def gettimerplayers(request,sessionid):
		ensuretimertables()
		sessionrow=query(SETTING["dbname"],f"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
		if not sessionrow:
			return errorresponse("ERROR_session_not_found")
		sessionrow=sessionrow[0]
		if not boolval(sessionrow.get("linkuser")):
			return Response({"success": True,"data": []},status.HTTP_200_OK)
		synctimerplayers(sessionrow)
		return Response({"success": True,"data": serializetimerplayers(gettimerplayerrows(sessionid))},status.HTTP_200_OK)

	@api_view(["PUT"])
	def edittimerplayer(request,sessionid,timerplayerid):
		userrow,errresp=gettimerpermissionuser(request)
		if errresp:
			return errresp
		sessionrow=query(SETTING["dbname"],f"""SELECT*FROM "session" WHERE "id"=%s AND "deletetime" IS NULL""",[sessionid],SETTING["dbsetting"])
		if not sessionrow:
			return errorresponse("ERROR_session_not_found")
		sessionrow=sessionrow[0]
		if not hastimercontrolpermission(sessionrow,userrow):
			return errorresponse("ERROR_no_permission")
		try:
			data=json.loads(request.body)
		except Exception as error:
			return errorresponse("ERROR_request_data_not_found")
		action=data.get("action")
		row=query(SETTING["dbname"],f"""SELECT*FROM "sessiontimerplayer" WHERE "id"=%s AND "sessionid"=%s AND "deletetime" IS NULL""",[timerplayerid,sessionid],SETTING["dbsetting"])
		if not row:
			return errorresponse("ERROR_timer_player_not_found")
		row=row[0]
		if action=="eliminate":
			counts=linkedcounts(sessionid)
			place=None
			if timerregclosed(sessionid):
				finalizetimerpendingplaces(sessionid,counts[1])
				place=counts[0]
			query(SETTING["dbname"],f"""UPDATE "sessiontimerplayer" SET "status"='eliminated',"eliminatedtime"=NOW(),"place"=%s,"updatetime"=NOW() WHERE "id"=%s""",[place,timerplayerid],SETTING["dbsetting"])
			query(SETTING["dbname"],f"""UPDATE "sessionplayer" SET "tableid"=NULL,"seatno"=NULL,"updatetime"=NOW() WHERE "id"=%s""",[row["sessionplayerid"]],SETTING["dbsetting"])
		elif action=="restore":
			query(SETTING["dbname"],f"""UPDATE "sessiontimerplayer" SET "status"='active',"eliminatedtime"=NULL,"place"=NULL,"updatetime"=NOW() WHERE "id"=%s""",[timerplayerid],SETTING["dbsetting"])
		else:
			return errorresponse("ERROR_request_data_not_found")
		state=buildtimerstate(sessionid)
		savesplitstate(sessionrow,state)
		state=buildtimerstate(sessionid)
		broadcasttimerupdate(sessionid,state)
		return Response({"success": True,"data": state},status.HTTP_200_OK)
except Exception as error:
	printcolorhaveline("fail","[ERROR] "+str(error),"")
