# import
import bcrypt
import hashlib
import json
import random
import re
import threading
import urllib.request
import urllib.parse
# Google Identity Services (取代 firebase_admin.auth, 解決跨域 storage 問題)
from decimal import Decimal
from google.oauth2 import id_token
from google.auth.transport import requests as grequests
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.views.decorators.http import require_http_methods
# from firebase_admin import auth  # 已停用, 改 GIS
from rest_framework import status
from rest_framework.decorators import api_view,renderer_classes
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from django.core.mail import send_mail
from .authhelper import getuserbanned

# Google OAuth Web Client ID (跟 frontend signin.js 的 client_id 必須一致)
GOOGLE_CLIENT_ID="676058961600-uo2cec3c18kiuipfci2tet1l67c8dmbl.apps.googleusercontent.com"
GOOGLE_CLOCK_SKEW_SECONDS=30

# 自創
from function.validation import *
from function.sql import *
from function.thing import *
from function.function import *
from .initialize import *
from .sessionplayer import _attachfinance

# main START

def async_send_mail(*args,**kwargs):
	threading.Thread(target=send_mail,args=args,kwargs=kwargs).start()

def defaultchipcolors():
	return [
		{"name": "白色","color": "#ffffff"},
		{"name": "紅色","color": "#ff0000"},
		{"name": "藍色","color": "#0000ff"},
		{"name": "綠色","color": "#008000"},
		{"name": "黑色","color": "#000000"},
		{"name": "黃色","color": "#ffff00"},
		{"name": "橘色","color": "#ffa500"},
		{"name": "紫色","color": "#800080"},
		{"name": "粉紅色","color": "#ffc0cb"},
		{"name": "灰色","color": "#808080"}
	]

def parsechipcolors(value):
	try:
		row=json.loads(value or "[]")
		if isinstance(row,list) and len(row)>0:
			return row
	except Exception as error:
		pass
	return defaultchipcolors()

def defaultchipset():
	return [
		{
			"name": "T100 Base",
			"chips": [
				{"shape": "circle","value": 100,"color": "#ffffff"},
				{"shape": "circle","value": 500,"color": "#ef4444"},
				{"shape": "circle","value": 1000,"color": "#f59e0b"},
				{"shape": "circle","value": 5000,"color": "#22c55e"},
				{"shape": "circle","value": 10000,"color": "#3b82f6"}
			]
		}
	]

def loaduserchipset(userid):
	# 從 userchipset/userchipsetchip 讀回前端要的 [{name,chips:[{shape,value,color}]}] 形狀。
	# 沒有任何組合時回傳預設組 (不落地, 與舊 parsechipsets 行為一致)。
	ensureuserchipsettables()
	setrows=query(SETTING["dbname"],f"""SELECT "id","name" FROM "userchipset" WHERE "userid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC,"id" ASC""",[userid],SETTING["dbsetting"])
	if not setrows:
		return defaultchipset()
	output=[]
	for srow in setrows:
		chiprows=query(SETTING["dbname"],f"""SELECT "shape","value","color" FROM "userchipsetchip" WHERE "chipsetid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC,"value" ASC,"id" ASC""",[srow["id"]],SETTING["dbsetting"])
		chips=[]
		for crow in (chiprows or []):
			chips.append({
				"shape": crow["shape"],
				"value": int(crow["value"]),
				"color": crow["color"]
			})
		output.append({
			"name": srow["name"],
			"chips": chips
		})
	return output

def saveuserchipset(userid,sets):
	# 全量覆寫: 先軟刪除既有組合與其計分牌, 再插入新的 (sets 已驗證好的 [{name,chips}] 結構)。
	ensureuserchipsettables()
	query(SETTING["dbname"],f"""UPDATE "userchipsetchip" SET "deletetime"=NOW(),"updatetime"=NOW() WHERE "chipsetid" IN (SELECT "id" FROM "userchipset" WHERE "userid"=%s) AND "deletetime" IS NULL""",[userid],SETTING["dbsetting"])
	query(SETTING["dbname"],f"""UPDATE "userchipset" SET "deletetime"=NOW(),"updatetime"=NOW() WHERE "userid"=%s AND "deletetime" IS NULL""",[userid],SETTING["dbsetting"])
	for i in range(len(sets or [])):
		item=sets[i]
		chipsetid=queryinsert(SETTING["dbname"],"userchipset",{
			"userid": userid,
			"name": item["name"],
			"sortorder": i+1
		},SETTING["dbsetting"])
		chips=item.get("chips") or []
		for j in range(len(chips)):
			chip=chips[j]
			queryinsert(SETTING["dbname"],"userchipsetchip",{
				"chipsetid": chipsetid,
				"shape": chip["shape"],
				"value": chip["value"],
				"color": chip["color"],
				"sortorder": j+1
			},SETTING["dbsetting"])

def parsetoolfavorites(value):
	try:
		row=json.loads(value or "[]")
		if isinstance(row,list):
			output=[]
			for i in range(len(row)):
				item=str(row[i] or "").strip()
				if re.match(r"^(tool/[a-z0-9]+\.html|gto\.html|flopsolver\.html)$",item):
					if item not in output:
						output.append(item)
			return output
	except Exception as error:
		pass
	return []

def ensureuserchipsettables():
	query(SETTING["dbname"],"""CREATE TABLE IF NOT EXISTS "userchipset"(
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		userid bigint NOT NULL,
		name varchar(30) NOT NULL DEFAULT '',
		sortorder integer NOT NULL DEFAULT 0,
		createtime timestamp with time zone NOT NULL DEFAULT now(),
		updatetime timestamp with time zone NOT NULL DEFAULT now(),
		deletetime timestamp with time zone
	)""",[],SETTING["dbsetting"])
	query(SETTING["dbname"],"""CREATE TABLE IF NOT EXISTS "userchipsetchip"(
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		chipsetid bigint NOT NULL,
		shape varchar(20) NOT NULL DEFAULT 'circle',
		value bigint NOT NULL DEFAULT 0,
		color varchar(20) NOT NULL DEFAULT '#888888',
		sortorder integer NOT NULL DEFAULT 0,
		createtime timestamp with time zone NOT NULL DEFAULT now(),
		updatetime timestamp with time zone NOT NULL DEFAULT now(),
		deletetime timestamp with time zone
	)""",[],SETTING["dbsetting"])

def ensureusertoolfavoritetable():
	query(SETTING["dbname"],"""CREATE TABLE IF NOT EXISTS "usertoolfavorite"(
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		userid bigint NOT NULL,
		tool varchar(100) NOT NULL DEFAULT '',
		sortorder integer NOT NULL DEFAULT 0,
		createtime timestamp with time zone NOT NULL DEFAULT now(),
		updatetime timestamp with time zone NOT NULL DEFAULT now(),
		deletetime timestamp with time zone
	)""",[],SETTING["dbsetting"])

def loadusertoolfavorite(userid):
	# 從 usertoolfavorite 讀回工具路徑陣列 (依 sortorder)。
	ensureusertoolfavoritetable()
	rows=query(SETTING["dbname"],f"""SELECT "tool" FROM "usertoolfavorite" WHERE "userid"=%s AND "deletetime" IS NULL ORDER BY "sortorder" ASC,"id" ASC""",[userid],SETTING["dbsetting"])
	output=[]
	for row in (rows or []):
		tool=row["tool"]
		if tool not in output:
			output.append(tool)
	return output

def saveusertoolfavorite(userid,favorites):
	# 全量覆寫: 先軟刪除既有最愛, 再插入新的 (favorites 已經過 parsetoolfavorites 驗證/去重)。
	ensureusertoolfavoritetable()
	query(SETTING["dbname"],f"""UPDATE "usertoolfavorite" SET "deletetime"=NOW(),"updatetime"=NOW() WHERE "userid"=%s AND "deletetime" IS NULL""",[userid],SETTING["dbsetting"])
	for i in range(len(favorites or [])):
		queryinsert(SETTING["dbname"],"usertoolfavorite",{
			"userid": userid,
			"tool": favorites[i],
			"sortorder": i+1
		},SETTING["dbsetting"])

@api_view(["POST"])
def signin(request):
	try:
		data=json.loads(request.body)
		idtoken=data.get("idtoken")
		accesstoken=data.get("accesstoken")

		if accesstoken:
			# OAuth 隱式流程: 前端用 google.accounts.oauth2 popup 取得 access token
			# (Safari/ITP 友善, popup 由使用者點擊同步開啟, 不依賴第三方 cookie)。
			# 先用 tokeninfo 確認此 token 確實是發給「我們的 client」, 避免 token 替換攻擊,
			# 再用 userinfo 取得使用者資料。
			tokeninfourl="https://oauth2.googleapis.com/tokeninfo?"+urllib.parse.urlencode({"access_token":accesstoken})
			with urllib.request.urlopen(tokeninfourl,timeout=10) as resp:
				tokeninfo=json.loads(resp.read().decode("utf-8"))

			if tokeninfo.get("aud")!=GOOGLE_CLIENT_ID and tokeninfo.get("azp")!=GOOGLE_CLIENT_ID:
				return errorresponse("ERROR_signin_error")

			userinforeq=urllib.request.Request(
				"https://www.googleapis.com/oauth2/v3/userinfo",
				headers={"Authorization":"Bearer "+accesstoken}
			)
			with urllib.request.urlopen(userinforeq,timeout=10) as resp:
				userinfo=json.loads(resp.read().decode("utf-8"))

			uid=userinfo.get("sub")
			email=userinfo.get("email")
			name=userinfo.get("name")
			picture=userinfo.get("picture")
		else:
			# 驗證 Google ID Token (GIS), 返回 decoded payload (官方按鈕保底流程)
			decodedtoken=id_token.verify_oauth2_token(
				idtoken,
				grequests.Request(),
				GOOGLE_CLIENT_ID,
				clock_skew_in_seconds=GOOGLE_CLOCK_SKEW_SECONDS
			)

			# Google id_token 的欄位:
			#   sub      = Google 帳號的 unique user id (對應原本 Firebase 的 uid)
			#   email    = 信箱
			#   name     = 顯示名稱
			#   picture  = 頭像 URL
			uid=decodedtoken.get("sub")
			email=decodedtoken.get("email")
			name=decodedtoken.get("name")
			picture=decodedtoken.get("picture")

		signup=False

		# 先用 uid 找 (新註冊或已遷移過的使用者)
		row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "uid"=%s AND "deletetime" IS NULL""",[uid],SETTING["dbsetting"])

		if not row:
			# 遷移處理: 原本 Firebase 使用者的 uid 是 Firebase uid (不是 Google sub)
			# 用 email 找看看, 找到就把 uid 更新為 Google sub
			emailrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "email"=%s AND "deletetime" IS NULL""",[email],SETTING["dbsetting"])
			if emailrow:
				query(SETTING["dbname"],f"""UPDATE "user" SET "uid"=%s,"updatetime"=%s WHERE "id"=%s""",[uid,nowtime(),emailrow[0]["id"]],SETTING["dbsetting"])
				row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[emailrow[0]["id"]],SETTING["dbsetting"])

		if not row:
			signup=True
			while True:
				# 產生 8 碼隨機數字
				playerid=str(random.randint(10000000,99999999))

				# 判斷是否「沒有」在裡面 (檢查 playerid 唯一性)
				if not query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "playerid"=%s""",[playerid],SETTING["dbsetting"]):
					break

			# type 留空字串, signup 流程完成才會寫入實際類型
			query(SETTING["dbname"],f"""INSERT INTO "user"("token","uid","name","email","avatarurl","permission","verifytoken","createtime","playerid","type")VALUES(gen_random_uuid(),%s,%s,%s,%s,%s,%s,%s,%s,%s)""",[uid,name,email,picture,"1","0",nowtime(),playerid,""],SETTING["dbsetting"])
			row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "uid"=%s AND "deletetime" IS NULL""",[uid],SETTING["dbsetting"])
		else:
			# 已存在但 type 還沒設定 → 視同需要 signup
			if not row[0]["type"]:
				signup=True

		# 封禁檢查：必須在發新 token 之前擋掉，否則被封禁者重新登入就能拿到全新可用的 token，
		# 封禁當下撤銷舊 token 的動作等於白做。
		if getuserbanned(row[0]["id"]):
			return errorresponse("ERROR_no_permission")

		token=randomtext()

		query(SETTING["dbname"],f"""INSERT INTO "token"("userid","token","createtime")VALUES(%s,%s,%s)""",[row[0]["id"],token,nowtime()],SETTING["dbsetting"])

		# 稽核：使用者登入（供後台 admin.html 追蹤帳號存取狀況）
		writeauditlog(SETTING["dbname"],SETTING["dbsetting"],row[0]["id"],"user","signin",row[0]["id"],None,None,request)

		return Response({
			"success": True,
			"data": {
				"signup": signup,
				"token": token,
				"uid": uid,
				"email": email,
				"name": name,
				"picture": picture,
				"language": row[0]["language"]
			}
		},status.HTTP_200_OK)
	except Exception as e:
		print("signin error:",str(e))
		return errorresponse("ERROR_signin_error")


@api_view(["POST"])
def signup(request):
	# signup 流程: 使用者首次 Firebase 登入後, 補完顯示名稱 / 帳號類型 / 語言
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenrow=tokenrow[0]
			row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow["userid"]],SETTING["dbsetting"])
			if row:
				row=row[0]

				# 防護: type 已設定就不能再改
				if row["type"]:
					return errorresponse("ERROR_already_signed_up")

				requestdata=validate(json.loads(request.body),{
					"name": "required|string",
					"type": "required|string|in:player,dealer,floor,assistant",
					"language": "required|string|in:zhtw,en"
				},{
					"required": "ERROR_request_data_not_found",
					"string": "ERROR_request_data_type_error",
					"in": "ERROR_request_data_type_error"
				})

				if requestdata["error"] is None:
					name=requestdata["data"].get("name")
					usertype=requestdata["data"].get("type")
					language=requestdata["data"].get("language")

					queryupdate(SETTING["dbname"],"user",{
						"name": name,
						"type": usertype,
						"language": language,
						"updatetime": nowtime()
					},{
						"id": row["id"]
					},SETTING["dbsetting"])

					return Response({
						"success": True,
						"data": ""
					},status.HTTP_200_OK)
				else:
					return errorresponse(requestdata["error"])
			else:
				return errorresponse("ERROR_user_not_found")
		else:
			return errorresponse("ERROR_token_error")
	else:
		return errorresponse("ERROR_token_not_found")

@api_view(["POST"])
def signout(request):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")

	if token:
		row=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if row:
			query(SETTING["dbname"],f"""DELETE FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
			# 稽核：使用者登出（供後台 admin.html 追蹤帳號存取狀況）
			writeauditlog(SETTING["dbname"],SETTING["dbsetting"],row[0]["userid"],"user","signout",row[0]["userid"],None,None,request)
			return Response({
				"success": True,
				"data": ""
			},status.HTTP_200_OK)
		else:
			return errorresponse("ERROR_token_error")
	else:
		return errorresponse("ERROR_token_not_found")

@api_view(["GET"])
def signincheck(request):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if not token:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	row=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if row:
		userrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[row[0]["userid"]],SETTING["dbsetting"])
		if not userrow:
			return Response({
				"success": False,
				"data": "ERROR_user_not_found"
			},status.HTTP_404_NOT_FOUND)
		userrow=userrow[0]
		return Response({
			"success": True,
			"data": {
				"userid": userrow["id"],
				"permission": userrow["permission"],
			}
		},status.HTTP_200_OK)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_error"
		},status.HTTP_403_FORBIDDEN)

@api_view(["GET"])
def getuserlist(request):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenuserid=tokenrow[0]["userid"]
			tokenuserrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[tokenuserid],SETTING["dbsetting"])
			if 4<=int(tokenuserrow[0]["permission"]):
				data=[]
				row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "deletetime" IS NULL""",None,SETTING["dbsetting"])

				for i in range(len(row)):
					data.append({
						"id": row[i]["id"],
						"name": row[i]["name"],
						"email": row[i]["email"],
						"permission": row[i]["permission"],
						"createtime": row[i]["createtime"],
						"updatetime": row[i]["updatetime"]
					})

				return Response({
					"success": True,
					"data": data
				},status.HTTP_200_OK)
			else:
				return Response({
					"success": False,
					"data": "ERROR_no_permission"
				},status.HTTP_403_FORBIDDEN)
		else:
			return Response({
				"success": False,
				"data": "ERROR_token_error"
			},status.HTTP_403_FORBIDDEN)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

@api_view(["GET"])
def getuser(request):
	ensureuserchipsettables()
	ensureusertoolfavoritetable()
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenrow=tokenrow[0]
			row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow["userid"]],SETTING["dbsetting"])
			if row:
				row=row[0]

				# includefee toggle (預設 true=含服務費)
				includefee=True
				includefeeparam=request.GET.get("includefee")
				if includefeeparam=="false" or includefeeparam=="0":
					includefee=False

				# 計算個人成本的內部函式 (依 includefee 決定是否加 fee)
				def calccost(s):
					# 用 .get 寬容處理舊資料沒 fee 欄位的情況
					buyin=s.get("buyin") or 0
					bf=s.get("buyinfee") or 0
					rebuybuyin=s.get("rebuybuyin") or 0
					rf=s.get("rebuyfee") or 0
					reentrybuyin=s.get("reentrybuyin") or 0
					reentryfee=s.get("reentryfee") or 0
					addonbuyin=s.get("addonbuyin") or 0
					addonfee=s.get("addonfee") or 0
					if 0>=reentrybuyin:
						reentrybuyin=buyin
					if 0>=reentryfee:
						reentryfee=bf
					if includefee:
						return buyin+bf+(rebuybuyin+rf)*(s.get("rebuycount") or 0)+(reentrybuyin+reentryfee)*(s.get("reentrycount") or 0)+(addonbuyin+addonfee)*(s.get("addoncount") or 0)
					else:
						return buyin+rebuybuyin*(s.get("rebuycount") or 0)+reentrybuyin*(s.get("reentrycount") or 0)+addonbuyin*(s.get("addoncount") or 0)

				# 取得當前時間
				now=datetime.datetime.now()
				today_start=now.replace(hour=0,minute=0,second=0,microsecond=0)
				# 本週的開始(週一)和結束(週日)
				week_start=(now-timedelta(days=now.weekday())).replace(hour=0,minute=0,second=0,microsecond=0)
				week_end=(week_start+timedelta(days=6)).replace(hour=23,minute=59,second=59,microsecond=999999)
				# 本月的開始(1號)和結束(最後一天)
				month_start=now.replace(day=1,hour=0,minute=0,second=0,microsecond=0)
				next_month=month_start+timedelta(days=32)  # 跳到下個月
				month_end=(next_month.replace(day=1)-timedelta(days=1)).replace(hour=23,minute=59,second=59,microsecond=999999)
				# 最近7天（含今天）
				last_seven_days_start=today_start-timedelta(days=6)  # 往前推6天(加上今天共7天)

				# 計算今日盈利 (主辦牌局不計入個人盈虧)
				today_end=today_start.replace(hour=23,minute=59,second=59,microsecond=999999)
				today_sessions=query(SETTING["dbname"],
					"""SELECT winprice, buyin, buyinfee, rebuybuyin, rebuyfee, rebuycount, reentrybuyin, reentryfee, reentrycount, addonbuyin, addonfee, addoncount
					   FROM session
					   WHERE userid=%s AND deletetime IS NULL AND owned=false
					   AND %s<=starttime AND starttime <= %s""",
					[row["id"],today_start.strftime("%Y-%m-%d %H:%M:%S"),today_end.strftime("%Y-%m-%d %H:%M:%S")],
					SETTING["dbsetting"]
				)

				# 計算各時段的盈利
				today_profit=0
				for s in today_sessions:
					today_profit=today_profit+(s["winprice"]-calccost(s))

				# 計算本週盈利 (週一到週日, 主辦牌局不計入個人盈虧)
				week_sessions=query(SETTING["dbname"],
					"""SELECT winprice, buyin, buyinfee, rebuybuyin, rebuyfee, rebuycount, reentrybuyin, reentryfee, reentrycount, addonbuyin, addonfee, addoncount
					   FROM session
					   WHERE userid=%s AND deletetime IS NULL AND owned=false
					   AND starttime >= %s AND starttime <= %s""",
					[row["id"],
					 week_start.strftime("%Y-%m-%d %H:%M:%S"),
					 week_end.strftime("%Y-%m-%d %H:%M:%S")],
					SETTING["dbsetting"]
				)
				week_profit=0
				for s in week_sessions:
					week_profit=week_profit+(s["winprice"]-calccost(s))

				# 計算本月盈利 (1號到月底, 主辦牌局不計入個人盈虧)
				month_sessions=query(SETTING["dbname"],
					"""SELECT winprice, buyin, buyinfee, rebuybuyin, rebuyfee, rebuycount, reentrybuyin, reentryfee, reentrycount, addonbuyin, addonfee, addoncount
					   FROM session
					   WHERE userid=%s AND deletetime IS NULL AND owned=false
					   AND starttime >= %s AND starttime <= %s""",
					[row["id"],
					 month_start.strftime("%Y-%m-%d %H:%M:%S"),
					 month_end.strftime("%Y-%m-%d %H:%M:%S")],
					SETTING["dbsetting"]
				)
				month_profit=0
				for s in month_sessions:
					month_profit=month_profit+(s["winprice"]-calccost(s))

				# 計算最近7天盈利 (含今天, 主辦牌局不計入個人盈虧)
				last_week_sessions=query(SETTING["dbname"],
					"""SELECT DATE(starttime) as date,
					   winprice, buyin, buyinfee, rebuybuyin, rebuyfee, rebuycount, reentrybuyin, reentryfee, reentrycount, addonbuyin, addonfee, addoncount
					   FROM session
					   WHERE userid=%s AND deletetime IS NULL AND owned=false
					   AND starttime >= %s AND starttime <= %s
					   ORDER BY starttime ASC""",
					[row["id"],
					 last_seven_days_start.strftime("%Y-%m-%d %H:%M:%S"),
					 today_start.strftime("%Y-%m-%d 23:59:59.999999")],
					SETTING["dbsetting"]
				)

				# 將最近7天數據轉換為陣列 [前6天,前5天,前4天,前3天,前2天,前1天,今天]
				last_week_daily=[0]*7
				for session in last_week_sessions:
					session_date=datetime.datetime.strptime(str(session["date"]),"%Y-%m-%d").date()
					days_ago=(today_start.date()-session_date).days
					if 0 <= days_ago < 7:  # 確保日期在最近7天內
						array_index=6-days_ago  # 反轉索引,使今天在最後
						profit=session["winprice"]-calccost(session)
						last_week_daily[array_index] += profit

				employedby=[]
				if row["type"]!="player":
					employedby=query(SETTING["dbname"],
						f"""SELECT us.*, u."name" AS ownername, u."playerid" AS ownerplayerid, u."email" AS owneremail
						   FROM "userstaff" us
						   JOIN "user" u ON u."id"=us."userid"
						   WHERE us."staffuserid"=%s AND us."status"='active' AND us."deletetime" IS NULL
						   ORDER BY us."createtime" DESC""",
						[row["id"]],
						SETTING["dbsetting"]
					)

				return Response({
					"success": True,
					"data": {
						**{k:v for k,v in row.items() if k not in ("token","verifytoken","uid")},
						"chipcolors": parsechipcolors(row.get("chipcolors")),
						"chipset": loaduserchipset(row["id"]),
						"toolfavorite": loadusertoolfavorite(row["id"]),
						"todaytotalprofit": float(today_profit),
						"weektotalprofit": float(week_profit),
						"lastweekprofit": last_week_daily,
						"monthtotalprofit": float(month_profit),
						"employedby": employedby
					}
				},status.HTTP_200_OK)
			else:
				return Response({
					"success": False,
					"data": "ERROR_user_not_found"
				},status.HTTP_404_NOT_FOUND)
		else:
			return Response({
				"success": False,
				"data": "ERROR_token_error"
			},status.HTTP_403_FORBIDDEN)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

@api_view(["GET"])
def searchusers(request):
	header=request.headers.get("Authorization")
	token=None
	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")
	if not token:
		return errorresponse("ERROR_token_not_found")
	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return errorresponse("ERROR_token_error")
	operatorrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow[0]["userid"]],SETTING["dbsetting"])
	if not operatorrow:
		return errorresponse("ERROR_user_not_found")
	keyword=(request.GET.get("keyword") or "").strip()
	# sessionid 為空字串時綁 None (NULL): 帳號搜尋 (newedithand.js) 不帶 sessionid,
	# 若直接把 "" 綁進 bigint 比較 (sp."sessionid"=%s 等) 會觸發 '' -> bigint 轉型錯誤,
	# 讓整個 query 吞例外回 None → 端點永遠找不到人。綁 None 時 sessionplayer/staff 相關欄位
	# 自然為 NULL/false,走「純使用者搜尋」;register.js 帶 sessionid 的行為與回傳欄位不變。
	sessionid=(request.GET.get("sessionid") or "").strip()
	if not sessionid:
		sessionid=None
	if len(keyword)<1:
		return Response({"success": True,"data": []},status.HTTP_200_OK)
	like="%"+keyword+"%"
	rows=query(SETTING["dbname"],
		f"""SELECT u."id",u."name",u."playerid",u."email",u."type",
		       sp."id" AS sessionplayerid,sp."status" AS registrationstatus,
		       sp."reentrycount",sp."rebuycount",tp."status" AS timerstatus,
		       CASE
		           WHEN EXISTS(SELECT 1 FROM "sessionstaff" ss WHERE ss."sessionid"=%s AND ss."staffuserid"=u."id" AND ss."status"='active' AND ss."deletetime" IS NULL) THEN true
		           WHEN EXISTS(
		               SELECT 1
		               FROM "session" s
		               JOIN "userstaff" us ON us."userid"=s."userid"
		               WHERE s."id"=%s AND s."deletetime" IS NULL
		                 AND us."staffuserid"=u."id" AND us."status"='active' AND us."deletetime" IS NULL
		           ) THEN true
		           ELSE false
		       END AS isstaff
		   FROM "user" u
		   LEFT JOIN "sessionplayer" sp ON sp."userid"=u."id" AND sp."sessionid"=%s AND sp."deletetime" IS NULL
		   LEFT JOIN "sessiontimerplayer" tp ON tp."sessionplayerid"=sp."id" AND tp."sessionid"=sp."sessionid" AND tp."deletetime" IS NULL
		   WHERE u."deletetime" IS NULL
		     AND (u."playerid" ILIKE %s OR u."name" ILIKE %s OR u."email" ILIKE %s)
		   ORDER BY u."playerid" ASC
		   LIMIT 20""",
		[sessionid,sessionid,sessionid,like,like,like],
		SETTING["dbsetting"]
	)
	# 非管理員 (permission<4) 不回傳完整 email，改回遮罩後的 email，
	# 報名搜尋畫面仍可顯示辨識用資訊，但避免任何登入者枚舉全站使用者信箱
	if not (4<=int(operatorrow[0]["permission"])):
		for row in (rows or []):
			email=row.get("email") or ""
			if "@" in email:
				row["email"]=email.split("@")[0][:2]+"***@"+email.split("@",1)[1]
			else:
				row["email"]=""
	return Response({"success": True,"data": rows or []},status.HTTP_200_OK)

@api_view(["GET"])
def getuserreport(request):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenrow=tokenrow[0]
			row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow["userid"]],SETTING["dbsetting"])
			if row:
				row=row[0]
				data=request.GET.dict()

				requestdata=validate(data,{
					"type": "string|in:month,year,all",
					"year": "string",
					"month": "string"
				},{
					"string": "ERROR_request_data_type_error",
					"in": "ERROR_request_data_type_error"
				})

				if requestdata["error"] is None:
					type=requestdata["data"].get("type") if requestdata["data"].get("type") else "month"
					year=requestdata["data"].get("year") if requestdata["data"].get("year") else str(datetime.datetime.now().year)
					month=requestdata["data"].get("month") if requestdata["data"].get("month") else str(datetime.datetime.now().month)

					# includefee toggle (預設 true=含服務費)
					includefee=True
					includefeeparam=request.GET.get("includefee")
					if includefeeparam=="false" or includefeeparam=="0":
						includefee=False

					# 1. 先計算時間區間 (保持不變或優化)
					if type=="month":
						startdate=f"{year}-{month}-01 00:00:00"
						nextmonthdate=(datetime.datetime.strptime(startdate,"%Y-%m-%d %H:%M:%S")+timedelta(days=32)).replace(day=1)
						startdate=f"{year}-{month}-01 00:00:00+08"
						enddate=(nextmonthdate-timedelta(seconds=1)).strftime("%Y-%m-%d %H:%M:%S")+"+08"
					elif type=="year":
						startdate=f"{year}-01-01 00:00:00+08"
						enddate=f"{year}-12-31 23:59:59+08"
					else:
						startdate="1000-01-01 00:00:00+08"
						enddate="3000-12-31 23:59:59+08"
					# 2. 執行一條彙總查詢 (主辦牌局不計入個人盈虧)
					# 依 includefee 決定 cost 公式是否加 buyinfee + rebuyfee
					if includefee:
						summary_sql = """
							SELECT
								"gametype",
								COUNT(*) as count,
								SUM(COALESCE("buyin", 0) + COALESCE("buyinfee", 0) + (COALESCE("rebuybuyin", 0) + COALESCE("rebuyfee", 0)) * COALESCE("rebuycount", 0) + (COALESCE(NULLIF("reentrybuyin",0), "buyin", 0) + COALESCE(NULLIF("reentryfee",0), "buyinfee", 0)) * COALESCE("reentrycount", 0) + (COALESCE("addonbuyin", 0) + COALESCE("addonfee", 0)) * COALESCE("addoncount", 0)) as buyin,
								SUM(COALESCE("winprice", 0) - (COALESCE("buyin", 0) + COALESCE("buyinfee", 0) + (COALESCE("rebuybuyin", 0) + COALESCE("rebuyfee", 0)) * COALESCE("rebuycount", 0) + (COALESCE(NULLIF("reentrybuyin",0), "buyin", 0) + COALESCE(NULLIF("reentryfee",0), "buyinfee", 0)) * COALESCE("reentrycount", 0) + (COALESCE("addonbuyin", 0) + COALESCE("addonfee", 0)) * COALESCE("addoncount", 0))) as profit
							FROM "session"
							WHERE "userid" = %s AND "deletetime" IS NULL AND "owned"=false AND "starttime" >= %s AND "starttime" <= %s
							GROUP BY "gametype"
						"""
					else:
						summary_sql = """
							SELECT
								"gametype",
								COUNT(*) as count,
								SUM(COALESCE("buyin", 0)+COALESCE("rebuybuyin", 0)*COALESCE("rebuycount", 0)+COALESCE(NULLIF("reentrybuyin",0), "buyin", 0)*COALESCE("reentrycount", 0)+COALESCE("addonbuyin", 0)*COALESCE("addoncount", 0)) as buyin,
								SUM(COALESCE("winprice", 0) - (COALESCE("buyin", 0) + (COALESCE("rebuybuyin", 0) * COALESCE("rebuycount", 0)) + (COALESCE(NULLIF("reentrybuyin",0), "buyin", 0) * COALESCE("reentrycount", 0)) + (COALESCE("addonbuyin", 0) * COALESCE("addoncount", 0)))) as profit
							FROM "session"
							WHERE "userid" = %s AND "deletetime" IS NULL AND "owned"=false AND "starttime" >= %s AND "starttime" <= %s
							GROUP BY "gametype"
						"""
					raw_data = query(SETTING["dbname"], summary_sql, [row["id"], startdate, enddate], SETTING["dbsetting"])

					# 3. 整理成需要的格式
					stats = {
						"cash": {"count": 0, "buyin": 0, "profit": 0},
						"limited": {"count": 0, "buyin": 0, "profit": 0}, # 對應你原本的 tlt
						"tournament": {"count": 0, "buyin": 0, "profit": 0} # 對應你原本的 mtt
					}
					total_profit = 0

					for item in raw_data:
						g_type = item["gametype"]
						if g_type in stats:
							stats[g_type]["count"] = item["count"]
							stats[g_type]["buyin"] = float(item["buyin"] or 0)
							stats[g_type]["profit"] = float(item["profit"] or 0)
							total_profit=total_profit+float(item["profit"] or 0)

					regsessionrow=query(SETTING["dbname"],
						"""SELECT DISTINCT s.*
						   FROM "sessionplayer" sp
						   JOIN "session" s ON s."id"=sp."sessionid" AND s."deletetime" IS NULL
						   WHERE sp."userid"=%s AND sp."deletetime" IS NULL AND sp."status" IN ('confirmed','advanced') AND s."starttime">=%s AND s."starttime"<=%s""",
						[row["id"],startdate,enddate],
						SETTING["dbsetting"]
					)
					for regsession in regsessionrow:
						regrow=query(SETTING["dbname"],
							"""SELECT sp.*, tp."place" AS timerplace, tp."status" AS timerstatus
							   FROM "sessionplayer" sp
							   LEFT JOIN "sessiontimerplayer" tp ON tp."sessionid"=sp."sessionid" AND tp."userid"=sp."userid" AND tp."deletetime" IS NULL
							   WHERE sp."userid"=%s AND sp."sessionid"=%s AND sp."deletetime" IS NULL AND sp."status" IN ('confirmed','advanced')""",
							[row["id"],regsession["id"]],
							SETTING["dbsetting"]
						)
						regrow=_attachfinance(regsession,regrow)
						for item in regrow:
							g_type=regsession["gametype"]
							if g_type in stats:
								cost=item["cost"] or 0
								if not includefee and item.get("paymenttype")!="ticket":
									cost=cost-float(regsession.get("buyinfee") or 0)
									cost=cost-(float(regsession.get("rebuyfee") or 0)*(item.get("rebuycount") or 0))
									reentryfee=float(regsession.get("reentryfee") or 0)
									if reentryfee<=0:
										reentryfee=float(regsession.get("buyinfee") or 0)
									cost=cost-(reentryfee*(item.get("reentrycount") or 0))
									cost=cost-(float(regsession.get("addonfee") or 0)*(item.get("addoncount") or 0))
								profit=(item["finalprize"] or 0)-cost
								stats[g_type]["count"]=stats[g_type]["count"]+1
								stats[g_type]["buyin"]=stats[g_type]["buyin"]+cost
								stats[g_type]["profit"]=stats[g_type]["profit"]+profit
								total_profit=total_profit+profit

					typelist=["cash","limited","tournament"]
					for stattype in typelist:
						buyinval=stats[stattype]["buyin"] or 0
						profitval=stats[stattype]["profit"] or 0
						if 0<float(buyinval):
							stats[stattype]["roi"]=round((float(profitval)/float(buyinval))*100,2)
						else:
							stats[stattype]["roi"]=0

					# cashcount=query(SETTING["dbname"],"""SELECT COUNT(*) as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "gametype"='cash' AND %s<="starttime" AND "starttime"<=%s""",[row["id"],startdate,enddate],SETTING["dbsetting"])
					# cashbuyin=query(SETTING["dbname"],"""SELECT SUM("buyin") as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "gametype"='cash' AND %s<="starttime" AND "starttime"<=%s""",[row["id"],startdate,enddate],SETTING["dbsetting"])
					# cashprofit=query(SETTING["dbname"],"""SELECT SUM("winprice"-("buyin"+("rebuybuyin"*"rebuycount"))) as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "gametype"='cash' AND %s<="starttime" AND "starttime"<=%s""",[row["id"],startdate,enddate],SETTING["dbsetting"])

					# tltcount=query(SETTING["dbname"],"""SELECT COUNT(*) as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "gametype"='limited' AND %s<="starttime" AND "starttime"<=%s""",[row["id"],startdate,enddate],SETTING["dbsetting"])
					# tltbuyin=query(SETTING["dbname"],"""SELECT SUM("buyin") as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "gametype"='limited' AND %s<="starttime" AND "starttime"<=%s""",[row["id"],startdate,enddate],SETTING["dbsetting"])
					# tltprofit=query(SETTING["dbname"],"""SELECT SUM("winprice"-("buyin"+("rebuybuyin"*"rebuycount"))) as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "gametype"='limited' AND %s<="starttime" AND "starttime"<=%s""",[row["id"],startdate,enddate],SETTING["dbsetting"])

					mttbuyincount=query(SETTING["dbname"],"""SELECT SUM(1+COALESCE("rebuycount", 0)+COALESCE("reentrycount", 0)) as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "owned"=false AND "gametype"='tournament' AND %s<="starttime" AND "starttime"<=%s""",[row["id"],startdate,enddate],SETTING["dbsetting"])
					regmttbuyincount=query(SETTING["dbname"],"""SELECT SUM(1+COALESCE(sp."rebuycount",0)+COALESCE(sp."reentrycount",0)+COALESCE(sp."addoncount",0)) as count FROM "sessionplayer" sp JOIN "session" s ON s."id"=sp."sessionid" AND s."deletetime" IS NULL WHERE sp."userid"=%s AND sp."deletetime" IS NULL AND sp."status"='confirmed' AND s."gametype"='tournament' AND %s<=s."starttime" AND s."starttime"<=%s""",[row["id"],startdate,enddate],SETTING["dbsetting"])
					stats["tournament"]["buyincount"]=(mttbuyincount[0]["count"] if mttbuyincount[0]["count"] else 0)+(regmttbuyincount[0]["count"] if regmttbuyincount and regmttbuyincount[0]["count"] else 0)

					# MTT 進階統計: ROI% / ITM% / ft% / Top3%
					mttstats=query(SETTING["dbname"],
						"""SELECT
							COUNT(CASE WHEN "inmoney"=true THEN 1 END) AS itm,
							COUNT(CASE WHEN "inft"=true THEN 1 END) AS ft,
							COUNT(CASE WHEN "place" IN ('1','2','3') THEN 1 END) AS top3
						FROM "session"
						WHERE "userid"=%s AND "deletetime" IS NULL AND "owned"=false
						AND "gametype"='tournament' AND %s<="starttime" AND "starttime"<=%s""",
						[row["id"],startdate,enddate],
						SETTING["dbsetting"]
					)

					mttcount=stats["tournament"]["count"] or 0
					mttbuyinval=stats["tournament"]["buyin"] or 0
					mttprofitval=stats["tournament"]["profit"] or 0
					itmcount=(mttstats[0]["itm"] if mttstats and mttstats[0]["itm"] else 0) or 0
					ftcount=(mttstats[0]["ft"] if mttstats and mttstats[0]["ft"] else 0) or 0
					top3count=(mttstats[0]["top3"] if mttstats and mttstats[0]["top3"] else 0) or 0

					# 算百分比, 沒場次的話一律 0
					if 0<mttcount:
						itmpct=round((float(itmcount)/float(mttcount))*100,2)
						ftpct=round((float(ftcount)/float(mttcount))*100,2)
						top3pct=round((float(top3count)/float(mttcount))*100,2)
					else:
						itmpct=0
						ftpct=0
						top3pct=0

					if 0<float(mttbuyinval):
						roipct=round((float(mttprofitval)/float(mttbuyinval))*100,2)
					else:
						roipct=0

					stats["tournament"]["roi"]=roipct
					stats["tournament"]["itm"]=itmpct
					stats["tournament"]["ft"]=ftpct
					stats["tournament"]["top3"]=top3pct

					# 總盈虧 (依 includefee 決定 cost 是否含 fee)
					if includefee:
						profitsql="""SELECT SUM(COALESCE("winprice", 0) - (COALESCE("buyin", 0) + COALESCE("buyinfee", 0) + (COALESCE("rebuybuyin", 0) + COALESCE("rebuyfee", 0)) * COALESCE("rebuycount", 0) + (COALESCE(NULLIF("reentrybuyin",0), "buyin", 0) + COALESCE(NULLIF("reentryfee",0), "buyinfee", 0)) * COALESCE("reentrycount", 0) + (COALESCE("addonbuyin", 0) + COALESCE("addonfee", 0)) * COALESCE("addoncount", 0))) as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "owned"=false AND %s<="starttime" AND "starttime"<=%s"""
					else:
						profitsql="""SELECT SUM(COALESCE("winprice", 0) - (COALESCE("buyin", 0) + (COALESCE("rebuybuyin", 0) * COALESCE("rebuycount", 0)) + (COALESCE(NULLIF("reentrybuyin",0), "buyin", 0) * COALESCE("reentrycount", 0)) + (COALESCE("addonbuyin", 0) * COALESCE("addoncount", 0)))) as count FROM "session" WHERE "userid"=%s AND "deletetime" IS NULL AND "owned"=false AND %s<="starttime" AND "starttime"<=%s"""
					profit=query(SETTING["dbname"],profitsql,[row["id"],startdate,enddate],SETTING["dbsetting"])
					totalprofit=(profit[0]["count"] if profit[0]["count"] else Decimal("0")) + (Decimal(str(total_profit)) - (profit[0]["count"] if profit[0]["count"] else Decimal("0")))

					# return Response({
					# 	"success": True,
					# 	"data": {
					# 		"cash": {
					# 			"count": cashcount[0]["count"],
					# 			"buyin": cashbuyin[0]["count"] if cashbuyin[0]["count"] else 0,
					# 			"profit": cashprofit[0]["count"] if cashprofit[0]["count"] else 0,
					# 		},
					# 		"tlt": {
					# 			"count": tltcount[0]["count"],
					# 			"buyin": tltbuyin[0]["count"] if tltbuyin[0]["count"] else 0,
					# 			"profit": tltprofit[0]["count"] if tltprofit[0]["count"] else 0,
					# 		},
					# 		"mtt": {
					# 			"count": mttcount[0]["count"],
					# 			"buyin": mttbuyin[0]["count"] if mttbuyin[0]["count"] else 0,
					# 			"profit": mttprofit[0]["count"] if mttprofit[0]["count"] else 0,
					# 		},
					# 		"profit": profit[0]["count"] if profit[0]["count"] else 0,
					# 	}
					# },status.HTTP_200_OK)
					return Response({
						"success": True,
						"data": {
							"cash": stats["cash"],
							"tlt": stats["limited"],
							"mtt": stats["tournament"],
							"profit": totalprofit,
						}
					},status.HTTP_200_OK)
				else:
					return errorresponse(requestdata["error"])


				# 取得當前時間
				now=datetime.datetime.now()
				today_start=now.replace(hour=0,minute=0,second=0,microsecond=0)
				# 本週的開始(週一)和結束(週日)
				week_start=(now-timedelta(days=now.weekday())).replace(hour=0,minute=0,second=0,microsecond=0)
				week_end=(week_start+timedelta(days=6)).replace(hour=23,minute=59,second=59,microsecond=999999)
				# 本月的開始(1號)和結束(最後一天)
				month_start=now.replace(day=1,hour=0,minute=0,second=0,microsecond=0)
				next_month=month_start+timedelta(days=32)  # 跳到下個月
				month_end=(next_month.replace(day=1)-timedelta(days=1)).replace(hour=23,minute=59,second=59,microsecond=999999)
				# 最近7天（含今天）
				last_seven_days_start=today_start-timedelta(days=6)  # 往前推6天(加上今天共7天)

				# 計算今日盈利
				today_end=today_start.replace(hour=23,minute=59,second=59,microsecond=999999)
				today_sessions=query(SETTING["dbname"],
					"""SELECT winprice, buyin, rebuybuyin, rebuycount
					   FROM session
					   WHERE userid=%s AND deletetime IS NULL
					   AND %s<=starttime AND starttime <= %s""",
					[row["id"],today_start.strftime("%Y-%m-%d %H:%M:%S"),today_end.strftime("%Y-%m-%d %H:%M:%S")],
					SETTING["dbsetting"]
				)

				# 計算各時段的盈利
				today_profit=0
				for s in today_sessions:
					today_profit=today_profit+(s["winprice"]-(s["buyin"]+(s["rebuybuyin"]*s["rebuycount"])))

				# 計算本週盈利 (週一到週日)
				week_sessions=query(SETTING["dbname"],
					"""SELECT winprice, buyin, rebuybuyin, rebuycount
					   FROM session
					   WHERE userid=%s AND deletetime IS NULL
					   AND starttime >= %s AND starttime <= %s""",
					[row["id"],
					 week_start.strftime("%Y-%m-%d %H:%M:%S"),
					 week_end.strftime("%Y-%m-%d %H:%M:%S")],
					SETTING["dbsetting"]
				)
				week_profit=0
				for s in week_sessions:
					week_profit=week_profit+s["winprice"]-(s["buyin"]+(s["rebuybuyin"]*s["rebuycount"]))

				# 計算本月盈利 (1號到月底)
				month_sessions=query(SETTING["dbname"],
					"""SELECT winprice, buyin, rebuybuyin, rebuycount
					   FROM session
					   WHERE userid=%s AND deletetime IS NULL
					   AND starttime >= %s AND starttime <= %s""",
					[row["id"],
					 month_start.strftime("%Y-%m-%d %H:%M:%S"),
					 month_end.strftime("%Y-%m-%d %H:%M:%S")],
					SETTING["dbsetting"]
				)
				month_profit=0
				for s in month_sessions:
					month_profit=month_profit+s["winprice"]-(s["buyin"]+(s["rebuybuyin"]*s["rebuycount"]))

				# 計算最近7天盈利 (含今天)
				last_week_sessions=query(SETTING["dbname"],
					"""SELECT DATE(starttime) as date,
					   winprice, buyin, rebuybuyin, rebuycount
					   FROM session
					   WHERE userid=%s AND deletetime IS NULL
					   AND starttime >= %s AND starttime <= %s
					   ORDER BY starttime ASC""",
					[row["id"],
					 last_seven_days_start.strftime("%Y-%m-%d %H:%M:%S"),
					 today_start.strftime("%Y-%m-%d 23:59:59.999999")],
					SETTING["dbsetting"]
				)

				# 將最近7天數據轉換為陣列 [前6天,前5天,前4天,前3天,前2天,前1天,今天]
				last_week_daily=[0]*7
				for session in last_week_sessions:
					session_date=datetime.datetime.strptime(str(session["date"]),"%Y-%m-%d").date()
					days_ago=(today_start.date()-session_date).days
					if 0 <= days_ago < 7:  # 確保日期在最近7天內
						array_index=6-days_ago  # 反轉索引,使今天在最後
						profit=session["winprice"]-(session["buyin"]+(session["rebuybuyin"]*session["rebuycount"]))
						last_week_daily[array_index] += profit

				return Response({
					"success": True,
					"data": {
						**row,
						"todaytotalprofit": float(today_profit),
						"weektotalprofit": float(week_profit),
						"lastweekprofit": last_week_daily,
						"monthtotalprofit": float(month_profit),
					}
				},status.HTTP_200_OK)
			else:
				return Response({
					"success": False,
					"data": "ERROR_user_not_found"
				},status.HTTP_404_NOT_FOUND)
		else:
			return Response({
				"success": False,
				"data": "ERROR_token_error"
			},status.HTTP_403_FORBIDDEN)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

@api_view(["POST"])
def blockuser(request,userid):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenuserid=tokenrow[0]["userid"]
			tokenuserrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[tokenuserid],SETTING["dbsetting"])
			if 4<=int(tokenuserrow[0]["permission"]):
				data=json.loads(request.body)
				reason=data.get("reason")
				blocktime=data.get("blocktime")
				if reason and blocktime:
					# 封鎖必須同時撤銷被封鎖者手上的所有 token，否則舊 token 仍可通過各端點的 inline 驗證。
					# WHERE 用目標 userid（被封鎖者），不是操作者 tokenuserid，別把管理員自己踢下線。
					# 兩件事包成單一交易：寫不進封鎖紀錄就不該撤 token，避免只做一半。
					sqllist=[
						["""INSERT INTO "blockbanuser"("userid","blockbanuserid","reason","type","time","createtime")VALUES(%s,%s,%s,%s,%s,%s)""",[tokenuserid,userid,reason,"block",blocktime,nowtime()]],
						["""DELETE FROM "token" WHERE "userid"=%s""",[userid]]
					]
					response=querytransaction(SETTING["dbname"],sqllist,SETTING["dbsetting"])
					# 原本不檢查寫入結果，blockbanuser 表不存在時 query() 吃掉例外、端點照樣回 success:True，
					# 管理員以為封鎖成功但其實什麼都沒寫。這裡如實回報失敗。
					if response is None:
						return Response({
							"success": False,
							"data": "ERROR_database_error"
						},status.HTTP_500_INTERNAL_SERVER_ERROR)
					return Response({
						"success": True,
						"data": ""
					},status.HTTP_200_OK)
				else:
					return Response({
						"success": False,
						"data": "ERROR_request_data_not_found"
					},status.HTTP_400_BAD_REQUEST)
			else:
				return Response({
					"success": False,
					"data": "ERROR_no_permission"
				},status.HTTP_403_FORBIDDEN)
		else:
			return Response({
				"success": False,
				"data": "ERROR_token_error"
			},status.HTTP_403_FORBIDDEN)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

@api_view(["POST"])
def banuser(request,userid):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenuserid=tokenrow[0]["userid"]
			tokenuserrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[tokenuserid],SETTING["dbsetting"])
			if 4<=int(tokenuserrow[0]["permission"]):
				data=json.loads(request.body)
				reason=data.get("reason")
				if reason:
					# 永久封禁必須同時撤銷被封禁者手上的所有 token，否則舊 token 仍可通過各端點的 inline 驗證。
					# WHERE 用目標 userid（被封禁者），不是操作者 tokenuserid，別把管理員自己踢下線。
					# 兩件事包成單一交易：寫不進封禁紀錄就不該撤 token，避免只做一半。
					sqllist=[
						["""INSERT INTO "blockbanuser"("userid","blockbanuserid","reason","type","time","createtime")VALUES(%s,%s,%s,%s,%s,%s)""",[tokenuserid,userid,reason,"ban","inf",nowtime()]],
						["""DELETE FROM "token" WHERE "userid"=%s""",[userid]]
					]
					response=querytransaction(SETTING["dbname"],sqllist,SETTING["dbsetting"])
					# 原本不檢查寫入結果，blockbanuser 表不存在時 query() 吃掉例外、端點照樣回 success:True，
					# 管理員以為封禁成功但其實什麼都沒寫。這裡如實回報失敗。
					if response is None:
						return Response({
							"success": False,
							"data": "ERROR_database_error"
						},status.HTTP_500_INTERNAL_SERVER_ERROR)
					return Response({
						"success": True,
						"data": ""
					},status.HTTP_200_OK)
				else:
					return Response({
						"success": False,
						"data": "ERROR_request_data_not_found"
					},status.HTTP_400_BAD_REQUEST)
			else:
				return Response({
					"success": False,
					"data": "ERROR_no_permission"
				},status.HTTP_403_FORBIDDEN)
		else:
			return Response({
				"success": False,
				"data": "ERROR_token_error"
			},status.HTTP_403_FORBIDDEN)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

@api_view(["POST"])
def unbanuser(request,userid):
	# 解除封禁：刪掉目標使用者在 blockbanuser 的紀錄，讓 authhelper.getuserbanned 不再判定封禁。
	# 權限比照 banuser／blockuser，admin permission>=4 才能操作。
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenuserid=tokenrow[0]["userid"]
			tokenuserrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[tokenuserid],SETTING["dbsetting"])
			if 4<=int(tokenuserrow[0]["permission"]):
				# blockbanuser 沒有 deletetime 欄（INSERT 與 deleteuser 都是硬刪），這裡也用 DELETE 硬刪。
				# WHERE 用 blockbanuserid（被封禁者）比對，比照 getuserbanned；用 userid 會反刪到操作管理員自己開的封禁紀錄。
				# ban 與 block 都是刪紀錄即解除，不分 type 一併移除該使用者的所有封禁紀錄。
				# 解除不需動 token：被封時 token 已撤銷，使用者重新登入即可，這裡不新增任何 token。
				# blockbanuser 目前線上不存在（另一 agent 正在 dbinitialize 建表），存在才刪，比照 deleteuser 的守門，
				# 避免表不存在時 querytransaction 整批 rollback；表不存在＝沒有任何封禁紀錄，視為已解除。
				blockbantable=query(SETTING["dbname"],"""SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='blockbanuser'""",[],SETTING["dbsetting"])
				if blockbantable:
					sqllist=[
						["""DELETE FROM "blockbanuser" WHERE "blockbanuserid"=%s""",[userid]]
					]
					response=querytransaction(SETTING["dbname"],sqllist,SETTING["dbsetting"])
					# 比照 banuser：寫入失敗（querytransaction 回 None）就如實回報，不要假成功。
					if response is None:
						return errorresponse("ERROR_database_error")
				return Response({
					"success": True,
					"data": ""
				},status.HTTP_200_OK)
			else:
				return errorresponse("ERROR_no_permission")
		else:
			return errorresponse("ERROR_token_error")
	else:
		return errorresponse("ERROR_token_not_found")

@api_view(["PUT"])
def edituserlanguage(request):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenrow=tokenrow[0]
			data=json.loads(request.body)

			requestdata=validate(data,{
				"langkey": "required|string|in:zhtw,en"
			},{
				"required": "ERROR_request_data_not_found",
				"string": "ERROR_request_data_type_error",
			})

			if requestdata["error"] is None:
				langkey=requestdata["data"].get("langkey")

				row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[tokenrow["userid"]],SETTING["dbsetting"])
				if row:
					query(SETTING["dbname"],f"""UPDATE "user" SET "language"=%s,"updatetime"=%s WHERE "id"=%s""",[langkey,nowtime(),tokenrow["userid"]],SETTING["dbsetting"])
					# row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[tokenrow["userid"]],SETTING["dbsetting"])

					return Response({
						"success": True,
						"data": langkey
					},status.HTTP_200_OK)
				else:
					return Response({
						"success": False,
						"data": "ERROR_request_data_not_found"
					},status.HTTP_401_UNAUTHORIZED)
			else:
				return errorresponse(requestdata["error"])
		else:
			return Response({
				"success": False,
				"data": "ERROR_token_error"
			},status.HTTP_403_FORBIDDEN)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

@api_view(["PUT"])
def edituserchipcolors(request):
	header=request.headers.get("Authorization")
	token=None
	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")
	if not token:
		return errorresponse("ERROR_token_not_found")
	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return errorresponse("ERROR_token_error")
	data=json.loads(request.body)
	colors=data.get("colors")
	if not isinstance(colors,list):
		return errorresponse("ERROR_request_data_type_error")
	output=[]
	for i in range(len(colors)):
		item=colors[i]
		if not isinstance(item,dict):
			continue
		name=str(item.get("name") or "").strip()
		color=str(item.get("color") or "").strip()
		if not re.match(r"^#[0-9a-fA-F]{6}$",color):
			continue
		if name=="":
			name=color
		output.append({
			"name": name[:20],
			"color": color.lower()
		})
	if len(output)==0:
		output=defaultchipcolors()
	query(SETTING["dbname"],f"""UPDATE "user" SET "chipcolors"=%s,"updatetime"=%s WHERE "id"=%s""",[json.dumps(output,ensure_ascii=False),nowtime(),tokenrow[0]["userid"]],SETTING["dbsetting"])
	return Response({
		"success": True,
		"data": output
	},status.HTTP_200_OK)

@api_view(["PUT"])
def edituserchipset(request):
	ensureuserchipsettables()
	header=request.headers.get("Authorization")
	token=None
	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")
	if not token:
		return errorresponse("ERROR_token_not_found")
	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return errorresponse("ERROR_token_error")
	data=json.loads(request.body)
	sets=data.get("sets")
	if not isinstance(sets,list):
		return errorresponse("ERROR_request_data_type_error")
	output=[]
	for i in range(len(sets)):
		item=sets[i]
		if not isinstance(item,dict):
			continue
		name=str(item.get("name") or "").strip()
		chips=item.get("chips") or []
		if name=="":
			name="計分牌組合 "+str(i+1)
		chipoutput=[]
		if isinstance(chips,list):
			for j in range(len(chips)):
				chip=chips[j]
				if not isinstance(chip,dict):
					continue
				shape=chip.get("shape") or "circle"
				if shape!="square":
					shape="circle"
				try:
					value=int(chip.get("value") or 0)
				except Exception as error:
					value=0
				color=str(chip.get("color") or "").strip()
				if value<=0:
					continue
				if not re.match(r"^#[0-9a-fA-F]{6}$",color):
					color="#888888"
				chipoutput.append({
					"shape": shape,
					"value": value,
					"color": color.lower()
				})
		if len(chipoutput)==0:
			continue
		output.append({
			"name": name[:30],
			"chips": chipoutput
		})
	if len(output)==0:
		output=defaultchipset()
	saveuserchipset(tokenrow[0]["userid"],output)
	return Response({
		"success": True,
		"data": loaduserchipset(tokenrow[0]["userid"])
	},status.HTTP_200_OK)

@api_view(["GET"])
def gettoolfavorite(request):
	ensureusertoolfavoritetable()
	header=request.headers.get("Authorization")
	token=None
	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")
	if not token:
		return errorresponse("ERROR_token_not_found")
	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return errorresponse("ERROR_token_error")
	return Response({
		"success": True,
		"data": loadusertoolfavorite(tokenrow[0]["userid"])
	},status.HTTP_200_OK)

@api_view(["PUT"])
def edittoolfavorite(request):
	ensureusertoolfavoritetable()
	header=request.headers.get("Authorization")
	token=None
	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")
	if not token:
		return errorresponse("ERROR_token_not_found")
	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return errorresponse("ERROR_token_error")
	data=json.loads(request.body)
	favorites=data.get("favorites")
	if not isinstance(favorites,list):
		return errorresponse("ERROR_request_data_type_error")
	output=parsetoolfavorites(json.dumps(favorites,ensure_ascii=False))
	saveusertoolfavorite(tokenrow[0]["userid"],output)
	return Response({
		"success": True,
		"data": loadusertoolfavorite(tokenrow[0]["userid"])
	},status.HTTP_200_OK)

@api_view(["PUT"])
def edituser(request):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			tokenrow=tokenrow[0]
			data=json.loads(request.body)

			requestdata=validate(data,{
				"email": "required|string",
				"name": "required|string",
				"phone": "required|string"
			},{
				"required": "ERROR_request_data_not_found",
				"string": "ERROR_request_data_type_error",
			})

			if requestdata["error"] is None:
				email=requestdata["data"].get("email")
				name=requestdata["data"].get("name")
				phone=requestdata["data"].get("phone")

				row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[tokenrow["userid"]],SETTING["dbsetting"])
				if row:
					query(SETTING["dbname"],f"""UPDATE "user" SET "email"=%s,"name"=%s,"phone"=%s,"updatetime"=%s WHERE "id"=%s""",[email,name,phone,nowtime(),tokenrow["userid"]],SETTING["dbsetting"])

					row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[tokenrow["userid"]],SETTING["dbsetting"])

					# 比照 getuser 過濾敏感欄位，避免把 token/verifytoken/uid 回傳給前端
					return Response({
						"success": True,
						"data": {k:v for k,v in row[0].items() if k not in ("token","verifytoken","uid")}
					},status.HTTP_200_OK)
				else:
					return Response({
						"success": False,
						"data": "ERROR_request_data_not_found"
					},status.HTTP_401_UNAUTHORIZED)
			else:
				return errorresponse(requestdata["error"])
		else:
			return Response({
				"success": False,
				"data": "ERROR_token_error"
			},status.HTTP_403_FORBIDDEN)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

@api_view(["PUT"])
def edituserpermission(request,userid):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			data=json.loads(request.body)
			validateresponse=validate(json.loads(request.body),{
				"permission": "required|string|in:1,2,3,4,5"
			},{
				"required": "ERROR_request_data_not_found",
				"string": "ERROR_request_data_type_error",
				"in": "ERROR_request_data_type_error",
			})


			if validateresponse["success"]:
				# 權限判斷必須針對「操作者」(token 擁有者)，而非「被修改的使用者」
				operatorrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow[0]["userid"]],SETTING["dbsetting"])
				if not operatorrow:
					return errorresponse("ERROR_user_not_found")
				if not (4<=int(operatorrow[0]["permission"])):
					return errorresponse("ERROR_no_permission")
				row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[userid],SETTING["dbsetting"])
				if row:
					row=row[0]
					data=validateresponse["data"]
					beforeperm=row.get("permission")
					row=query(SETTING["dbname"],f"""UPDATE "user" SET "permission"=%s,"updatetime"=%s WHERE "id"=%s""",[data["permission"],nowtime(),userid],SETTING["dbsetting"])
					# 稽核：權限變更（檢查表 1.7）
					writeauditlog(SETTING["dbname"],SETTING["dbsetting"],operatorrow[0]["id"],"user","editpermission",userid,{"permission": beforeperm},{"permission": data["permission"]},request)

					return Response({
						"success": True,
						"data": row
					},status.HTTP_200_OK)
				else:
					return errorresponse("ERROR_user_not_found")
			else:
				return errorresponse(validateresponse["error"])
		else:
			return errorresponse("ERROR_token_error")
	else:
		return errorresponse("ERROR_token_not_found")

@api_view(["DELETE"])
def deleteuser(request,userid):
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)

	if token:
		tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
		if tokenrow:
			# 刪除使用者屬高權限操作，必須驗證操作者(token 擁有者)的管理權限
			operatorrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow[0]["userid"]],SETTING["dbsetting"])
			if not operatorrow or not (4<=int(operatorrow[0]["permission"])):
				return Response({
					"success": False,
					"data": "ERROR_no_permission"
				},status.HTTP_403_FORBIDDEN)
			row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s""",[userid],SETTING["dbsetting"])
			if row:
				# 權限已於上方 operatorrow 檢查（需 permission>=4），此處直接執行軟刪除。
				# 軟刪除必須同時撤銷該使用者的所有 token，否則被刪除者手上的舊 token 仍可通過
				# 各端點的 inline 驗證繼續操作；兩件事包在單一交易，避免只做一半。
				sqllist=[
					["""UPDATE "user" SET "deletetime"=%s WHERE "id"=%s""",[nowtime(),userid]],
					["""DELETE FROM "token" WHERE "userid"=%s""",[userid]]
				]
				response=querytransaction(SETTING["dbname"],sqllist,SETTING["dbsetting"])
				if response is None:
					return Response({
						"success": False,
						"data": "ERROR_deleteuser_error"
					},status.HTTP_400_BAD_REQUEST)
				# 稽核：刪除使用者（檢查表 1.7）
				writeauditlog(SETTING["dbname"],SETTING["dbsetting"],operatorrow[0]["id"],"user","delete",userid,{"permission": row[0].get("permission"),"email": row[0].get("email")},None,request)
				return Response({
					"success": True,
					"data": ""
				},status.HTTP_200_OK)
			else:
				return Response({
					"success": False,
					"data": "ERROR_api_not_found"
				},status.HTTP_400_BAD_REQUEST)
		else:
			return Response({
				"success": False,
				"data": "ERROR_token_error"
			},status.HTTP_403_FORBIDDEN)
	else:
		return Response({
			"success": False,
			"data": "ERROR_token_not_found"
		},status.HTTP_401_UNAUTHORIZED)
@api_view(["DELETE"])
def deleteuseraccount(request):
	# 使用者自行刪除帳號：硬刪除（真刪除）所有與此使用者相關的資料，無法復原。
	# 與管理員的 deleteuser（軟刪除指定使用者）不同，此端點只作用在 token 擁有者自己身上。
	# auditlog / apilog 屬系統稽核紀錄，保留不刪；別人場次中的歷史手牌/座位列保留但去識別化。
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")

	if not token:
		return errorresponse("ERROR_token_not_found")

	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return errorresponse("ERROR_token_error")

	row=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow[0]["userid"]],SETTING["dbsetting"])
	if not row:
		return errorresponse("ERROR_user_not_found")
	row=row[0]
	userid=row["id"]

	# 防呆：前端 lightbox 已確認兩次，後端仍要求輸入的玩家 ID 完全一致才執行
	try:
		data=json.loads(request.body)
	except Exception as error:
		data={}
	confirmtext=str(data.get("confirmtext") or "").strip()
	if confirmtext!=str(row["playerid"]):
		return errorresponse("ERROR_confirm_text_error")

	# 確保執行期才建立的表存在，避免交易中對不存在的表 DELETE 導致整批 rollback
	ensureuserchipsettables()
	ensureusertoolfavoritetable()
	from .notification import ensurenotificationtable
	ensurenotificationtable()

	# 稽核：先寫入刪除紀錄（帳號刪除後 auditlog.userid 仍保留數字供追查）
	writeauditlog(SETTING["dbname"],SETTING["dbsetting"],userid,"user","deleteaccount",userid,{"email": row.get("email"),"playerid": row.get("playerid")},None,request)

	OWNSESSION="""SELECT "id" FROM "session" WHERE "userid"=%s"""
	OWNTABLE="""SELECT "id" FROM "table" WHERE "sessionid" IN ("""+OWNSESSION+""")"""
	OWNHAND="""SELECT "id" FROM "hand" WHERE "tableid" IN ("""+OWNTABLE+""")"""

	sqllist=[
		# 自己主辦場次的完整資料樹（手牌 → 桌次 → 場次，由子到母刪）
		["""DELETE FROM "handpotallocation" WHERE "handpotid" IN (SELECT "id" FROM "handpot" WHERE "handid" IN ("""+OWNHAND+"""))""",[userid]],
		["""DELETE FROM "handpot" WHERE "handid" IN ("""+OWNHAND+""")""",[userid]],
		["""DELETE FROM "handrake" WHERE "handid" IN ("""+OWNHAND+""")""",[userid]],
		["""DELETE FROM "handbittingdata" WHERE "handid" IN ("""+OWNHAND+""")""",[userid]],
		["""DELETE FROM "handseating" WHERE "handid" IN ("""+OWNHAND+""")""",[userid]],
		["""DELETE FROM "handplayercard" WHERE "handid" IN ("""+OWNHAND+""")""",[userid]],
		["""DELETE FROM "communitycard" WHERE "handid" IN ("""+OWNHAND+""")""",[userid]],
		["""DELETE FROM "hand" WHERE "tableid" IN ("""+OWNTABLE+""")""",[userid]],
		["""DELETE FROM "seating" WHERE "tableid" IN ("""+OWNTABLE+""")""",[userid]],
		["""DELETE FROM "sessiontimebank" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "table" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessionchip" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessiontimer" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessiontimerconfig" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessiontimerlevel" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessiontimerpayout" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessiontimerplayer" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessionplayer" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessionstaff" WHERE "sessionid" IN ("""+OWNSESSION+""")""",[userid]],
		["""DELETE FROM "sessionrelation" WHERE "sourceid" IN ("""+OWNSESSION+""") OR "targetid" IN ("""+OWNSESSION+""")""",[userid,userid]],
		["""DELETE FROM "seriessession" WHERE "sessionid" IN ("""+OWNSESSION+""") OR "seriesid" IN (SELECT "id" FROM "series" WHERE "userid"=%s)""",[userid,userid]],
		["""DELETE FROM "series" WHERE "userid"=%s""",[userid]],
		["""DELETE FROM "session" WHERE "userid"=%s""",[userid]],
		["""DELETE FROM "club" WHERE "userid"=%s""",[userid]],
		# 參加別人場次的個人報名/計時器紀錄
		["""DELETE FROM "sessiontimerplayer" WHERE "userid"=%s""",[userid]],
		["""DELETE FROM "sessionplayer" WHERE "userid"=%s""",[userid]],
		# 別人場次的歷史手牌/座位列保留（不破壞其他玩家的牌局紀錄），但去識別化
		["""UPDATE "seating" SET "userid"=NULL,"sessionplayerid"=NULL,"name"=NULL,"updatetime"=NOW() WHERE "userid"=%s""",[userid]],
		["""UPDATE "handseating" SET "userid"=NULL,"sessionplayerid"=NULL,"name"=NULL,"updatetime"=NOW() WHERE "userid"=%s""",[userid]],
		["""UPDATE "hand" SET "userid"=NULL,"handcard"=NULL,"updatetime"=NOW() WHERE "userid"=%s""",[userid]],
		["""UPDATE "player" SET "userid"=NULL,"updatetime"=NOW() WHERE "userid"=%s""",[userid]],
		["""UPDATE "contactmessage" SET "replyuserid"=NULL,"updatetime"=NOW() WHERE "replyuserid"=%s""",[userid]],
		# 聘用關聯（雙向）、個人設定、通知、聯絡訊息、token，最後刪 user 本體
		["""DELETE FROM "userstaff" WHERE "userid"=%s OR "staffuserid"=%s""",[userid,userid]],
		["""DELETE FROM "userdealer" WHERE "userid"=%s OR "userdealerid"=%s""",[userid,userid]],
		["""DELETE FROM "userchipsetchip" WHERE "chipsetid" IN (SELECT "id" FROM "userchipset" WHERE "userid"=%s)""",[userid]],
		["""DELETE FROM "userchipset" WHERE "userid"=%s""",[userid]],
		["""DELETE FROM "usertoolfavorite" WHERE "userid"=%s""",[userid]],
		["""DELETE FROM "notification" WHERE "userid"=%s""",[userid]],
		["""DELETE FROM "contactmessage" WHERE "userid"=%s""",[userid]],
		["""DELETE FROM "token" WHERE "userid"=%s""",[userid]],
		["""DELETE FROM "user" WHERE "id"=%s""",[userid]]
	]

	# blockbanuser 沒有 dbinitialize/ensure 建表，存在才刪，避免交易整批 rollback
	blockbantable=query(SETTING["dbname"],"""SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='blockbanuser'""",[],SETTING["dbsetting"])
	if blockbantable:
		sqllist.insert(len(sqllist)-2,["""DELETE FROM "blockbanuser" WHERE "userid"=%s OR "blockbanuserid"=%s""",[userid,userid]])

	response=querytransaction(SETTING["dbname"],sqllist,SETTING["dbsetting"])
	if response is None:
		return errorresponse("ERROR_deleteuseraccount_error")

	return Response({
		"success": True,
		"data": ""
	},status.HTTP_200_OK)

@api_view(["GET"])
def getauditlog(request):
	# 管理員查詢操作稽核紀錄（檢查表 1.7.2）。
	# 支援篩選：?userid=（操作者）、?tablename=（資料表，如 user/sessionplayer）、?recordid=（目標資料列）。
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")

	if not token:
		return errorresponse("ERROR_token_not_found")

	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return errorresponse("ERROR_token_error")

	operatorrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow[0]["userid"]],SETTING["dbsetting"])
	if not operatorrow or not (4<=int(operatorrow[0]["permission"])):
		return errorresponse("ERROR_no_permission")

	conditions=[]
	params=[]
	if request.GET.get("userid"):
		conditions.append("\"auditlog\".\"userid\"=%s")
		params.append(request.GET.get("userid"))
	if request.GET.get("tablename"):
		conditions.append("\"auditlog\".\"tablename\"=%s")
		params.append(request.GET.get("tablename"))
	if request.GET.get("action"):
		conditions.append("\"auditlog\".\"action\"=%s")
		params.append(request.GET.get("action"))
	if request.GET.get("recordid"):
		conditions.append("\"auditlog\".\"recordid\"=%s")
		params.append(request.GET.get("recordid"))
	where=(" WHERE "+" AND ".join(conditions)) if conditions else ""

	rows=query(SETTING["dbname"],f"""SELECT "auditlog".*,"user"."name" AS "username","user"."email" AS "useremail","user"."playerid" AS "userplayerid" FROM "auditlog" LEFT JOIN "user" ON "user"."id"="auditlog"."userid"{where} ORDER BY "auditlog"."id" DESC LIMIT 200""",params,SETTING["dbsetting"])
	return Response({
		"success": True,
		"data": rows
	},status.HTTP_200_OK)
@api_view(["GET"])
def getapilog(request):
	# 管理員查詢後端 API 呼叫紀錄（每次 API 請求都由 ApiLogMiddleware 寫入 apilog）。
	# 支援：?userid=（依使用者過濾）、?keyword=（比對使用者姓名/信箱/玩家編號、API 路徑、方法、IP）、?erroronly=1（只列狀態碼非 200 的紀錄）、?page=、?limit=（分頁，避免一次撈太多筆）。
	header=request.headers.get("Authorization")
	token=None

	try:
		if header:
			token=header.split("Bearer ")[1]
	except Exception as error:
		return errorresponse("ERROR_token_not_found")

	if not token:
		return errorresponse("ERROR_token_not_found")

	tokenrow=query(SETTING["dbname"],f"""SELECT*FROM "token" WHERE "token"=%s""",[token],SETTING["dbsetting"])
	if not tokenrow:
		return errorresponse("ERROR_token_error")

	operatorrow=query(SETTING["dbname"],f"""SELECT*FROM "user" WHERE "id"=%s AND "deletetime" IS NULL""",[tokenrow[0]["userid"]],SETTING["dbsetting"])
	if not operatorrow or not (4<=int(operatorrow[0]["permission"])):
		return errorresponse("ERROR_no_permission")

	try:
		page=max(1,int(request.GET.get("page") or 1))
	except Exception as error:
		page=1
	try:
		limit=max(1,min(200,int(request.GET.get("limit") or 20)))
	except Exception as error:
		limit=20

	conditions=[]
	params=[]
	if request.GET.get("userid"):
		conditions.append("\"apilog\".\"userid\"=%s")
		params.append(request.GET.get("userid"))
	if request.GET.get("keyword"):
		keyword="%"+request.GET.get("keyword")+"%"
		conditions.append("(\"user\".\"name\" ILIKE %s OR \"user\".\"email\" ILIKE %s OR \"user\".\"playerid\" ILIKE %s OR \"apilog\".\"path\" ILIKE %s OR \"apilog\".\"method\" ILIKE %s OR \"apilog\".\"ipaddress\"::text ILIKE %s)")
		params.append(keyword)
		params.append(keyword)
		params.append(keyword)
		params.append(keyword)
		params.append(keyword)
		params.append(keyword)
	if request.GET.get("erroronly")=="1":
		# statuscode 為 NULL 代表回應物件拿不到狀態碼，也視為異常一併列出
		conditions.append("(\"apilog\".\"statuscode\" IS NULL OR \"apilog\".\"statuscode\"<>200)")
	where=(" WHERE "+" AND ".join(conditions)) if conditions else ""

	countrow=query(SETTING["dbname"],f"""SELECT COUNT(*) AS "total" FROM "apilog" LEFT JOIN "user" ON "user"."id"="apilog"."userid"{where}""",params,SETTING["dbsetting"])
	total=int(countrow[0]["total"]) if countrow else 0

	totalpages=(total+limit-1)//limit
	if totalpages<=0:
		totalpages=1
	if totalpages<page:
		page=totalpages

	rows=query(SETTING["dbname"],f"""SELECT "apilog".*,"user"."name" AS "username","user"."email" AS "useremail","user"."playerid" AS "userplayerid" FROM "apilog" LEFT JOIN "user" ON "user"."id"="apilog"."userid"{where} ORDER BY "apilog"."id" DESC LIMIT %s OFFSET %s""",params+[limit,(page-1)*limit],SETTING["dbsetting"])
	return Response({
		"success": True,
		"data": {
			"logs": rows,
			"pagination": {
				"page": page,
				"limit": limit,
				"total": total,
				"totalpages": totalpages,
				"hasprev": 1<page,
				"hasnext": page<totalpages
			}
		}
	},status.HTTP_200_OK)
