/*
    Narrow solved preflop extras. Generated by gtosolvesblimp.py.
    Scope: HE 6MAX 100bb, one limper reaches BB.
    Non-SB limp ranges are explicit assumptions in the generator.
*/
let GTOSOLVEDDEEP={
    "HE_6MAX_100BB_UTGLIMP_BB": {
        "spot":"HULIMP_SOLVED",
        "matchup":"BBvUTGLIMP",
        "source":"gtosolvesblimp.py",
        "stackbb":100,
        "raise":["AA","AKs","AQs","AJs","ATs","A9s","A8s","AKo","KK","KQs","AQo","QQ","AJo","JJ","ATo","TT","99","88","77","66","55"],
        "check":["A7s","A6s","A5s","A4s","A3s","A2s","KJs","KTs","K9s","K8s","K7s","K6s","K5s","K4s","K3s","K2s","KQo","QJs","QTs","Q9s","Q8s","Q7s","Q6s","Q5s","Q4s","Q3s","Q2s","KJo","QJo","JTs","J9s","J8s","J7s","J6s","J5s","J4s","J3s","J2s","KTo","QTo","JTo","T9s","T8s","T7s","T6s","T5s","T4s","T3s","T2s","A9o","K9o","Q9o","J9o","T9o","98s","97s","96s","95s","94s","93s","92s","A8o","K8o","Q8o","J8o","T8o","98o","87s","86s","85s","84s","83s","82s","A7o","K7o","Q7o","J7o","T7o","97o","87o","76s","75s","74s","73s","72s","A6o","K6o","Q6o","J6o","T6o","96o","86o","76o","65s","64s","63s","62s","A5o","K5o","Q5o","J5o","T5o","95o","85o","75o","65o","54s","53s","52s","A4o","K4o","Q4o","J4o","T4o","94o","84o","74o","64o","54o","44","43s","42s","A3o","K3o","Q3o","J3o","T3o","93o","83o","73o","63o","53o","43o","33","32s","A2o","K2o","Q2o","J2o","T2o","92o","82o","72o","62o","52o","42o","32o","22"],
        "meta": {
            "iters":3000,
            "iso":4.0,
            "bbfactor":0.9696,
            "deadblind":0.5,
            "limpercall":["A5s","A4s","A3s","A2s","KQs","KJs","KTs","QJs","QTs","JTs","T9s","98s","87s","66","55","44","33","22"],
            "limperfold":[],
            "limpertokenlist":["66","55","44","33","22","A5s","A4s","A3s","A2s","KQs","KJs","KTs","QJs","QTs","JTs","T9s","98s","87s"]
        }
    },
    "HE_6MAX_100BB_MPLIMP_BB": {
        "spot":"HULIMP_SOLVED",
        "matchup":"BBvMPLIMP",
        "source":"gtosolvesblimp.py",
        "stackbb":100,
        "raise":["AA","AKs","AQs","AJs","ATs","A9s","A8s","AKo","KK","KQs","AQo","QQ","AJo","JJ","ATo","TT","99","88","77","66","55"],
        "check":["A7s","A6s","A5s","A4s","A3s","A2s","KJs","KTs","K9s","K8s","K7s","K6s","K5s","K4s","K3s","K2s","KQo","QJs","QTs","Q9s","Q8s","Q7s","Q6s","Q5s","Q4s","Q3s","Q2s","KJo","QJo","JTs","J9s","J8s","J7s","J6s","J5s","J4s","J3s","J2s","KTo","QTo","JTo","T9s","T8s","T7s","T6s","T5s","T4s","T3s","T2s","A9o","K9o","Q9o","J9o","T9o","98s","97s","96s","95s","94s","93s","92s","A8o","K8o","Q8o","J8o","T8o","98o","87s","86s","85s","84s","83s","82s","A7o","K7o","Q7o","J7o","T7o","97o","87o","76s","75s","74s","73s","72s","A6o","K6o","Q6o","J6o","T6o","96o","86o","76o","65s","64s","63s","62s","A5o","K5o","Q5o","J5o","T5o","95o","85o","75o","65o","54s","53s","52s","A4o","K4o","Q4o","J4o","T4o","94o","84o","74o","64o","54o","44","43s","42s","A3o","K3o","Q3o","J3o","T3o","93o","83o","73o","63o","53o","43o","33","32s","A2o","K2o","Q2o","J2o","T2o","92o","82o","72o","62o","52o","42o","32o","22"],
        "meta": {
            "iters":3000,
            "iso":4.0,
            "bbfactor":0.9696,
            "deadblind":0.5,
            "limpercall":["A7s","A6s","A5s","A4s","A3s","A2s","KQs","KJs","KTs","K9s","QJs","QTs","JTs","T9s","98s","87s","77","76s","66","55","44","33","22"],
            "limperfold":[],
            "limpertokenlist":["77","66","55","44","33","22","A7s","A6s","A5s","A4s","A3s","A2s","KQs","KJs","KTs","K9s","QJs","QTs","JTs","T9s","98s","87s","76s"]
        }
    },
    "HE_6MAX_100BB_COLIMP_BB": {
        "spot":"HULIMP_SOLVED",
        "matchup":"BBvCOLIMP",
        "source":"gtosolvesblimp.py",
        "stackbb":100,
        "raise":["AA","AKs","AQs","AJs","ATs","AKo","KK","AQo","QQ","AJo","JJ","TT","99","88","77","66","55"],
        "check":["A9s","A8s","A7s","A6s","A5s","A4s","A3s","A2s","KQs","KJs","KTs","K9s","K8s","K7s","K6s","K5s","K4s","K3s","K2s","KQo","QJs","QTs","Q9s","Q8s","Q7s","Q6s","Q5s","Q4s","Q3s","Q2s","KJo","QJo","JTs","J9s","J8s","J7s","J6s","J5s","J4s","J3s","J2s","ATo","KTo","QTo","JTo","T9s","T8s","T7s","T6s","T5s","T4s","T3s","T2s","A9o","K9o","Q9o","J9o","T9o","98s","97s","96s","95s","94s","93s","92s","A8o","K8o","Q8o","J8o","T8o","98o","87s","86s","85s","84s","83s","82s","A7o","K7o","Q7o","J7o","T7o","97o","87o","76s","75s","74s","73s","72s","A6o","K6o","Q6o","J6o","T6o","96o","86o","76o","65s","64s","63s","62s","A5o","K5o","Q5o","J5o","T5o","95o","85o","75o","65o","54s","53s","52s","A4o","K4o","Q4o","J4o","T4o","94o","84o","74o","64o","54o","44","43s","42s","A3o","K3o","Q3o","J3o","T3o","93o","83o","73o","63o","53o","43o","33","32s","A2o","K2o","Q2o","J2o","T2o","92o","82o","72o","62o","52o","42o","32o","22"],
        "meta": {
            "iters":3000,
            "iso":4.0,
            "bbfactor":0.9696,
            "deadblind":0.5,
            "limpercall":["A9s","A8s","A7s","KQs","KJs","KTs","K9s","KQo","QJs","QTs","Q9s","AJo","JTs","J9s","T9s","T8s","98s","88","87s","77","66","55","44","33","22"],
            "limperfold":["A6s","A5s","A4s","A3s","A2s","76s","65s"],
            "limpertokenlist":["88","77","66","55","44","33","22","A9s","A8s","A7s","A6s","A5s","A4s","A3s","A2s","KQs","KJs","KTs","K9s","QJs","QTs","Q9s","JTs","J9s","T9s","T8s","98s","87s","76s","65s","AJo","KQo"]
        }
    },
    "HE_6MAX_100BB_BTNLIMP_BB": {
        "spot":"HULIMP_SOLVED",
        "matchup":"BBvBTNLIMP",
        "source":"gtosolvesblimp.py",
        "stackbb":100,
        "raise":["AA","AKs","AQs","AJs","ATs","A9s","A8s","AKo","KK","KQs","AQo","QQ","AJo","JJ","ATo","TT","99","88","77","66","55"],
        "check":["A7s","A6s","A5s","A4s","A3s","A2s","KJs","KTs","K9s","K8s","K7s","K6s","K5s","K4s","K3s","K2s","KQo","QJs","QTs","Q9s","Q8s","Q7s","Q6s","Q5s","Q4s","Q3s","Q2s","KJo","QJo","JTs","J9s","J8s","J7s","J6s","J5s","J4s","J3s","J2s","KTo","QTo","JTo","T9s","T8s","T7s","T6s","T5s","T4s","T3s","T2s","A9o","K9o","Q9o","J9o","T9o","98s","97s","96s","95s","94s","93s","92s","A8o","K8o","Q8o","J8o","T8o","98o","87s","86s","85s","84s","83s","82s","A7o","K7o","Q7o","J7o","T7o","97o","87o","76s","75s","74s","73s","72s","A6o","K6o","Q6o","J6o","T6o","96o","86o","76o","65s","64s","63s","62s","A5o","K5o","Q5o","J5o","T5o","95o","85o","75o","65o","54s","53s","52s","A4o","K4o","Q4o","J4o","T4o","94o","84o","74o","64o","54o","44","43s","42s","A3o","K3o","Q3o","J3o","T3o","93o","83o","73o","63o","53o","43o","33","32s","A2o","K2o","Q2o","J2o","T2o","92o","82o","72o","62o","52o","42o","32o","22"],
        "meta": {
            "iters":3000,
            "iso":4.0,
            "bbfactor":0.9696,
            "deadblind":0.5,
            "limpercall":["A9s","A8s","A7s","A6s","A5s","A4s","A3s","A2s","KQs","KJs","KTs","K9s","K8s","K7s","K6s","K5s","KQo","QJs","QTs","Q9s","Q8s","AJo","KJo","QJo","JTs","J9s","J8s","ATo","T9s","T8s","98s","97s","88","87s","77","76s","66","55","44","33","22"],
            "limperfold":["65s","54s"],
            "limpertokenlist":["88","77","66","55","44","33","22","A9s","A8s","A7s","A6s","A5s","A4s","A3s","A2s","KQs","KJs","KTs","K9s","K8s","K7s","K6s","K5s","QJs","QTs","Q9s","Q8s","JTs","J9s","J8s","T9s","T8s","98s","97s","87s","76s","65s","54s","AJo","ATo","KQo","KJo","QJo"]
        }
    },
    "HE_6MAX_100BB_SBLIMP_BB": {
        "spot":"HULIMP_SOLVED",
        "matchup":"BBvSBLIMP",
        "source":"gtosolvesblimp.py",
        "stackbb":100,
        "raise":["AA","AKs","AQs","AJs","ATs","A9s","A8s","A7s","A6s","A5s","A4s","A3s","A2s","AKo","KK","KQs","KJs","KTs","K9s","K8s","K7s","K6s","K5s","K4s","K3s","K2s","AQo","KQo","QQ","QJs","QTs","Q9s","Q8s","Q7s","Q6s","Q5s","Q4s","Q3s","Q2s","AJo","KJo","QJo","JJ","JTs","J9s","J8s","J7s","J6s","J5s","J4s","J3s","J2s","ATo","KTo","QTo","JTo","TT","T9s","T8s","T7s","T6s","T4s","T3s","T2s","A9o","K9o","Q9o","J9o","T9o","99","98s","97s","96s","A8o","K8o","Q8o","J8o","T8o","98o","88","87s","86s","85s","84s","A7o","K7o","Q7o","J7o","77","76s","75s","A6o","K6o","Q6o","66","65s","64s","63s","A5o","K5o","Q5o","55","54s","53s","52s","A4o","K4o","Q4o","J4o","44","43s","42s","A3o","K3o","Q3o","J3o","33","32s","A2o","K2o","Q2o","J2o","22"],
        "check":["T5s","95s","94s","93s","92s","83s","82s","T7o","97o","87o","74s","73s","72s","J6o","T6o","96o","86o","76o","62s","J5o","T5o","95o","85o","75o","65o","T4o","94o","84o","74o","64o","54o","T3o","93o","83o","73o","63o","53o","43o","T2o","92o","82o","72o","62o","52o","42o","32o"],
        "meta": {
            "iters":3000,
            "iso":4.0,
            "bbfactor":1.0579,
            "deadblind":0.0,
            "limpercall":["K6s","K5s","K4s","K3s","K2s","Q7s","Q6s","Q5s","Q4s","Q3s","J7s","J6s","J5s","J4s","T7s","T6s","J9o","T9o","98s","97s","96s","K8o","Q8o","J8o","T8o","98o","87s","86s","K7o","Q7o","J7o","76s","A6o","K6o","Q6o","A5o","K5o","A4o","A3o","A2o"],
            "limperfold":["T5s","T4s","95s","94s","93s","85s","84s","83s","T7o","97o","87o","75s","74s","73s","96o","86o","76o","65s","64s","63s","75o","65o","54s","53s","54o","43s"],
            "limpertokenlist":["K2s-K6s","Q3s-Q7s","J4s-J7s","T4s-T7s","93s+","83s+","73s+","63s+","53s+","43s","A2o-A6o","K5o-K8o","Q6o-Q8o","J7o-J9o","T7o-T9o","96o+","86o+","75o+","65o","54o"]
        }
    }
}
