/*
	製作人員: 賀皓群(小賀) / dc: chris0527 / line: ho960527 / email: chris960527ho@gmail.com / 電話: 0906585605

		|-------    -----    -                     -     -----  -----  -----   -------|
	   |-------    -        -            - - -          -                     -------|
	  |-------    -        -------    -          -     -----    --       --  -------|
	 |-------    -        -     -    -          -         -      --     --  -------|
	|-------    -----    -     -    -          -     -----         -----  -------|

	無授權禁止拷貝使用!
*/

const TRANSLATE={
	"zhtw": {
		"api": {
			"signin": {
				"success": "登入成功"
			},
			"signup": {
				"success": "註冊成功"
			},
			"signout": {
				"success": "登出成功"
			},
		},
		"adminuser": {
			"name": "名稱",
			"permission": "權限",
			"function": "功能區",
			"ban": "封禁",
			"delete": "刪除",
			"editpermission": "修改權限"
		},
		"navigationbar": {
			"index": "首頁",
			"signin": "登入",
			"signup": "註冊",
			"signout": "登出",
			"profile": "個人資料",
			"club": "協會管理",
			"session": "場次列表",
			"benefit": "收益折線圖",
			"back": "返回",
			"main": "專案主頁",
			"adminuser": "使用者管理",
			"newproject": "新增專案",
			"newapi": "新增API"
		},
		"footer": {
			"privacy": "隱私權政策",
			"terms": "服務條款",
			"contact": "聯絡我們"
		},
		"index": {
			"index": "首頁",
			"signin": "登入",
			"signup": "註冊",
			"adminuser": "管理使用者"
		},
		"gametype": {
			"cash": "現金局",
			"tournament": "錦標賽",
			"limited": "限時錦標賽",
		},
		"seatingtype": {
			"buyin": "買入",
			"rebuy": "重新買入",
			"leave": "離席",
		},
		"seating": {
			"CO": "關煞(CO)",
			"HJ": "劫位(HJ)",
			"BTN": "莊家(BTN)",
			"SB": "小盲",
			"BB": "大盲",
			"UTG": "槍口(UTG)",
			"UTG+1": "槍口+1",
			"UTG+2": "槍口+2",
			"MP": "中位(MP)",
			"MP+1": "中位+1",
		},
		"projectandapi": {
			"newapi": "新增api",
			"back": "返回",
			"index": "首頁",
			"signout": "登出",
			"copyrootlink": "複製根目錄連結",
			"editproject": "修改專案",
			"deleteproject": "刪除專案",
			"copylink": "複製連結",
			"editapi": "修改api",
			"deleteapi": "刪除api",
			"newproject": "新增專案",
			"projecttitle": "專案名稱",
			"projectdescription": "專案描述",
			"projectrootlink": "專案根目錄",
			"projectpermission": "專案權限",
			"projectpermissionpublic": "公開",
			"projectpermissioninvite": "邀請",
			"projectpermissionprivate": "私人",
			"projecttype": "專案權限類型",
			"projecttypeedit": "編輯",
			"projecttypeadd": "新增",
			"projecttypeview": "查看",
			"testapi": "發送測試",
			"setpermission": "設定權限"
		},
		"errorlist": {
			"ERROR_request_mimes_type_error": "檔案需為圖片",
			"ERROR_request_data_not_found": "缺少必填資料",
			"ERROR_request_data_type_error": "資料型態錯誤",
			"ERROR_password_error": "密碼錯誤",
			"ERROR_username_error": "使用者名稱錯誤",
			"ERROR_username_exist": "使用者名稱已存在",
			"ERROR_token_error": "token錯誤",
			"ERROR_token_not_found": "找不到token",
			"ERROR_no_permission": "沒有權限",
			"ERROR_user_not_found": "找不到使用者",
			"ERROR_session_not_found": "找不到場次",
			"ERROR_product_not_found": "找不到此商品",
			"ERROR_phone_exist": "手機號碼已存在",
			"ERROR_email_exist": "電子郵件已存在"
		},
		"breadcrumb": {
			"index": "專案主頁",
			"newapi": "新增API"
		},
		"warning": {
			"exitpage": "確定要離開嗎,將丟失未儲存的內容"
		},
		"type": {
			"game": {
				"HE": "德州撲克(Hold'em)",
				"OM": "奧馬哈(Omaha)",
				"ST": "梭哈(Stud)",
				"MX": "混合遊戲(Mixed up)",
				"O8": "奧馬哈高低",
				"O5": "5張奧馬哈",
				"BO": "5張奧馬哈高低(Big O)",
				"ST": "7張梭哈",
				"RA": "7張梭哈低牌",
				"S8": "7張梭哈高低",
				"CP": "瘋狂菠蘿",
				"SH": "超級德州(三卡賽)",
				"BU": "巴杜基",
				"AS": "A-5單次換牌",
				"AD": "A-5兩次換牌",
				"AT": "A-5三次換牌",
				"DS": "2-7單次換牌",
				"DD": "2-7兩次換牌",
				"DT": "2-7三次換牌",
				"ZZ": "其他(Other) "
			},
			"limit": {
				"NL": "無限注(no limit)",
				"PL": "底池限注(pot limit)",
				"FL": "固定注(fixed limit)"
			},
			"stack": {
				"N": "正常(normal)",
				"D": "深籌(deep)",
				"L": "深籌(moster)",
				"S": "極深籌(super)",
				"M": "巨籌(mega)",
				"U": "極巨籌(ultra)",
			},
			"event": {
				"OD": "單日賽",
				"SA": "衛星賽",
				"Milestone Satellite": "里程碑衛星賽",
				"ND": "多日賽"
			}
		},
		"mainpage": {
			"title": "主儀表板",
			"todayprofit": "今日盈虧",
			"weekprofit": "本週盈虧",
			"monthprofit": "本月盈虧",
			"weeklytrend": "個人前週盈虧趨勢圖",
			"profit": "盈虧",
			"networkerror": "網路不佳，請重新嘗試"
		},
		"profile": {
			"title": "個人資料",
			"playerid": "玩家 ID",
			"monthreport": "月報表",
			"yearreport": "年報表",
			"allreport": "生涯報表",
			"selectmonth": "選擇年月：",
			"selectyear": "選擇年份：",
			"includefee": "盈虧計算包含服務費",
			"includefeedesc": "取消勾選後，盈虧只算買入金額本身",
			"cash": "現金桌",
			"tlt": "限時錦標賽",
			"mtt": "錦標賽",
			"games": "局數",
			"sessions": "場次",
			"totalbuyin": "總買入",
			"totalprofit": "總收益",
			"buyincount": "總組數",
			"reporttotal": "總盈虧",
			"staff": "聘用人員",
			"employed": "已聘用",
			"dealer": "發牌員",
			"floor": "裁判",
			"assistant": "助理",
			"manage": "管理",
			"language": "選擇語言",
			"chinese": "中文",
			"english": "英文",
			"localtimer": "簡易本地計時器",
			"refereecontrol": "裁判控制台",
			"staffmodalcurrent": "目前名單",
			"staffmodaladd": "新增",
			"staffmodalclose": "關閉",
			"staffinputplaceholder": "輸入使用者 ID（e.g. P-00099）",
			"empty": "尚無成員",
			"unemployed": "目前尚未被任何玩家聘用。",
			"unnamed": "未命名玩家",
			"pending": "待確認",
			"tokenexpired": "權杖已失效，請重新登入",
			"networkerror": "網路不佳，請重新嘗試",
			"invitesent": "已寄出邀請信給 ",
			"targetuser": "該使用者",
			"usernotfound": "找不到該使用者",
			"rolemismatch": "該使用者的帳號類型與此職位不符",
			"alreadyinvited": "此使用者已經在名單中",
			"selfinvite": "不能邀請自己",
			"unknownerror": "未知錯誤",
			"removeconfirm": "確定要移除此員工嗎?"
		},
		"clublist": {
			"title": "協會管理",
			"searchplaceholder": "搜尋協會名稱",
			"search": "搜尋",
			"addclub": "新增協會",
			"name": "協會名稱",
			"address": "協會地址",
			"note": "註解",
			"action": "操作",
			"stats": "協會統計",
			"totalclubs": "總協會數",
			"displaycount": "顯示數量",
			"edit": "編輯",
			"delete": "刪除",
			"cancel": "取消",
			"editclub": "編輯協會",
			"deleteconfirm": "確定刪除此協會?",
			"deletesuccess": "刪除成功",
			"deletefail": "刪除失敗",
			"addsuccess": "新增成功",
			"editsuccess": "修改成功",
			"operationfail": "操作失敗",
			"tokenexpired": "權限已失效,請重新登入",
			"unknownerror": "未知錯誤"
		},
		"sessionlist": {
			"title": "場次管理",
			"startdate": "開始日期",
			"enddate": "結束日期",
			"selectclub": "-- 請選擇 --",
			"allgametype": "全部遊戲類型",
			"name": "名稱",
			"search": "搜尋",
			"newsession": "新增場次",
			"stats": "場次統計預覽",
			"gamecount": "總場次",
			"totalprofit": "總盈虧",
			"avgduration": "平均時長",
			"time": "時間",
			"buyin": "買入",
			"place": "名次",
			"profit": "盈虧",
			"action": "操作",
			"entryfee": "入場費",
			"owner": "主辦",
			"staff": "已聘用",
			"registered": "已報名",
			"confirmed": "已確認",
			"registerable": "可報名",
			"unregister": "取消報名",
			"register": "報名此場次",
			"displaytimer": "顯示計時器",
			"structure": "查看結構",
			"timer": "計時器",
			"copy": "複製",
			"edit": "編輯",
			"delete": "刪除",
			"minute": "分鐘",
			"hour": "小時",
			"registersuccess": "報名成功, 等待主辦確認",
			"alreadyregistered": "您已經報名過了",
			"cannotown": "不能報名自己主辦的場次",
			"notopen": "此場次未開放報名",
			"unknownerror": "未知錯誤",
			"unregisterconfirm": "確定要取消報名嗎?",
			"unregistersuccess": "已取消報名",
			"deleteconfirm": "確定刪除?",
			"deletesuccess": "刪除成功",
			"tokenexpired": "權限已失效，請重新登入",
			"networkerror": "網路不佳，請重新嘗試"
		},
		"benefit": {
			"title": "收益圖表",
			"startdate": "開始日期",
			"enddate": "結束日期",
			"search": "查詢",
			"reset": "重置",
			"dailyprofit": "當日收益",
			"cumulativeprofit": "累計收益",
			"date": "日期",
			"amount": "金額",
			"minute": "分鐘",
			"hour": "小時",
			"networkerror": "網路不佳，請重新嘗試"
		},
		"default": "預設模式",
		"coding": "程式碼模式",
		"clearall": "清空全部",
		"reset": "重設",
		"back": "返回",
		"signout": "登出",
		"submit": "送出",
		"confirm": "確認",
		"clearallconfirm": "確認清空全部?",
		"clearallconfirmdescription": "此操作將清空所有內容並不能復原,請確認是否繼續?",
		"resetconfirm": "確認重設?",
		"resetconfirmdescription": "此操作將重設所有內容並不能復原,請確認是否繼續?",
		"deleteconfirm": "確認刪除",
		"deleteconfirmdescription": "此操作將刪除該項目",
		"copyed": "已複製"
	},
	"en": {
		"api": {
			"signin": {
				"success": "signin successful"
			},
			"signup": {
				"success": "signup successful"
			},
			"signout": {
				"success": "signout successful"
			},
		},
		"adminuser": {
			"name": "Name",
			"permission": "Permission",
			"function": "Function",
			"ban": "Ban",
			"delete": "Delete",
			"editpermission": "Edit Permission"
		},
		"navigationbar": {
			"index": "Home",
			"signin": "SignIn",
			"signup": "SignUp",
			"signout": "SignOut",
			"profile": "Profile",
			"club": "Club",
			"session": "Session",
			"benefit": "Benefit",
			"back": "Back",
			"main": "Project Home",
			"adminuser": "User Management",
			"newproject": "New Project",
			"newapi": "New API"
		},
		"footer": {
			"privacy": "Privacy Policy",
			"terms": "Terms of Service",
			"contact": "Contact Us"
		},
		"index": {
			"index": "Home",
			"signin": "SignIn",
			"signup": "SignUp",
			"adminuser": "User Management"
		},
		"gametype": {
			"cash": "Cash Game",
			"tournament": "Tournament",
			"limited": "Time Limited Tournament",
		},
		"seatingtype": {
			"buyin": "Buy In",
			"rebuy": "Rebuy",
			"leave": "Leave",
		},
		"seating": {
			"CO": "CO",
			"HJ": "HJ",
			"BTN": "BTN",
			"SB": "SB",
			"BB": "BB",
			"UTG": "UTG",
			"UTG+1": "UTG+1",
			"UTG+2": "UTG+2",
			"MP": "MP",
			"MP+1": "MP+1",
		},
		"errorlist": {
			"ERROR_request_mimes_type_error": "File must be an image",
			"ERROR_request_data_not_found": "Missing required data",
			"ERROR_request_data_type_error": "Data type error",
			"ERROR_password_error": "Password error",
			"ERROR_username_error": "Username error",
			"ERROR_username_exist": "Username already exists",
			"ERROR_token_error": "token error",
			"ERROR_token_not_found": "token not found",
			"ERROR_no_permission": "No permission",
			"ERROR_user_not_found": "User not found",
			"ERROR_session_not_found": "Session not found",
			"ERROR_product_not_found": "Product not found",
			"ERROR_phone_exist": "Phone number already exists",
			"ERROR_email_exist": "Email already exists"
		},
		"warning": {
			"exitpage": "Are you sure to leave? Unsaved content will be lost."
		},
		"type": {
			"game": {
				"HE": "Texas Hold'em",
				"O": "Omaha",
				"ST": "Stud",
				"MX": "Mixed up",
				"Z": "Other"
			},
			"limit": {
				"NL": "No limit",
				"PL": "Pot limit",
				"FL": "Fixed limit"
			},
			"stack": {
				"N": "Normal",
				"D": "Deep",
				"L": "Moster",
				"S": "Super",
				"M": "Mega",
				"U": "Ultra",
			},
			"event": {
				"OD": "Single Day",
				"SA": "Satellite",
				"ND": "Multiple Day"
			}
		},
		"mainpage": {
			"title": "Dashboard",
			"todayprofit": "Today Profit",
			"weekprofit": "This Week Profit",
			"monthprofit": "This Month Profit",
			"weeklytrend": "Personal Weekly Profit Trend",
			"profit": "Profit",
			"networkerror": "Network error, please try again"
		},
		"profile": {
			"title": "Profile",
			"playerid": "Player ID",
			"monthreport": "Monthly",
			"yearreport": "Yearly",
			"allreport": "Career",
			"selectmonth": "Select month:",
			"selectyear": "Select year:",
			"includefee": "Include service fees in profit",
			"includefeedesc": "When unchecked, profit only uses buy-in amounts",
			"cash": "Cash Game",
			"tlt": "Time Limited Tournament",
			"mtt": "Tournament",
			"games": "Games",
			"sessions": "Sessions",
			"totalbuyin": "Total Buy-in",
			"totalprofit": "Total Profit",
			"buyincount": "Total Entries",
			"reporttotal": "Total Profit",
			"staff": "Staff",
			"employed": "Employed By",
			"dealer": "Dealer",
			"floor": "Floor",
			"assistant": "Assistant",
			"manage": "Manage",
			"language": "Language",
			"chinese": "Chinese",
			"english": "English",
			"localtimer": "Local Timer",
			"refereecontrol": "Referee Control Panel",
			"staffmodalcurrent": "Current List",
			"staffmodaladd": "Add",
			"staffmodalclose": "Close",
			"staffinputplaceholder": "Enter user ID (e.g. P-00099)",
			"empty": "No members",
			"unemployed": "This user is not employed by any player yet.",
			"unnamed": "Unnamed player",
			"pending": "Pending",
			"tokenexpired": "Token expired, please sign in again",
			"networkerror": "Network error, please try again",
			"invitesent": "Invitation sent to ",
			"targetuser": "this user",
			"usernotfound": "User not found",
			"rolemismatch": "This user's account type does not match this role",
			"alreadyinvited": "This user is already on the list",
			"selfinvite": "You cannot invite yourself",
			"unknownerror": "Unknown error",
			"removeconfirm": "Remove this staff member?"
		},
		"clublist": {
			"title": "Club Management",
			"searchplaceholder": "Search club name",
			"search": "Search",
			"addclub": "Add Club",
			"name": "Club Name",
			"address": "Club Address",
			"note": "Note",
			"action": "Actions",
			"stats": "Club Stats",
			"totalclubs": "Total Clubs",
			"displaycount": "Displayed",
			"edit": "Edit",
			"delete": "Delete",
			"cancel": "Cancel",
			"editclub": "Edit Club",
			"deleteconfirm": "Delete this club?",
			"deletesuccess": "Deleted",
			"deletefail": "Delete failed",
			"addsuccess": "Added",
			"editsuccess": "Updated",
			"operationfail": "Operation failed",
			"tokenexpired": "Permission expired, please sign in again",
			"unknownerror": "Unknown error"
		},
		"sessionlist": {
			"title": "Session List",
			"startdate": "Start Date",
			"enddate": "End Date",
			"selectclub": "-- Select --",
			"allgametype": "All Game Types",
			"name": "Name",
			"search": "Search",
			"newsession": "New Session",
			"stats": "Session Stats",
			"gamecount": "Total Sessions",
			"totalprofit": "Total Profit",
			"avgduration": "Average Duration",
			"time": "Time",
			"buyin": "Buy-in",
			"place": "Place",
			"profit": "Profit",
			"action": "Actions",
			"entryfee": "Entry Fee",
			"owner": "Owner",
			"staff": "Employed",
			"registered": "Registered",
			"confirmed": "Confirmed",
			"registerable": "Open",
			"unregister": "Cancel Registration",
			"register": "Register",
			"displaytimer": "Display Timer",
			"timer": "Timer",
			"copy": "Copy",
			"edit": "Edit",
			"delete": "Delete",
			"minute": "min",
			"hour": "hr",
			"registersuccess": "Registered, waiting for host confirmation",
			"alreadyregistered": "You have already registered",
			"cannotown": "You cannot register for your own session",
			"notopen": "This session is not open for registration",
			"unknownerror": "Unknown error",
			"unregisterconfirm": "Cancel this registration?",
			"unregistersuccess": "Registration cancelled",
			"deleteconfirm": "Delete this session?",
			"deletesuccess": "Deleted",
			"tokenexpired": "Permission expired, please sign in again",
			"networkerror": "Network error, please try again"
		},
		"benefit": {
			"title": "Benefit Chart",
			"startdate": "Start Date",
			"enddate": "End Date",
			"search": "Search",
			"reset": "Reset",
			"dailyprofit": "Daily Profit",
			"cumulativeprofit": "Cumulative Profit",
			"date": "Date",
			"amount": "Amount",
			"minute": "min",
			"hour": "hr",
			"networkerror": "Network error, please try again"
		},
		"default": "Default Mode",
		"clearall": "Clear All",
		"signout": "Sign Out",
		"reset": "Reset",
		"back": "Back",
		"submit": "Submit",
		"confirm": "Confirm",
		"clearallconfirm": "Confirm Clear All?",
		"clearallconfirmdescription": "This action will clear all content and cannot be undone. Please confirm if you wish to continue?",
		"resetconfirm": "Confirm Reset?",
		"resetconfirmdescription": "This action will reset all content and cannot be undone. Please confirm if you wish to continue?",
		"deleteconfirm": "Confirm Delete",
		"deleteconfirmdescription": "This action will delete the item",
		"copyed": "Copied"
	}
}
