# dbinitialize.py
# ===========================================================================
# 啟動專案時會由 runserver.cmd 先執行此檔, 確保資料庫 schema 與字典預設資料就緒
# 設計準則:
#     1. 全部 CREATE TABLE 都用 IF NOT EXISTS, 已存在的表不會被破壞
#     2. 字典表預設資料用 ON CONFLICT DO NOTHING 安全插入
#     3. 連線資訊請與 api/initialize.py 同步
# ===========================================================================

import os
import psycopg2
import sys

# NSSM/主控台重導輸出時預設編碼可能是 cp1252, print 中文會 UnicodeEncodeError 使啟動失敗
try:
	sys.stdout.reconfigure(encoding="utf-8",errors="replace")
	sys.stderr.reconfigure(encoding="utf-8",errors="replace")
except Exception:
	pass

# 與 backend/api/initialize.py 對齊的連線設定（測試機用 pokertrace_test）
DBNAME="pokertrace_test"
DBHOST="localhost"
DBUSER="chris0527"
DBPASSWORD=os.environ.get("PT_DB_PASSWORD","")
DBPORT=5432

# ---------------------------------------------------------------------------
# Schema DDL
# ---------------------------------------------------------------------------
SCHEMASQL=r"""
-- 幣別字典
CREATE TABLE IF NOT EXISTS public.currency(
	code varchar(10) PRIMARY KEY,
	name varchar(50) NOT NULL,
	symbol varchar(10),
	decimals integer NOT NULL DEFAULT 2,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 遊戲類型字典
CREATE TABLE IF NOT EXISTS public.gametype(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	code varchar(20) NOT NULL UNIQUE,
	description text,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 限注類型字典
CREATE TABLE IF NOT EXISTS public.limittype(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	code varchar(20) NOT NULL UNIQUE,
	description text,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 計分牌類型字典
CREATE TABLE IF NOT EXISTS public.stacktype(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	code varchar(20) NOT NULL UNIQUE,
	description text,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 賽事類型字典
CREATE TABLE IF NOT EXISTS public.eventtype(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50) NOT NULL,
	code varchar(20) NOT NULL UNIQUE,
	description text,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 匯率
CREATE TABLE IF NOT EXISTS public.fxrate(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	basecurrency varchar(10) NOT NULL,
	quotecurrency varchar(10) NOT NULL,
	rate numeric(18,8) NOT NULL,
	asofdate date NOT NULL,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 組織/俱樂部
CREATE TABLE IF NOT EXISTS public.org(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) NOT NULL,
	description text,
	timezone varchar(50) DEFAULT 'UTC',
	currency varchar(10) DEFAULT 'USD',
	status varchar(20) DEFAULT 'active',
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 使用者
CREATE TABLE IF NOT EXISTS public."user"(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	orgid bigint,
	uid varchar(50) NOT NULL UNIQUE,
	email varchar(100) NOT NULL UNIQUE,
	name varchar(100),
	avatarurl varchar(255),
	userlevel varchar(20) DEFAULT 'beginner',
	totalhands integer DEFAULT 0,
	lastlogin timestamp with time zone,
	verified boolean DEFAULT true,
	phone varchar(20),
	verifytoken varchar(50),
	token varchar(50) NOT NULL,
	country varchar(50),
	timezone varchar(50),
	language varchar(10) NOT NULL DEFAULT 'zhtw',
	privacylevel varchar(20) DEFAULT 'public',
	permission integer NOT NULL DEFAULT 1,
	playerid varchar(8) NOT NULL DEFAULT '0',
	type varchar(50) DEFAULT '',
	carddeck varchar(20) NOT NULL DEFAULT 'classic',
	potmainside varchar(10) NOT NULL DEFAULT 'right',
	chipcolors text NOT NULL DEFAULT '[{"name":"白色","color":"#ffffff"},{"name":"紅色","color":"#ff0000"},{"name":"藍色","color":"#0000ff"},{"name":"綠色","color":"#008000"},{"name":"黑色","color":"#000000"},{"name":"黃色","color":"#ffff00"},{"name":"橘色","color":"#ffa500"},{"name":"紫色","color":"#800080"},{"name":"粉紅色","color":"#ffc0cb"},{"name":"灰色","color":"#808080"}]',
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

ALTER TABLE public."user" ADD COLUMN IF NOT EXISTS chipcolors text NOT NULL DEFAULT '[{"name":"白色","color":"#ffffff"},{"name":"紅色","color":"#ff0000"},{"name":"藍色","color":"#0000ff"},{"name":"綠色","color":"#008000"},{"name":"黑色","color":"#000000"},{"name":"黃色","color":"#ffff00"},{"name":"橘色","color":"#ffa500"},{"name":"紫色","color":"#800080"},{"name":"粉紅色","color":"#ffc0cb"},{"name":"灰色","color":"#808080"}]';
ALTER TABLE public."user" ADD COLUMN IF NOT EXISTS carddeck varchar(20) NOT NULL DEFAULT 'classic';
ALTER TABLE public."user" ADD COLUMN IF NOT EXISTS potmainside varchar(10) NOT NULL DEFAULT 'right';

-- 聯絡我們訊息
CREATE TABLE IF NOT EXISTS public.contactmessage(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint,
	name varchar(100) NOT NULL,
	email varchar(150) NOT NULL,
	subject varchar(150) NOT NULL DEFAULT '',
	message text NOT NULL,
	status varchar(20) NOT NULL DEFAULT 'new',
	replysubject varchar(150) NOT NULL DEFAULT '',
	replymessage text NOT NULL DEFAULT '',
	replytime timestamp with time zone,
	replyuserid bigint,
	ip varchar(80) NOT NULL DEFAULT '',
	useragent text NOT NULL DEFAULT '',
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);
ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replysubject varchar(150) NOT NULL DEFAULT '';
ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replymessage text NOT NULL DEFAULT '';
ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replytime timestamp with time zone;
ALTER TABLE public.contactmessage ADD COLUMN IF NOT EXISTS replyuserid bigint;

-- Token
CREATE TABLE IF NOT EXISTS public.token(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	token varchar(50) NOT NULL,
	createtime timestamp with time zone NOT NULL DEFAULT now()
);

-- 封鎖/停權紀錄（api/user.py banuser/blockuser 寫入、authhelper.getuserbanned 判定、unbanuser 解除）
-- 欄位語意：userid=操作的管理員、blockbanuserid=被封禁者、type='ban'(永久,time='inf')或'block'、time 存文字。硬刪、無 deletetime。
CREATE TABLE IF NOT EXISTS public.blockbanuser(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	blockbanuserid bigint NOT NULL,
	reason text NOT NULL DEFAULT '',
	type varchar(20) NOT NULL DEFAULT 'block',
	time varchar(50) NOT NULL DEFAULT '',
	createtime timestamp with time zone NOT NULL DEFAULT now()
);

-- 俱樂部
CREATE TABLE IF NOT EXISTS public.club(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	name varchar NOT NULL,
	address varchar NOT NULL,
	ps varchar NOT NULL,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 場次
CREATE TABLE IF NOT EXISTS public.session(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	orgid bigint,
	name varchar(100) NOT NULL,
	description text,
	starttime timestamp with time zone NOT NULL DEFAULT '2025-09-07 11:00:00+00',
	endtime timestamp with time zone NOT NULL DEFAULT '2025-09-07 11:00:00+00',
	buyin numeric NOT NULL DEFAULT 600,
	chip numeric NOT NULL DEFAULT 20000,
	gametype varchar NOT NULL DEFAULT 'limited',
	token varchar(15),
	buyinfee numeric DEFAULT 0,
	rebuycount bigint,
	rebuybuyin numeric,
	rebuyfee numeric DEFAULT 0,
	rebuychip numeric DEFAULT 0,
	reentrycount bigint DEFAULT 0,
	reentrybuyin numeric DEFAULT 0,
	reentryfee numeric DEFAULT 0,
	reentrychip numeric DEFAULT 0,
	addoncount bigint DEFAULT 0,
	addonbuyin numeric DEFAULT 0,
	addonfee numeric DEFAULT 0,
	addonchip numeric DEFAULT 0,
	linkuser boolean NOT NULL DEFAULT false,
	winprice numeric,
	winthing text,
	inmoney boolean NOT NULL DEFAULT false,
	inft boolean NOT NULL DEFAULT false,
	clubid bigint NOT NULL,
	tablelinked boolean NOT NULL DEFAULT false,
	parentid bigint,
	relationtype varchar(20) NOT NULL DEFAULT 'normal',
	ticketenabled boolean NOT NULL DEFAULT false,
	ticketvalue numeric DEFAULT 0,
	antemode varchar(20) NOT NULL DEFAULT 'bigblindante',
	unifiedhandrecord boolean NOT NULL DEFAULT false,
	openregistration boolean NOT NULL DEFAULT false,
	guaranteedprize numeric DEFAULT 0,
	private boolean NOT NULL DEFAULT false,
	place varchar DEFAULT '0',
	totalbuyin varchar DEFAULT '0',
	gametypeid bigint NOT NULL DEFAULT 1,
	limittypeid bigint NOT NULL DEFAULT 1,
	stacktypeid bigint NOT NULL DEFAULT 1,
	eventtypeid bigint NOT NULL DEFAULT 1,
	owned boolean NOT NULL DEFAULT false,
	maxseat bigint NOT NULL DEFAULT 9,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- session 表新欄位 (處理既有資料庫沒有這些欄位的情況)
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS buyinfee numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS rebuyfee numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS rebuychip numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS reentrycount bigint DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS reentrybuyin numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS reentryfee numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS reentrychip numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS addoncount bigint DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS addonbuyin numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS addonfee numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS addonchip numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS linkuser boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS inmoney boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS inft boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS parentid bigint;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS relationtype varchar(20) NOT NULL DEFAULT 'normal';
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS ticketenabled boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS ticketvalue numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS antemode varchar(20) NOT NULL DEFAULT 'bigblindante';
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS unifiedhandrecord boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS openregistration boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS guaranteedprize numeric DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS private boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS maxseat bigint NOT NULL DEFAULT 9;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS raisecap bigint NOT NULL DEFAULT 4;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS brandname varchar(120) DEFAULT '';
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS brandcolor varchar(20) DEFAULT '';
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS brandlogo text DEFAULT '';
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS displayfields varchar(300) DEFAULT '';
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS broadcastopen boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS broadcastdelay integer NOT NULL DEFAULT 0;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS broadcastshowcard boolean NOT NULL DEFAULT true;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS broadcasth4h boolean NOT NULL DEFAULT false;
ALTER TABLE public.session ADD COLUMN IF NOT EXISTS broadcastreleasedcount integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.sessionrelation(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sourceid bigint NOT NULL,
	targetid bigint NOT NULL,
	relationtype varchar(20) NOT NULL,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone,
	UNIQUE(sourceid,targetid,relationtype)
);

-- 系列賽: 把多個 session 歸成一包, 做彙總統計與排名
CREATE TABLE IF NOT EXISTS public.series(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	clubid bigint,
	name varchar(100) NOT NULL,
	description text,
	starttime timestamp with time zone,
	endtime timestamp with time zone,
	token varchar(15),
	scoringtype varchar(20) NOT NULL DEFAULT 'profit',
	private boolean NOT NULL DEFAULT false,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 系列賽成員: 哪些 session 屬於哪個系列賽 (中介表, 同一 session 可掛多個系列賽)
CREATE TABLE IF NOT EXISTS public.seriessession(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	seriesid bigint NOT NULL,
	sessionid bigint NOT NULL,
	sortorder bigint NOT NULL DEFAULT 0,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone,
	UNIQUE(seriesid,sessionid)
);

-- 桌次
CREATE TABLE IF NOT EXISTS public."table"(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL,
	no integer,
	name varchar(100),
	token varchar(20),
	firstdealerplace bigint DEFAULT 1,
	selfseating bigint DEFAULT 1,
	closedtime timestamp with time zone,
	createtime timestamp with time zone DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);
ALTER TABLE public."table" ADD COLUMN IF NOT EXISTS no integer;
-- CREATE TABLE 有宣告 name, 但早期建立的資料庫沒有這欄, 少了 ALTER 會造成新舊環境結構不一致
ALTER TABLE public."table" ADD COLUMN IF NOT EXISTS name varchar(100);
ALTER TABLE public."table" ADD COLUMN IF NOT EXISTS firstdealerplace bigint DEFAULT 1;
ALTER TABLE public."table" ADD COLUMN IF NOT EXISTS selfseating bigint DEFAULT 1;
-- 牌桌關閉時間: NULL=開放中, 有值=已關閉(不再讓新選手進桌)
ALTER TABLE public."table" ADD COLUMN IF NOT EXISTS closedtime timestamp with time zone;

CREATE TABLE IF NOT EXISTS public.sessionchip(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL,
	shape varchar(20) NOT NULL DEFAULT 'circle',
	value bigint NOT NULL DEFAULT 0,
	color varchar(20) NOT NULL DEFAULT '#888888',
	sortorder integer NOT NULL DEFAULT 0,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 座位 (table 上的玩家就座記錄)
CREATE TABLE IF NOT EXISTS public.seating(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tableid bigint NOT NULL,
	seatno integer NOT NULL,
	buyin bigint NOT NULL,
	"time" timestamp with time zone NOT NULL DEFAULT now(),
	name varchar(25),
	type varchar(20),
	chip numeric,
	userid bigint,
	sessionplayerid bigint,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 玩家
CREATE TABLE IF NOT EXISTS public.player(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	orgid bigint NOT NULL,
	userid bigint,
	nickname varchar(100) NOT NULL,
	externalref varchar(100),
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 手牌 (事件溯源核心)
CREATE TABLE IF NOT EXISTS public.hand(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tableid bigint NOT NULL,
	token varchar(50) NOT NULL,
	dealerseat integer NOT NULL,
	selfseating bigint DEFAULT 0,
	handcard varchar,
	userid bigint,
	totalpot numeric,
	boardcard varchar,
	gametype varchar NOT NULL DEFAULT 'holdem',
	blindlevel varchar,
	smallblind numeric DEFAULT 0,
	bigblind numeric DEFAULT 0,
	bigblindante numeric DEFAULT 0,
	ante numeric DEFAULT 0,
	emptybutton boolean NOT NULL DEFAULT false,
	deadsmallblind boolean NOT NULL DEFAULT false,
	ps varchar,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 手牌動作 (事件)
CREATE TABLE IF NOT EXISTS public.handbittingdata(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	handid bigint NOT NULL,
	seatno bigint,
	blinded boolean NOT NULL DEFAULT false,
	timebank bigint DEFAULT 0,
	bbed boolean DEFAULT false,
	chip numeric NOT NULL DEFAULT 0,
	type varchar,
	action varchar,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 手牌參與玩家
CREATE TABLE IF NOT EXISTS public.handseating(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	handid bigint NOT NULL,
	seatno integer NOT NULL,
	chip numeric NOT NULL,
	endchip numeric,
	handcard varchar,
	banned boolean DEFAULT false,
	chipchange numeric,
	winnered boolean DEFAULT false,
	name varchar,
	userid bigint,
	sessionplayerid bigint,
	specialbutton varchar,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 玩家底牌
CREATE TABLE IF NOT EXISTS public.handplayercard(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	handid bigint NOT NULL,
	playerid bigint NOT NULL,
	card1 varchar(3),
	card2 varchar(3),
	revealed boolean NOT NULL DEFAULT false,
	note text NOT NULL DEFAULT '',
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 公共牌
CREATE TABLE IF NOT EXISTS public.communitycard(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	handid bigint NOT NULL,
	runno integer NOT NULL DEFAULT 1,
	street varchar(10) NOT NULL,
	cards text[] NOT NULL,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 主/邊池
CREATE TABLE IF NOT EXISTS public.handpot(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	handid bigint NOT NULL,
	runno integer NOT NULL DEFAULT 1,
	potno integer NOT NULL,
	amount bigint NOT NULL,
	ismain boolean NOT NULL DEFAULT false,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 彩池分配
CREATE TABLE IF NOT EXISTS public.handpotallocation(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	handpotid bigint NOT NULL,
	winnerplayerid bigint NOT NULL,
	amount bigint NOT NULL,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 抽水
CREATE TABLE IF NOT EXISTS public.handrake(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	handid bigint NOT NULL,
	rakeamount bigint NOT NULL,
	feeamount bigint NOT NULL DEFAULT 0,
	currency varchar(10) NOT NULL,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 手牌分類統計
CREATE TABLE IF NOT EXISTS public.handcategory(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	playerid bigint NOT NULL,
	handcategory varchar(50) NOT NULL,
	handsplayed integer DEFAULT 0,
	handswon integer DEFAULT 0,
	totalprofit bigint DEFAULT 0,
	winrate numeric(5,2),
	timeperiod varchar(20) DEFAULT 'all_time',
	startdate date,
	enddate date,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 玩家日統計
CREATE TABLE IF NOT EXISTS public.playerstatdaily(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	playerid bigint NOT NULL,
	day date NOT NULL,
	handsplayed integer NOT NULL DEFAULT 0,
	vpip integer NOT NULL DEFAULT 0,
	pfr integer NOT NULL DEFAULT 0,
	threebet integer NOT NULL DEFAULT 0,
	cbet integer NOT NULL DEFAULT 0,
	wtsd integer NOT NULL DEFAULT 0,
	wsd integer NOT NULL DEFAULT 0,
	winning bigint NOT NULL DEFAULT 0,
	bbper100 numeric(8,2) NOT NULL DEFAULT 0,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 玩家統計
CREATE TABLE IF NOT EXISTS public.playerstatistic(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	playerid bigint NOT NULL,
	sessionid bigint,
	timeperiod varchar(20) DEFAULT 'all_time',
	startdate date,
	enddate date,
	handsplayed integer DEFAULT 0,
	handswon integer DEFAULT 0,
	totalwinning bigint DEFAULT 0,
	totalrakepaid bigint DEFAULT 0,
	vpiphands integer DEFAULT 0,
	vpippercentage numeric(5,2),
	pfrhands integer DEFAULT 0,
	pfrpercentage numeric(5,2),
	totalbets integer DEFAULT 0,
	totalcalls integer DEFAULT 0,
	aggressionfactor numeric(5,2),
	earlypositionhands integer DEFAULT 0,
	middlepositionhands integer DEFAULT 0,
	latepositionhands integer DEFAULT 0,
	blindhands integer DEFAULT 0,
	wenttoshowdown integer DEFAULT 0,
	wonatshowdown integer DEFAULT 0,
	showdownwinpercentage numeric(5,2),
	threebetpercentage numeric(5,2),
	foldtothreebetpercentage numeric(5,2),
	cbetpercentage numeric(5,2),
	foldtocbetpercentage numeric(5,2),
	bbper100 numeric(8,2),
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 錦標賽
CREATE TABLE IF NOT EXISTS public.tournament(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	orgid bigint NOT NULL,
	name varchar(100) NOT NULL,
	buyin bigint NOT NULL,
	fee bigint NOT NULL DEFAULT 0,
	startingstack bigint NOT NULL,
	structure jsonb NOT NULL,
	maxplayers integer,
	rebuyallowed boolean DEFAULT false,
	addonallowed boolean DEFAULT false,
	starttime timestamp with time zone,
	endtime timestamp with time zone,
	status varchar(20) DEFAULT 'scheduled',
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 錦標賽報名
CREATE TABLE IF NOT EXISTS public.tournamententry(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tournamentid bigint NOT NULL,
	playerid bigint NOT NULL,
	seatno integer,
	reentryno integer NOT NULL DEFAULT 0,
	chips bigint NOT NULL,
	status varchar(20) NOT NULL DEFAULT 'active',
	finalposition integer,
	prizeamount bigint DEFAULT 0,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 盲注結構
CREATE TABLE IF NOT EXISTS public.blindstructure(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint,
	tournamentid bigint,
	levelnumber integer NOT NULL,
	smallblind bigint NOT NULL,
	bigblind bigint NOT NULL,
	ante bigint NOT NULL DEFAULT 0,
	durationminutes integer,
	breakafter boolean DEFAULT false,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 稽核日誌
CREATE TABLE IF NOT EXISTS public.auditlog(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint,
	handid bigint,
	tablename varchar(50) NOT NULL,
	action varchar(20) NOT NULL,
	recordid bigint,
	beforedata jsonb,
	afterdata jsonb,
	ipaddress inet,
	useragent text,
	createtime timestamp with time zone NOT NULL DEFAULT now()
);

-- API 呼叫紀錄（每一次後端 API 請求都會寫一筆，供 admin.html 依使用者查詢/分頁瀏覽）
CREATE TABLE IF NOT EXISTS public.apilog(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint,
	path varchar(255) NOT NULL,
	method varchar(10) NOT NULL,
	statuscode integer,
	ipaddress inet,
	useragent text,
	createtime timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS apilog_userid_idx ON public.apilog("userid");
CREATE INDEX IF NOT EXISTS apilog_createtime_idx ON public.apilog("createtime");

-- 匯入來源
CREATE TABLE IF NOT EXISTS public.importsource(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	orgid bigint NOT NULL,
	name varchar(100) NOT NULL,
	type varchar(20) NOT NULL,
	description text,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 原始手牌歷史
CREATE TABLE IF NOT EXISTS public.rawhandhistory(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sourceid bigint NOT NULL,
	payload text NOT NULL,
	receivedtime timestamp with time zone NOT NULL DEFAULT now(),
	parsed boolean NOT NULL DEFAULT false,
	parseerror text,
	handid bigint,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 使用者-荷官關聯 (舊表, 保留相容性, 新功能改用 userstaff)
CREATE TABLE IF NOT EXISTS public.userdealer(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	userdealerid bigint NOT NULL,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 主辦人聘用的長期員工 (跨所有主辦場次有效)
CREATE TABLE IF NOT EXISTS public.userstaff(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	staffuserid bigint NOT NULL,
	role varchar(20) NOT NULL,
	status varchar(20) NOT NULL DEFAULT 'pending',
	verifytoken varchar(100),
	invitetime timestamp with time zone DEFAULT now(),
	verifytime timestamp with time zone,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 主辦場次的員工指派 (限定該場次, 不影響其他場次)
CREATE TABLE IF NOT EXISTS public.sessionstaff(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL,
	staffuserid bigint NOT NULL,
	role varchar(20) NOT NULL,
	status varchar(20) NOT NULL DEFAULT 'pending',
	verifytoken varchar(100),
	invitetime timestamp with time zone DEFAULT now(),
	verifytime timestamp with time zone,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 主辦計時器狀態 (一個場次一筆, state 用 JSONB 自由擴充)
-- 對應 control.html 與 display.html, 之後接 WebSocket 同步
CREATE TABLE IF NOT EXISTS public.sessiontimer(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL UNIQUE,
	state jsonb NOT NULL DEFAULT '{}'::jsonb,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 主辦牌局報名 (linkuser=true 才能報名)
-- 一個 user 對一個 session 只有一筆 (取消只是改 status)
CREATE TABLE IF NOT EXISTS public.sessiontimerconfig(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL UNIQUE,
	tournname varchar(200) NOT NULL DEFAULT '',
	subtitle varchar(200) NOT NULL DEFAULT '',
	startingchips bigint NOT NULL DEFAULT 0,
	buyin bigint NOT NULL DEFAULT 0,
	fee bigint NOT NULL DEFAULT 0,
	defaultbreakdur integer NOT NULL DEFAULT 10,
	soundon boolean NOT NULL DEFAULT true,
	vibeon boolean NOT NULL DEFAULT true,
	prizepoolmode varchar(20) NOT NULL DEFAULT 'auto',
	prizepoolmanual bigint NOT NULL DEFAULT 0,
	itmmode varchar(20) NOT NULL DEFAULT 'pct',
	itmpct numeric NOT NULL DEFAULT 15,
	itmcount integer NOT NULL DEFAULT 7,
	marqueetext text NOT NULL DEFAULT '',
	defaulttimebankseconds integer NOT NULL DEFAULT 15,
	timebanksoundon boolean NOT NULL DEFAULT true,
	autostartbytime boolean NOT NULL DEFAULT false,
	otherreward text NOT NULL DEFAULT '',
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);
ALTER TABLE public.sessiontimerconfig ADD COLUMN IF NOT EXISTS defaulttimebankseconds integer NOT NULL DEFAULT 15;
ALTER TABLE public.sessiontimerconfig ADD COLUMN IF NOT EXISTS timebanksoundon boolean NOT NULL DEFAULT true;
ALTER TABLE public.sessiontimerconfig ADD COLUMN IF NOT EXISTS autostartbytime boolean NOT NULL DEFAULT false;
-- 非名次獎勵(例如 bounty)的純文字記錄欄位, 不參與任何獎金自動計算
ALTER TABLE public.sessiontimerconfig ADD COLUMN IF NOT EXISTS otherreward text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS public.sessiontimebank(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL,
	tableid bigint NOT NULL UNIQUE,
	state jsonb NOT NULL DEFAULT '{}'::jsonb,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.sessiontimerlevel(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL,
	sortorder integer NOT NULL,
	type varchar(20) NOT NULL DEFAULT 'level',
	smallblind bigint NOT NULL DEFAULT 0,
	bigblind bigint NOT NULL DEFAULT 0,
	ante bigint NOT NULL DEFAULT 0,
	durationminutes integer NOT NULL DEFAULT 20,
	timemode varchar(20) NOT NULL DEFAULT 'time',
	handtargetcount integer NOT NULL DEFAULT 0,
	handcount integer NOT NULL DEFAULT 0,
	regcloseafter boolean NOT NULL DEFAULT false,
	chipraisevalues text NOT NULL DEFAULT '[]',
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);
ALTER TABLE public.sessiontimerlevel ADD COLUMN IF NOT EXISTS chipraisevalues text NOT NULL DEFAULT '[]';
ALTER TABLE public.sessiontimerlevel ADD COLUMN IF NOT EXISTS timemode varchar(20) NOT NULL DEFAULT 'time';
ALTER TABLE public.sessiontimerlevel ADD COLUMN IF NOT EXISTS handtargetcount integer NOT NULL DEFAULT 0;
ALTER TABLE public.sessiontimerlevel ADD COLUMN IF NOT EXISTS handcount integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.sessiontimerpayout(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL,
	sortorder integer NOT NULL,
	rank varchar(50) NOT NULL DEFAULT '',
	pct numeric NOT NULL DEFAULT 0,
	reward text NOT NULL DEFAULT '',
	color varchar(20) NOT NULL DEFAULT '#888',
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);
ALTER TABLE public.sessiontimerpayout ADD COLUMN IF NOT EXISTS reward text NOT NULL DEFAULT '';
ALTER TABLE public.sessiontimerpayout ADD COLUMN IF NOT EXISTS cash numeric NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.sessiontimerplayer(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL,
	sessionplayerid bigint NOT NULL,
	userid bigint NOT NULL,
	status varchar(20) NOT NULL DEFAULT 'active',
	eliminatedtime timestamp with time zone,
	place integer,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone,
	UNIQUE(sessionid,sessionplayerid)
);

CREATE TABLE IF NOT EXISTS public.sessionplayer(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	sessionid bigint NOT NULL,
	userid bigint NOT NULL,
	status varchar(20) NOT NULL DEFAULT 'registered',
	registertime timestamp with time zone DEFAULT now(),
	confirmtime timestamp with time zone,
	canceltime timestamp with time zone,
	note text,
	buyin numeric DEFAULT 0,
	fee numeric DEFAULT 0,
	rebuycount bigint DEFAULT 0,
	reentrycount bigint DEFAULT 0,
	addoncount bigint DEFAULT 0,
	prize numeric DEFAULT 0,
	ticketvalue numeric DEFAULT 0,
	paymenttype varchar(20) NOT NULL DEFAULT 'cash',
	tableid bigint,
	seatno integer,
	startchip numeric DEFAULT 0,
	prizeoverride numeric,
	place varchar DEFAULT '',
	serialno bigint,
	advancechip numeric DEFAULT 0,
	advancetargetid bigint,
	advancetime timestamp with time zone,
	advancesourceid bigint,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone,
	UNIQUE(sessionid,userid)
);

ALTER TABLE public.seating ADD COLUMN IF NOT EXISTS userid bigint;
ALTER TABLE public.seating ADD COLUMN IF NOT EXISTS sessionplayerid bigint;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS gametype varchar NOT NULL DEFAULT 'holdem';
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS blindlevel varchar;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS smallblind numeric DEFAULT 0;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS bigblind numeric DEFAULT 0;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS bigblindante numeric DEFAULT 0;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS ante numeric DEFAULT 0;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS emptybutton boolean NOT NULL DEFAULT false;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS deadsmallblind boolean NOT NULL DEFAULT false;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS levelid bigint;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS handtime timestamp with time zone;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS actionsjson text;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS recordtype varchar(40) NOT NULL DEFAULT 'hand';
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS exceptiontype varchar(80) NOT NULL DEFAULT '';
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS adjustmentsjson text;
ALTER TABLE public.hand ADD COLUMN IF NOT EXISTS familydatajson text;
ALTER TABLE public.handseating ADD COLUMN IF NOT EXISTS userid bigint;
ALTER TABLE public.handseating ADD COLUMN IF NOT EXISTS sessionplayerid bigint;
ALTER TABLE public.handseating ADD COLUMN IF NOT EXISTS specialbutton varchar;
ALTER TABLE public.handplayercard ADD COLUMN IF NOT EXISTS note text NOT NULL DEFAULT '';
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS buyin numeric DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS fee numeric DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS rebuycount bigint DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS reentrycount bigint DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS addoncount bigint DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS prize numeric DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS ticketvalue numeric DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS paymenttype varchar(20) NOT NULL DEFAULT 'cash';
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS tableid bigint;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS seatno integer;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS startchip numeric DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS prizeoverride numeric;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS place varchar DEFAULT '';
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS serialno bigint;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS advancechip numeric DEFAULT 0;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS advancetargetid bigint;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS advancetime timestamp with time zone;
ALTER TABLE public.sessionplayer ADD COLUMN IF NOT EXISTS advancesourceid bigint;
WITH numbered AS (
	SELECT id, ROW_NUMBER() OVER (PARTITION BY sessionid ORDER BY COALESCE(registertime,createtime), id) AS rn
	FROM public.sessionplayer
	WHERE serialno IS NULL
)
UPDATE public.sessionplayer sp
SET serialno=numbered.rn
FROM numbered
WHERE sp.id=numbered.id;
CREATE UNIQUE INDEX IF NOT EXISTS sessionplayer_session_serialno_unique ON public.sessionplayer(sessionid,serialno) WHERE serialno IS NOT NULL;

-- 通知 (api/notification.py 在用, 使用者站內通知)
CREATE TABLE IF NOT EXISTS public.notification(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	sessionid bigint,
	type varchar(50) NOT NULL DEFAULT '',
	title varchar(200) NOT NULL DEFAULT '',
	message text NOT NULL DEFAULT '',
	readed boolean NOT NULL DEFAULT false,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 使用者計分牌組合 (一個使用者可有多組, 對應 profile 的計分牌組合設定)
CREATE TABLE IF NOT EXISTS public.userchipset(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	name varchar(30) NOT NULL DEFAULT '',
	sortorder integer NOT NULL DEFAULT 0,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 計分牌組合內的單一計分牌 (一行一顆, 比照 sessionchip 的做法)
CREATE TABLE IF NOT EXISTS public.userchipsetchip(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chipsetid bigint NOT NULL,
	shape varchar(20) NOT NULL DEFAULT 'circle',
	value bigint NOT NULL DEFAULT 0,
	color varchar(20) NOT NULL DEFAULT '#888888',
	sortorder integer NOT NULL DEFAULT 0,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 把舊的 user.chipsets JSON 欄位遷移進 userchipset/userchipsetchip 後移除該欄位。
-- 用 information_schema 判斷欄位是否還在, 已遷移過(欄位不存在)就整段跳過, 可重複執行。
DO $$
DECLARE
	urow record;
	setrec jsonb;
	chiprec jsonb;
	newsetid bigint;
	setidx integer;
	chipidx integer;
BEGIN
	IF EXISTS (
		SELECT 1 FROM information_schema.columns
		WHERE table_schema='public' AND table_name='user' AND column_name='chipsets'
	) THEN
		FOR urow IN
			SELECT id, chipsets FROM public."user"
			WHERE chipsets IS NOT NULL AND chipsets <> '' AND chipsets <> '[]'
		LOOP
			BEGIN
				-- 此 user 已經有 userchipset 資料就跳過, 避免重複遷移
				IF EXISTS (SELECT 1 FROM public.userchipset WHERE userid=urow.id) THEN
					CONTINUE;
				END IF;
				setidx := 0;
				FOR setrec IN SELECT * FROM jsonb_array_elements(urow.chipsets::jsonb) LOOP
					setidx := setidx + 1;
					INSERT INTO public.userchipset(userid,name,sortorder)
					VALUES (
						urow.id,
						LEFT(COALESCE(NULLIF(setrec->>'name',''),'計分牌組合 '||setidx),30),
						setidx
					)
					RETURNING id INTO newsetid;
					chipidx := 0;
					FOR chiprec IN SELECT * FROM jsonb_array_elements(COALESCE(setrec->'chips','[]'::jsonb)) LOOP
						chipidx := chipidx + 1;
						INSERT INTO public.userchipsetchip(chipsetid,shape,value,color,sortorder)
						VALUES (
							newsetid,
							CASE WHEN setrec IS NOT NULL AND chiprec->>'shape'='square' THEN 'square' ELSE 'circle' END,
							COALESCE(NULLIF(chiprec->>'value','')::bigint,0),
							COALESCE(NULLIF(chiprec->>'color',''),'#888888'),
							chipidx
						);
					END LOOP;
				END LOOP;
			EXCEPTION WHEN OTHERS THEN
				-- 單一 user 的舊 JSON 格式壞掉不要中斷整批遷移
				RAISE WARNING 'chipsets migrate skip user %: %', urow.id, SQLERRM;
			END;
		END LOOP;
		ALTER TABLE public."user" DROP COLUMN chipsets;
	END IF;
END$$;

-- 使用者工具最愛 (一行一個工具路徑, 取代 user.toolfavorites JSON 欄位)
CREATE TABLE IF NOT EXISTS public.usertoolfavorite(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid bigint NOT NULL,
	tool varchar(100) NOT NULL DEFAULT '',
	sortorder integer NOT NULL DEFAULT 0,
	createtime timestamp with time zone NOT NULL DEFAULT now(),
	updatetime timestamp with time zone NOT NULL DEFAULT now(),
	deletetime timestamp with time zone
);

-- 把舊的 user.toolfavorites JSON 陣列遷移進 usertoolfavorite 後移除該欄位。
-- 同樣用 information_schema 判斷欄位是否還在, 已遷移過就整段跳過, 可重複執行。
DO $$
DECLARE
	urow record;
	favval text;
	favidx integer;
BEGIN
	IF EXISTS (
		SELECT 1 FROM information_schema.columns
		WHERE table_schema='public' AND table_name='user' AND column_name='toolfavorites'
	) THEN
		FOR urow IN
			SELECT id, toolfavorites FROM public."user"
			WHERE toolfavorites IS NOT NULL AND toolfavorites <> '' AND toolfavorites <> '[]'
		LOOP
			BEGIN
				IF EXISTS (SELECT 1 FROM public.usertoolfavorite WHERE userid=urow.id) THEN
					CONTINUE;
				END IF;
				favidx := 0;
				FOR favval IN SELECT value FROM jsonb_array_elements_text(urow.toolfavorites::jsonb) AS t(value) LOOP
					-- 只收白名單格式, 與後端 parsetoolfavorites 一致
					IF favval ~ '^(tool/[a-z0-9]+\.html|gto\.html|flopsolver\.html)$' THEN
						favidx := favidx + 1;
						INSERT INTO public.usertoolfavorite(userid,tool,sortorder)
						VALUES (urow.id, favval, favidx);
					END IF;
				END LOOP;
			EXCEPTION WHEN OTHERS THEN
				RAISE WARNING 'toolfavorites migrate skip user %: %', urow.id, SQLERRM;
			END;
		END LOOP;
		ALTER TABLE public."user" DROP COLUMN toolfavorites;
	END IF;
END$$;
"""

# ---------------------------------------------------------------------------
# 預設資料 (字典表) - 用 ON CONFLICT 避免重複插入
# ---------------------------------------------------------------------------
DEFAULTSQL="""
-- 確保字典表的 id 欄位有 sequence default
-- (處理舊 schema 沒掛 default 的情況, 否則 INSERT 不帶 id 會違反 NOT NULL)
DO $$
DECLARE
	tbl text;
	idattidentity text;
BEGIN
	FOREACH tbl IN ARRAY ARRAY['gametype','limittype','stacktype','eventtype'] LOOP
		-- 本檔建表用 GENERATED BY DEFAULT AS IDENTITY, identity 欄位不能再掛 sequence default
		-- (全新資料庫會報 "column id of relation xxx is an identity column" 使初始化失敗)。
		-- 只有舊 schema 那種「id 沒有 identity 也沒有 default」的情況才需要補 sequence。
		SELECT a.attidentity INTO idattidentity
		FROM pg_attribute a
		JOIN pg_class c ON c.oid=a.attrelid
		JOIN pg_namespace n ON n.oid=c.relnamespace
		WHERE n.nspname='public' AND c.relname=tbl AND a.attname='id' AND a.attnum>0 AND NOT a.attisdropped;

		IF idattidentity IS NULL OR idattidentity='' THEN
			EXECUTE format('CREATE SEQUENCE IF NOT EXISTS public.%I_id_seq', tbl);
			EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT nextval(''public.%I_id_seq'')', tbl, tbl);
			EXECUTE format('SELECT setval(''public.%I_id_seq'', GREATEST(1, COALESCE((SELECT MAX(id) FROM public.%I), 0)))', tbl, tbl);
		END IF;
	END LOOP;
END$$;

-- currency
INSERT INTO public.currency(code,name,symbol,decimals) VALUES
	('TWD','新台幣','NT$',0),
	('USD','美元','$',2),
	('CNY','人民幣','¥',2),
	('JPY','日圓','¥',0),
	('EUR','歐元','€',2)
ON CONFLICT(code) DO NOTHING;

-- gametype (對應 frontend translate.js: HE/O/ST/MX/Z)
INSERT INTO public.gametype(name,code,description) VALUES
	('Texas Hold''em','HE','德州撲克'),
	('Omaha','OM','奧馬哈'),
	('Omaha Hi-Lo','O8','奧馬哈高低'),
	('Omaha5','O5','5張奧馬哈'),
	('Omaha5 Hi-Lo','BO','5張奧馬哈高低(Big O)'),
	('7 card Stud','ST','7張梭哈'),
	('7 card Stud Razz','RA','7張梭哈低牌'),
	('7 card Stud Hi-Lo','S8','7張梭哈高低'),
	('Crazy Pineapple','CP','瘋狂菠蘿'),
	('Super Hold''em','SH','超級德州(三卡賽)'),
	('Short Deck','SD','短牌'),
	('Badugi','BU','巴杜基'),
	('A-5 Single Draw','AS','A-5單次換牌'),
	('A-5 Double Draw','AD','A-5兩次換牌'),
	('A-5 Triple Draw','AT','A-5三次換牌'),
	('2-7 Single Draw','DS','2-7單次換牌'),
	('2-7 Double Draw','DD','2-7兩次換牌'),
	('2-7 Triple Draw','DT','2-7三次換牌'),
	('Other','ZZ','其他')
ON CONFLICT(code) DO NOTHING;

-- limittype (對應 NL/PL/FL)
INSERT INTO public.limittype(name,code,description) VALUES
	('No Limit','NL','無限注'),
	('Pot Limit','PL','底池限注'),
	('Fixed Limit','FL','固定注')
ON CONFLICT(code) DO NOTHING;

-- stacktype (對應 N/D/L/S/M/U)
INSERT INTO public.stacktype(name,code,description) VALUES
	('Normal','N','正常'),
	('Deep','D','深籌'),
	('Monster','L','深籌'),
	('Super','S','極深籌'),
	('Mega','M','巨籌'),
	('Ultra','U','極巨籌')
ON CONFLICT(code) DO NOTHING;

-- eventtype (對應 OD/SA/ND)
INSERT INTO public.eventtype(name,code,description) VALUES
	('One Day','OD','單日賽'),
	('Satellite','SA','衛星賽'),
	('Milestone Satellite','MS','里程碑衛星賽'),
	('Multi Day','ND','多日賽')
ON CONFLICT(code) DO NOTHING;
"""


def main():
	# 連線
	try:
		db=psycopg2.connect(
			host=DBHOST,
			dbname=DBNAME,
			user=DBUSER,
			password=DBPASSWORD,
			port=DBPORT
		)
	except Exception as error:
		print(f"[dbinitialize] 無法連線資料庫: {error}")
		sys.exit(1)

	cursor=db.cursor()

	# 建立 schema (全部用 IF NOT EXISTS, 重跑不會破壞既有資料)
	try:
		cursor.execute(SCHEMASQL)
		db.commit()
		print("[dbinitialize] schema 檢查 / 建立完成")
	except Exception as error:
		db.rollback()
		print(f"[dbinitialize] schema 建立失敗: {error}")
		cursor.close()
		db.close()
		sys.exit(1)

	# 插入字典預設資料 (ON CONFLICT 避免覆蓋)
	try:
		cursor.execute(DEFAULTSQL)
		db.commit()
		print("[dbinitialize] 預設資料檢查 / 插入完成")
	except Exception as error:
		db.rollback()
		print(f"[dbinitialize] 預設資料插入失敗: {error}")
		cursor.close()
		db.close()
		sys.exit(1)

	cursor.close()
	db.close()
	print("[dbinitialize] 全部完成")


if __name__=="__main__":
	main()
